const themesDe = {
  "La maison": [
    {
      english: "der Tisch",
      french: "Table",
      hintEn: "Ein flaches Möbelstück mit Beinen, zum Essen oder Arbeiten",
      hintFr: "Surface plate avec des pieds, pour manger ou travailler",
    },
    {
      english: "der Stuhl",
      french: "Chaise",
      hintEn: "Ein Sitz mit einer Rückenlehne, für eine Person",
      hintFr: "Un siège avec un dossier, pour une personne",
    },
    {
      english: "das Fenster",
      french: "Fenêtre",
      hintEn: "Eine Öffnung in der Wand mit Glas, um nach draußen zu sehen",
      hintFr: "Une ouverture dans un mur avec du verre, pour voir dehors",
    },
    {
      english: "das Bett",
      french: "Lit",
      hintEn: "Dort schläfst du in der Nacht",
      hintFr: "Là où tu dors la nuit",
    },
    {
      english: "die Tür",
      french: "Porte",
      hintEn: "Du öffnest sie, um einen Raum zu betreten oder zu verlassen",
      hintFr: "Tu l'ouvres pour entrer ou sortir d'une pièce",
    },
    {
      english: "die Küche",
      french: "Cuisine",
      hintEn: "Der Raum, in dem man das Essen zubereitet",
      hintFr: "La pièce où on prépare les repas",
    },
    {
      english: "das Badezimmer",
      french: "Salle de bain",
      hintEn: "Der Raum mit einer Dusche oder Badewanne",
      hintFr: "La pièce avec une douche ou une baignoire",
    },
    {
      english: "der Garten",
      french: "Jardin",
      hintEn: "Ein Bereich draußen mit Pflanzen und Blumen",
      hintFr: "Un espace extérieur avec des plantes et des fleurs",
    },
    {
      english: "das Dach",
      french: "Toit",
      hintEn: "Der obere Teil des Hauses, der vor Regen schützt",
      hintFr: "La partie en haut de la maison qui protège de la pluie",
    },
    {
      english: "die Wand",
      french: "Mur",
      hintEn: "Eine senkrechte Fläche, die Zimmer trennt",
      hintFr: "Une surface verticale qui sépare les pièces",
    },
    {
      english: "der Boden",
      french: "Sol",
      hintEn: "Die Fläche, auf der du in einem Raum gehst",
      hintFr: "La surface sur laquelle tu marches dans une pièce",
    },
    {
      english: "die Treppe",
      french: "Escalier",
      hintEn: "Stufen, die nach oben oder unten zwischen den Stockwerken führen",
      hintFr: "Des marches pour monter ou descendre entre les étages",
    },
  ],
  "La nourriture": [
    {
      english: "der Apfel",
      french: "Pomme",
      hintEn: "Eine runde Frucht, oft rot oder grün",
      hintFr: "Un fruit rond, souvent rouge ou vert",
    },
    {
      english: "das Brot",
      french: "Pain",
      hintEn: "Aus Mehl gemacht, man isst es jeden Tag",
      hintFr: "Fait avec de la farine, on en mange tous les jours",
    },
    {
      english: "der Käse",
      french: "Fromage",
      hintEn: "Aus Milch gemacht, oft gelb",
      hintFr: "Fait avec du lait, souvent jaune",
    },
    {
      english: "der Kuchen",
      french: "Gâteau",
      hintEn: "Ein süßes Dessert für Geburtstage",
      hintFr: "Un dessert sucré pour les anniversaires",
    },
    {
      english: "die Milch",
      french: "Lait",
      hintEn: "Ein weißes Getränk, das von Kühen kommt",
      hintFr: "Une boisson blanche qui vient des vaches",
    },
    {
      english: "das Wasser",
      french: "Eau",
      hintEn: "Eine klare Flüssigkeit, die du jeden Tag trinkst",
      hintFr: "Un liquide transparent que tu bois chaque jour",
    },
    {
      english: "das Hähnchen",
      french: "Poulet",
      hintEn: "Ein Vogel, den man essen kann, sehr verbreitetes Fleisch",
      hintFr: "Un oiseau que l'on mange, une viande très courante",
    },
    {
      english: "der Reis",
      french: "Riz",
      hintEn: "Kleine weiße Körner, in Asien sehr beliebt",
      hintFr: "Petits grains blancs, très mangés en Asie",
    },
    {
      english: "der Salat",
      french: "Salade",
      hintEn: "Ein Gericht mit Kopfsalat und Gemüse",
      hintFr: "Un plat avec de la laitue et des légumes",
    },
    {
      english: "die Butter",
      french: "Beurre",
      hintEn: "Ein gelber Aufstrich aus Sahne",
      hintFr: "Une pâte jaune faite à partir de crème",
    },
    {
      english: "das Ei",
      french: "Oeuf",
      hintEn: "Es kommt vom Huhn, mit einer Schale",
      hintFr: "Il vient de la poule, avec une coquille",
    },
    {
      english: "der Zucker",
      french: "Sucre",
      hintEn: "Ein süßes weißes Pulver für Tee oder Kaffee",
      hintFr: "Une poudre blanche et sucrée pour le thé ou le café",
    },
  ],
  "Les animaux": [
    {
      english: "der Hund",
      french: "Chien",
      hintEn: "Ein Haustier, das bellt und mit dem Schwanz wedelt",
      hintFr: "Un animal qui aboie et remue la queue",
    },
    {
      english: "die Katze",
      french: "Chat",
      hintEn: "Ein Haustier, das schnurrt und Mäuse fängt",
      hintFr: "Un animal qui ronronne et attrape les souris",
    },
    {
      english: "der Vogel",
      french: "Oiseau",
      hintEn: "Ein Tier mit Flügeln, das fliegen kann",
      hintFr: "Un animal avec des ailes qui peut voler",
    },
    {
      english: "der Fisch",
      french: "Poisson",
      hintEn: "Ein Tier, das im Wasser lebt",
      hintFr: "Un animal qui vit dans l'eau",
    },
    {
      english: "das Pferd",
      french: "Cheval",
      hintEn: "Ein großes Tier, auf dem man reiten kann",
      hintFr: "Un grand animal que l'on peut monter",
    },
    {
      english: "das Kaninchen",
      french: "Lapin",
      hintEn: "Ein kleines Tier mit langen Ohren, das hüpft",
      hintFr: "Un petit animal avec de longues oreilles qui saute",
    },
    {
      english: "die Maus",
      french: "Souris",
      hintEn: "Ein sehr kleines Tier, das Käse mag",
      hintFr: "Un très petit animal qui aime le fromage",
    },
    {
      english: "die Kuh",
      french: "Vache",
      hintEn: "Ein großes Bauernhoftier, das Milch gibt",
      hintFr: "Un grand animal de ferme qui donne du lait",
    },
    {
      english: "das Schwein",
      french: "Cochon",
      hintEn: "Ein rosa Bauernhoftier, das Schlamm liebt",
      hintFr: "Un animal de ferme rose qui aime la boue",
    },
    {
      english: "das Schaf",
      french: "Mouton",
      hintEn: "Ein Bauernhoftier mit weicher weißer Wolle",
      hintFr: "Un animal de ferme avec de la laine blanche",
    },
    {
      english: "die Ente",
      french: "Canard",
      hintEn: "Ein Vogel, der schwimmt und 'quak' macht",
      hintFr: "Un oiseau qui nage et fait 'coin coin'",
    },
    {
      english: "der Frosch",
      french: "Grenouille",
      hintEn: "Ein kleines grünes Tier, das in der Nähe von Wasser springt",
      hintFr: "Un petit animal vert qui saute près de l'eau",
    },
  ],
  "La nature": [
    {
      english: "die Sonne",
      french: "Soleil",
      hintEn: "Der große gelbe Stern am Himmel tagsüber",
      hintFr: "La grande étoile jaune dans le ciel pendant la journée",
    },
    {
      english: "der Mond",
      french: "Lune",
      hintEn: "Man sieht ihn nachts am Himmel",
      hintFr: "On la voit dans le ciel la nuit",
    },
    {
      english: "der Stern",
      french: "Étoile",
      hintEn: "Ein kleiner leuchtender Punkt am Nachthimmel",
      hintFr: "Un petit point brillant dans le ciel la nuit",
    },
    {
      english: "die Wolke",
      french: "Nuage",
      hintEn: "Eine weiße oder graue Form am Himmel",
      hintFr: "Une forme blanche ou grise dans le ciel",
    },
    {
      english: "der Regen",
      french: "Pluie",
      hintEn: "Wasser, das vom Himmel fällt",
      hintFr: "De l'eau qui tombe du ciel",
    },
    {
      english: "der Baum",
      french: "Arbre",
      hintEn: "Eine große Pflanze mit Stamm und Blättern",
      hintFr: "Une grande plante avec un tronc et des feuilles",
    },
    {
      english: "die Blume",
      french: "Fleur",
      hintEn: "Eine bunte Pflanze, die gut riecht",
      hintFr: "Une plante colorée qui sent bon",
    },
    {
      english: "der Fluss",
      french: "Rivière",
      hintEn: "Ein langer Wasserlauf durch das Land",
      hintFr: "Un long cours d'eau à travers la terre",
    },
    {
      english: "der Berg",
      french: "Montagne",
      hintEn: "Ein sehr hohes Stück Land, mit Schnee auf der Spitze",
      hintFr: "Un terrain très élevé, avec de la neige au sommet",
    },
    {
      english: "das Meer",
      french: "Mer",
      hintEn: "Eine große Fläche aus Salzwasser",
      hintFr: "Une grande étendue d'eau salée",
    },
    {
      english: "der Schnee",
      french: "Neige",
      hintEn: "Weiß und kalt, er fällt im Winter",
      hintFr: "Blanc et froid, ça tombe en hiver",
    },
    {
      english: "der Wind",
      french: "Vent",
      hintEn: "Bewegte Luft, die man fühlt, aber nicht sieht",
      hintFr: "De l'air qui bouge, qu'on sent mais qu'on ne voit pas",
    },
  ],
  "L'école": [
    {
      english: "das Buch",
      french: "Livre",
      hintEn: "Du liest es, es hat Seiten",
      hintFr: "Tu le lis, il a des pages",
    },
    {
      english: "die Schule",
      french: "École",
      hintEn: "Ein Ort, wo Kinder hingehen, um zu lernen",
      hintFr: "Un endroit où les enfants vont pour apprendre",
    },
    {
      english: "der Kugelschreiber",
      french: "Stylo",
      hintEn: "Du schreibst damit, er benutzt Tinte",
      hintFr: "Tu écris avec, il utilise de l'encre",
    },
    {
      english: "der Bleistift",
      french: "Crayon",
      hintEn: "Du schreibst damit, du kannst es ausradieren",
      hintFr: "Tu écris avec, tu peux effacer",
    },
    {
      english: "der Lehrer",
      french: "Professeur",
      hintEn: "Eine Person, die in einer Schule unterrichtet",
      hintFr: "Une personne qui enseigne à l'école",
    },
    {
      english: "der Schüler",
      french: "Élève",
      hintEn: "Eine Person, die in einer Schule lernt",
      hintFr: "Une personne qui apprend à l'école",
    },
    {
      english: "der Schreibtisch",
      french: "Bureau",
      hintEn: "Ein Tisch, an dem du arbeitest oder lernst",
      hintFr: "Une table où tu travailles ou étudies",
    },
    {
      english: "die Hausaufgaben",
      french: "Devoirs",
      hintEn: "Schularbeit, die du zu Hause machst",
      hintFr: "Du travail scolaire que tu fais à la maison",
    },
    {
      english: "die Lektion",
      french: "Leçon",
      hintEn: "Eine Zeit des Lernens im Unterricht",
      hintFr: "Un moment d'apprentissage en classe",
    },
    {
      english: "das Heft",
      french: "Cahier",
      hintEn: "Ein Buch mit leeren Seiten zum Schreiben",
      hintFr: "Un livre avec des pages vides pour écrire",
    },
    {
      english: "die Tafel",
      french: "Tableau",
      hintEn: "Eine große dunkle Fläche, auf die der Lehrer schreibt",
      hintFr: "Un grand tableau sombre sur lequel le professeur écrit",
    },
    {
      english: "die Tasche",
      french: "Sac",
      hintEn: "Du trägst deine Sachen darin",
      hintFr: "Tu transportes tes affaires dedans",
    },
  ],
  "Les vêtements": [
    {
      english: "das Hemd",
      french: "Chemise",
      hintEn: "Du trägst es am Oberkörper, mit Knöpfen",
      hintFr: "Tu le portes sur le haut du corps, avec des boutons",
    },
    {
      english: "das Kleid",
      french: "Robe",
      hintEn: "Ein einteiliges Kleidungsstück, oft von Mädchen getragen",
      hintFr: "Un vêtement d'une seule pièce, souvent porté par les filles",
    },
    {
      english: "die Schuhe",
      french: "Chaussures",
      hintEn: "Du trägst sie an den Füßen zum Gehen",
      hintFr: "Tu les portes aux pieds pour marcher",
    },
    {
      english: "der Hut",
      french: "Chapeau",
      hintEn: "Du trägst ihn auf dem Kopf",
      hintFr: "Tu le portes sur la tête",
    },
    {
      english: "der Mantel",
      french: "Manteau",
      hintEn: "Ein warmes Kleidungsstück für kaltes Wetter",
      hintFr: "Un vêtement chaud pour le froid",
    },
    {
      english: "die Hose",
      french: "Pantalon",
      hintEn: "Kleidung für die Beine, mit zwei Löchern",
      hintFr: "Vêtement pour les jambes, avec deux trous",
    },
    {
      english: "die Socken",
      french: "Chaussettes",
      hintEn: "Du trägst sie an den Füßen, in den Schuhen",
      hintFr: "Tu les portes aux pieds, dans les chaussures",
    },
    {
      english: "die Handschuhe",
      french: "Gants",
      hintEn: "Du trägst sie an den Händen, wenn es kalt ist",
      hintFr: "Tu les portes aux mains quand il fait froid",
    },
    {
      english: "der Schal",
      french: "Écharpe",
      hintEn: "Du wickelst ihn im Winter um den Hals",
      hintFr: "Tu l'enroules autour du cou en hiver",
    },
    {
      english: "der Rock",
      french: "Jupe",
      hintEn: "Ein Kleidungsstück, das von der Taille hängt",
      hintFr: "Un vêtement qui pend à partir de la taille",
    },
    {
      english: "der Pullover",
      french: "Pull",
      hintEn: "Ein warmes gestricktes Oberteil für kalte Tage",
      hintFr: "Un haut en maille chaud pour les jours froids",
    },
    {
      english: "die Jacke",
      french: "Veste",
      hintEn: "Ein leichter Mantel, den du draußen trägst",
      hintFr: "Un manteau léger que tu portes dehors",
    },
  ],
  "Le corps humain": [
    {
      english: "der Kopf",
      french: "Tête",
      hintEn: "Der obere Teil deines Körpers",
      hintFr: "La partie en haut de ton corps",
    },
    {
      english: "die Hand",
      french: "Main",
      hintEn: "Du benutzt sie, um Dinge zu greifen",
      hintFr: "Tu l'utilises pour attraper des choses",
    },
    {
      english: "der Arm",
      french: "Bras",
      hintEn: "Zwischen deiner Schulter und deiner Hand",
      hintFr: "Entre ton épaule et ta main",
    },
    {
      english: "das Bein",
      french: "Jambe",
      hintEn: "Du benutzt sie zum Gehen",
      hintFr: "Tu les utilises pour marcher",
    },
    {
      english: "der Fuß",
      french: "Pied",
      hintEn: "Am unteren Ende deines Beins",
      hintFr: "En bas de ta jambe",
    },
    {
      english: "das Auge",
      french: "Œil",
      hintEn: "Du siehst damit",
      hintFr: "Tu vois avec",
    },
    {
      english: "das Ohr",
      french: "Oreille",
      hintEn: "Du hörst damit",
      hintFr: "Tu entends avec",
    },
    {
      english: "die Nase",
      french: "Nez",
      hintEn: "Du riechst damit",
      hintFr: "Tu sens les odeurs avec",
    },
    {
      english: "der Mund",
      french: "Bouche",
      hintEn: "Du isst und sprichst damit",
      hintFr: "Tu manges et parles avec",
    },
    {
      english: "die Haare",
      french: "Cheveux",
      hintEn: "Sie wachsen auf deinem Kopf",
      hintFr: "Ça pousse sur ta tête",
    },
    {
      english: "das Herz",
      french: "Cœur",
      hintEn: "Es pumpt das Blut durch deinen Körper",
      hintFr: "Il pompe le sang dans ton corps",
    },
    {
      english: "der Finger",
      french: "Doigt",
      hintEn: "Du hast zehn davon an deinen Händen",
      hintFr: "Tu en as dix sur tes mains",
    },
  ],
  "La famille": [
    {
      english: "die Mutter",
      french: "Mère",
      hintEn: "Die Frau, die dich zur Welt gebracht hat",
      hintFr: "La femme qui t'a mis au monde",
    },
    {
      english: "der Vater",
      french: "Père",
      hintEn: "Dein männliches Elternteil",
      hintFr: "Ton parent masculin",
    },
    {
      english: "der Bruder",
      french: "Frère",
      hintEn: "Ein Junge mit denselben Eltern wie du",
      hintFr: "Un garçon avec les mêmes parents que toi",
    },
    {
      english: "die Schwester",
      french: "Sœur",
      hintEn: "Ein Mädchen mit denselben Eltern wie du",
      hintFr: "Une fille avec les mêmes parents que toi",
    },
    {
      english: "die Großmutter",
      french: "Grand-mère",
      hintEn: "Die Mutter deiner Mutter oder deines Vaters",
      hintFr: "La mère de ton parent",
    },
    {
      english: "der Großvater",
      french: "Grand-père",
      hintEn: "Der Vater deiner Mutter oder deines Vaters",
      hintFr: "Le père de ton parent",
    },
    {
      english: "der Onkel",
      french: "Oncle",
      hintEn: "Der Bruder deiner Mutter oder deines Vaters",
      hintFr: "Le frère de ton parent",
    },
    {
      english: "die Tante",
      french: "Tante",
      hintEn: "Die Schwester deiner Mutter oder deines Vaters",
      hintFr: "La sœur de ton parent",
    },
    {
      english: "der Cousin",
      french: "Cousin",
      hintEn: "Das Kind deines Onkels oder deiner Tante",
      hintFr: "L'enfant de ton oncle ou ta tante",
    },
    {
      english: "das Baby",
      french: "Bébé",
      hintEn: "Ein sehr junges Kind",
      hintFr: "Un très jeune enfant",
    },
    {
      english: "der Sohn",
      french: "Fils",
      hintEn: "Ein männliches Kind",
      hintFr: "Un enfant masculin",
    },
    {
      english: "die Tochter",
      french: "Fille",
      hintEn: "Ein weibliches Kind",
      hintFr: "Un enfant féminin",
    },
  ],
  "Les couleurs": [
    {
      english: "rot",
      french: "Rouge",
      hintEn: "Die Farbe der Erdbeeren",
      hintFr: "La couleur des fraises",
    },
    {
      english: "blau",
      french: "Bleu",
      hintEn: "Die Farbe des Himmels",
      hintFr: "La couleur du ciel",
    },
    {
      english: "grün",
      french: "Vert",
      hintEn: "Die Farbe des Grases",
      hintFr: "La couleur de l'herbe",
    },
    {
      english: "gelb",
      french: "Jaune",
      hintEn: "Die Farbe der Sonne",
      hintFr: "La couleur du soleil",
    },
    {
      english: "weiß",
      french: "Blanc",
      hintEn: "Die Farbe des Schnees",
      hintFr: "La couleur de la neige",
    },
    {
      english: "schwarz",
      french: "Noir",
      hintEn: "Die Farbe der Nacht",
      hintFr: "La couleur de la nuit",
    },
    {
      english: "orange",
      french: "Orange",
      hintEn: "Die Farbe einer Karotte",
      hintFr: "La couleur d'une carotte",
    },
    {
      english: "rosa",
      french: "Rose",
      hintEn: "Ein heller Ton von Rot",
      hintFr: "Une teinte claire de rouge",
    },
    {
      english: "lila",
      french: "Violet",
      hintEn: "Eine Mischung aus Rot und Blau",
      hintFr: "Un mélange de rouge et bleu",
    },
    {
      english: "braun",
      french: "Marron",
      hintEn: "Die Farbe der Schokolade",
      hintFr: "La couleur du chocolat",
    },
    {
      english: "grau",
      french: "Gris",
      hintEn: "Eine Mischung aus Schwarz und Weiß",
      hintFr: "Un mélange de noir et blanc",
    },
    {
      english: "gold",
      french: "Doré",
      hintEn: "Eine glänzende gelbe Farbe",
      hintFr: "Une couleur jaune brillante",
    },
  ],
  "Les fruits": [
    {
      english: "die Erdbeere",
      french: "Fraise",
      hintEn: "Eine kleine rote Frucht mit Samen außen",
      hintFr: "Un petit fruit rouge avec des graines dehors",
    },
    {
      english: "die Banane",
      french: "Banane",
      hintEn: "Eine lange gelbe Frucht",
      hintFr: "Un long fruit jaune",
    },
    {
      english: "die Traube",
      french: "Raisin",
      hintEn: "Kleine runde Früchte, die in Trauben wachsen",
      hintFr: "Petits fruits ronds qui poussent en grappes",
    },
    {
      english: "die Zitrone",
      french: "Citron",
      hintEn: "Eine saure gelbe Frucht",
      hintFr: "Un fruit jaune acide",
    },
    {
      english: "der Pfirsich",
      french: "Pêche",
      hintEn: "Eine weiche, samtige Frucht mit einem Kern",
      hintFr: "Un fruit doux et duveteux avec un noyau",
    },
    {
      english: "die Kirsche",
      french: "Cerise",
      hintEn: "Eine kleine rote Frucht mit einem Stiel",
      hintFr: "Un petit fruit rouge avec une tige",
    },
    {
      english: "die Birne",
      french: "Poire",
      hintEn: "Glockenförmig, grün oder gelb",
      hintFr: "En forme de cloche, vert ou jaune",
    },
    {
      english: "die Wassermelone",
      french: "Pastèque",
      hintEn: "Eine große grüne Frucht, innen rot",
      hintFr: "Un gros fruit vert, rouge à l'intérieur",
    },
    {
      english: "die Ananas",
      french: "Ananas",
      hintEn: "Eine tropische Frucht mit stacheligen Blättern",
      hintFr: "Un fruit tropical avec des feuilles piquantes",
    },
    {
      english: "die Himbeere",
      french: "Framboise",
      hintEn: "Eine kleine weiche rote Beere",
      hintFr: "Un petit fruit rouge et mou",
    },
    {
      english: "die Pflaume",
      french: "Prune",
      hintEn: "Eine kleine violette Frucht mit glatter Haut",
      hintFr: "Un petit fruit violet à peau lisse",
    },
    {
      english: "die Aprikose",
      french: "Abricot",
      hintEn: "Eine kleine orangefarbene Frucht wie ein kleiner Pfirsich",
      hintFr: "Un petit fruit orange comme une petite pêche",
    },
  ],
  "Les légumes": [
    {
      english: "die Karotte",
      french: "Carotte",
      hintEn: "Ein langes oranges Gemüse",
      hintFr: "Un long légume orange",
    },
    {
      english: "die Kartoffel",
      french: "Pomme de terre",
      hintEn: "Man macht Pommes frites daraus",
      hintFr: "On fait des frites avec",
    },
    {
      english: "die Tomate",
      french: "Tomate",
      hintEn: "Eine rote Frucht, die als Gemüse verwendet wird",
      hintFr: "Un fruit rouge utilisé comme légume",
    },
    {
      english: "die Zwiebel",
      french: "Oignon",
      hintEn: "Sie bringt dich zum Weinen, wenn du sie schneidest",
      hintFr: "Il te fait pleurer quand tu le coupes",
    },
    {
      english: "die Paprika",
      french: "Poivron",
      hintEn: "Kann rot, grün oder gelb sein",
      hintFr: "Peut être rouge, vert ou jaune",
    },
    {
      english: "der Kopfsalat",
      french: "Laitue",
      hintEn: "Grüne Blätter für Salate",
      hintFr: "Des feuilles vertes pour les salades",
    },
    {
      english: "die Gurke",
      french: "Concombre",
      hintEn: "Ein langes grünes Gemüse, innen kühl",
      hintFr: "Un long légume vert, frais à l'intérieur",
    },
    {
      english: "der Pilz",
      french: "Champignon",
      hintEn: "Er wächst im Wald und hat einen Hut",
      hintFr: "Il pousse dans la forêt, avec un chapeau",
    },
    {
      english: "der Mais",
      french: "Maïs",
      hintEn: "Gelbe Körner auf einem Kolben",
      hintFr: "Des grains jaunes sur un épi",
    },
    {
      english: "die Erbse",
      french: "Petit pois",
      hintEn: "Kleine grüne runde Gemüse in einer Schote",
      hintFr: "Petits légumes verts ronds dans une cosse",
    },
    {
      english: "der Knoblauch",
      french: "Ail",
      hintEn: "Eine Knolle mit starkem Geruch zum Kochen",
      hintFr: "Un bulbe à forte odeur pour cuisiner",
    },
    {
      english: "der Spinat",
      french: "Épinard",
      hintEn: "Dunkelgrüne Blätter, Popeyes Essen",
      hintFr: "Des feuilles vert foncé, la nourriture de Popeye",
    },
  ],
  "Les sports": [
    {
      english: "der Fußball",
      french: "Football",
      hintEn: "Ein Mannschaftssport mit einem runden Ball und Toren",
      hintFr: "Un sport d'équipe avec un ballon rond et des buts",
    },
    {
      english: "der Basketball",
      french: "Basket",
      hintEn: "Du wirfst einen Ball in einen hohen Korb",
      hintFr: "Tu lances un ballon dans un panier en hauteur",
    },
    {
      english: "das Tennis",
      french: "Tennis",
      hintEn: "Du schlägst einen Ball mit einem Schläger über ein Netz",
      hintFr: "Tu frappes une balle avec une raquette par-dessus un filet",
    },
    {
      english: "das Schwimmen",
      french: "Natation",
      hintEn: "Sich im Wasser mit dem Körper fortbewegen",
      hintFr: "Se déplacer dans l'eau avec son corps",
    },
    {
      english: "das Laufen",
      french: "Course",
      hintEn: "Sich schnell auf den Füßen bewegen",
      hintFr: "Se déplacer vite sur ses pieds",
    },
    {
      english: "das Radfahren",
      french: "Cyclisme",
      hintEn: "Mit dem Fahrrad fahren",
      hintFr: "Faire du vélo",
    },
    {
      english: "das Skifahren",
      french: "Ski",
      hintEn: "Auf verschneiten Bergen hinuntergleiten",
      hintFr: "Glisser sur des montagnes enneigées",
    },
    {
      english: "das Tanzen",
      french: "Danse",
      hintEn: "Den Körper zur Musik bewegen",
      hintFr: "Bouger son corps sur de la musique",
    },
    {
      english: "das Boxen",
      french: "Boxe",
      hintEn: "Ein Kampfsport mit Handschuhen",
      hintFr: "Un sport de combat avec des gants",
    },
    {
      english: "das Turnen",
      french: "Gymnastique",
      hintEn: "Ein Sport mit Saltos und Gleichgewicht",
      hintFr: "Un sport avec des sauts et de l'équilibre",
    },
    {
      english: "das Rugby",
      french: "Rugby",
      hintEn: "Ein Mannschaftssport mit einem ovalen Ball",
      hintFr: "Un sport d'équipe avec un ballon ovale",
    },
    {
      english: "der Volleyball",
      french: "Volley",
      hintEn: "Ein Mannschaftssport, bei dem man einen Ball über ein Netz schlägt",
      hintFr: "Un sport d'équipe où on frappe un ballon par-dessus un filet",
    },
  ],
  "Les métiers": [
    {
      english: "der Arzt",
      french: "Médecin",
      hintEn: "Eine Person, die kranke Menschen behandelt",
      hintFr: "Une personne qui soigne les malades",
    },
    {
      english: "der Feuerwehrmann",
      french: "Pompier",
      hintEn: "Eine Person, die Brände löscht",
      hintFr: "Une personne qui éteint les incendies",
    },
    {
      english: "der Polizist",
      french: "Policier",
      hintEn: "Eine Person, die das Gesetz durchsetzt",
      hintFr: "Une personne qui fait respecter la loi",
    },
    {
      english: "der Bäcker",
      french: "Boulanger",
      hintEn: "Eine Person, die Brot backt",
      hintFr: "Une personne qui fait du pain",
    },
    {
      english: "der Bauer",
      french: "Fermier",
      hintEn: "Eine Person, die Nahrung anbaut",
      hintFr: "Une personne qui cultive la nourriture",
    },
    {
      english: "der Pilot",
      french: "Pilote",
      hintEn: "Eine Person, die Flugzeuge fliegt",
      hintFr: "Une personne qui pilote les avions",
    },
    {
      english: "der Krankenpfleger",
      french: "Infirmier",
      hintEn: "Eine Person, die dem Arzt hilft",
      hintFr: "Une personne qui aide le médecin",
    },
    {
      english: "der Friseur",
      french: "Coiffeur",
      hintEn: "Eine Person, die Haare schneidet",
      hintFr: "Une personne qui coupe les cheveux",
    },
    {
      english: "der Kellner",
      french: "Serveur",
      hintEn: "Eine Person, die im Restaurant serviert",
      hintFr: "Une personne qui sert dans un restaurant",
    },
    {
      english: "der Zahnarzt",
      french: "Dentiste",
      hintEn: "Eine Person, die sich um Zähne kümmert",
      hintFr: "Une personne qui soigne les dents",
    },
    {
      english: "der Anwalt",
      french: "Avocat",
      hintEn: "Eine Person, die Menschen vor Gericht verteidigt",
      hintFr: "Une personne qui défend les gens au tribunal",
    },
    {
      english: "der Mechaniker",
      french: "Mécanicien",
      hintEn: "Eine Person, die Autos repariert",
      hintFr: "Une personne qui répare les voitures",
    },
  ],
  "Les transports": [
    {
      english: "das Auto",
      french: "Voiture",
      hintEn: "Ein Fahrzeug mit vier Rädern",
      hintFr: "Un véhicule à quatre roues",
    },
    {
      english: "der Bus",
      french: "Bus",
      hintEn: "Ein großes Fahrzeug für viele Fahrgäste",
      hintFr: "Un grand véhicule pour beaucoup de passagers",
    },
    {
      english: "der Zug",
      french: "Train",
      hintEn: "Er fährt auf Schienen",
      hintFr: "Il roule sur des rails",
    },
    {
      english: "das Fahrrad",
      french: "Vélo",
      hintEn: "Ein Fahrzeug mit zwei Rädern und Pedalen",
      hintFr: "Un véhicule à deux roues et des pédales",
    },
    {
      english: "das Flugzeug",
      french: "Avion",
      hintEn: "Es fliegt am Himmel",
      hintFr: "Il vole dans le ciel",
    },
    {
      english: "das Boot",
      french: "Bateau",
      hintEn: "Ein Fahrzeug, das sich auf dem Wasser bewegt",
      hintFr: "Un véhicule qui se déplace sur l'eau",
    },
    {
      english: "das Motorrad",
      french: "Moto",
      hintEn: "Ein schnelles Zweirad mit Motor",
      hintFr: "Un véhicule rapide à deux roues avec un moteur",
    },
    {
      english: "das Taxi",
      french: "Taxi",
      hintEn: "Ein Auto, das du zum Fahren bezahlst",
      hintFr: "Une voiture que tu payes pour te déplacer",
    },
    {
      english: "die U-Bahn",
      french: "Métro",
      hintEn: "Ein unterirdischer Zug in Städten",
      hintFr: "Un train souterrain dans les villes",
    },
    {
      english: "der Hubschrauber",
      french: "Hélicoptère",
      hintEn: "Er fliegt mit drehenden Rotorblättern oben",
      hintFr: "Il vole avec des pales qui tournent",
    },
    {
      english: "der Lastwagen",
      french: "Camion",
      hintEn: "Ein großes Fahrzeug zum Transport von Waren",
      hintFr: "Un gros véhicule pour transporter des marchandises",
    },
    {
      english: "der Roller",
      french: "Trottinette",
      hintEn: "Ein kleines Fahrzeug, auf dem du stehst und dich abstoßt",
      hintFr: "Un petit véhicule sur lequel tu te tiens debout",
    },
  ],
  "La ville": [
    {
      english: "die Straße",
      french: "Rue",
      hintEn: "Ein Weg in einer Stadt",
      hintFr: "Une route dans une ville",
    },
    {
      english: "das Gebäude",
      french: "Bâtiment",
      hintEn: "Ein Bauwerk mit Wänden und einem Dach",
      hintFr: "Une structure avec des murs et un toit",
    },
    {
      english: "der Park",
      french: "Parc",
      hintEn: "Eine grüne Fläche mit Bäumen und Bänken",
      hintFr: "Un espace vert avec des arbres et des bancs",
    },
    {
      english: "das Krankenhaus",
      french: "Hôpital",
      hintEn: "Ein Ort, wo kranke Menschen behandelt werden",
      hintFr: "Un endroit où les malades sont soignés",
    },
    {
      english: "die Bibliothek",
      french: "Bibliothèque",
      hintEn: "Ein Ort mit vielen Büchern zum Lesen",
      hintFr: "Un endroit avec beaucoup de livres à lire",
    },
    {
      english: "das Museum",
      french: "Musée",
      hintEn: "Ein Ort, um Kunst und Geschichte zu sehen",
      hintFr: "Un endroit pour voir de l'art et de l'histoire",
    },
    {
      english: "die Kirche",
      french: "Église",
      hintEn: "Ein religiöses Gebäude mit einem Glockenturm",
      hintFr: "Un bâtiment religieux avec un clocher",
    },
    {
      english: "die Brücke",
      french: "Pont",
      hintEn: "Ein Bauwerk, um einen Fluss zu überqueren",
      hintFr: "Une structure pour traverser une rivière",
    },
    {
      english: "der Brunnen",
      french: "Fontaine",
      hintEn: "Wasser schießt daraus auf einem Platz empor",
      hintFr: "L'eau jaillit sur une place",
    },
    {
      english: "der Markt",
      french: "Marché",
      hintEn: "Ein Ort, um draußen frische Lebensmittel zu kaufen",
      hintFr: "Un endroit pour acheter de la nourriture fraîche dehors",
    },
    {
      english: "der Bürgersteig",
      french: "Trottoir",
      hintEn: "Der Weg zum Gehen neben einer Straße",
      hintFr: "Le chemin pour marcher le long d'une route",
    },
    {
      english: "der Turm",
      french: "Tour",
      hintEn: "Ein hohes schmales Gebäude",
      hintFr: "Un bâtiment haut et étroit",
    },
  ],
  "Les émotions": [
    {
      english: "glücklich",
      french: "Content",
      hintEn: "Freude und Vergnügen empfinden",
      hintFr: "Ressentir de la joie et du plaisir",
    },
    {
      english: "traurig",
      french: "Triste",
      hintEn: "Sich unglücklich fühlen, weinen wollen",
      hintFr: "Se sentir malheureux, vouloir pleurer",
    },
    {
      english: "wütend",
      french: "En colère",
      hintEn: "Sich über etwas ärgern",
      hintFr: "Se sentir furieux à propos de quelque chose",
    },
    {
      english: "ängstlich",
      french: "Effrayé",
      hintEn: "Vor etwas Angst haben",
      hintFr: "Avoir peur de quelque chose",
    },
    {
      english: "überrascht",
      french: "Surpris",
      hintEn: "Nicht erwarten, was passiert ist",
      hintFr: "Ne pas s'attendre à ce qui s'est passé",
    },
    {
      english: "müde",
      french: "Fatigué",
      hintEn: "Schlaf oder Ruhe brauchen",
      hintFr: "Avoir besoin de dormir ou se reposer",
    },
    {
      english: "gelangweilt",
      french: "Ennuyé",
      hintEn: "Nicht interessiert, nichts Lustiges zu tun",
      hintFr: "Pas intéressé, rien d'amusant à faire",
    },
    {
      english: "aufgeregt",
      french: "Excité",
      hintEn: "Sehr froh über etwas, das kommt",
      hintFr: "Très content à propos de quelque chose qui arrive",
    },
    {
      english: "stolz",
      french: "Fier",
      hintEn: "Froh über das, was du erreicht hast",
      hintFr: "Content de ce que tu as accompli",
    },
    {
      english: "schüchtern",
      french: "Timide",
      hintEn: "Nervös in Gegenwart anderer Menschen",
      hintFr: "Nerveux en présence d'autres personnes",
    },
    {
      english: "eifersüchtig",
      french: "Jaloux",
      hintEn: "Das wollen, was jemand anderes hat",
      hintFr: "Vouloir ce que quelqu'un d'autre a",
    },
    {
      english: "einsam",
      french: "Seul",
      hintEn: "Sich traurig fühlen, weil man allein ist",
      hintFr: "Se sentir triste parce qu'on est seul",
    },
  ],
  "La météo": [
    {
      english: "sonnig",
      french: "Ensoleillé",
      hintEn: "Wenn die Sonne hell scheint",
      hintFr: "Quand le soleil brille fort",
    },
    {
      english: "regnerisch",
      french: "Pluvieux",
      hintEn: "Wenn Wasser aus Wolken fällt",
      hintFr: "Quand l'eau tombe des nuages",
    },
    {
      english: "bewölkt",
      french: "Nuageux",
      hintEn: "Wenn der Himmel mit Wolken bedeckt ist",
      hintFr: "Quand le ciel est couvert de nuages",
    },
    {
      english: "windig",
      french: "Venteux",
      hintEn: "Wenn sich die Luft viel bewegt",
      hintFr: "Quand l'air bouge beaucoup",
    },
    {
      english: "stürmisch",
      french: "Orageux",
      hintEn: "Mit Donner und Blitz",
      hintFr: "Avec du tonnerre et des éclairs",
    },
    {
      english: "neblig",
      french: "Brumeux",
      hintEn: "Wenn man wegen Nebel nicht weit sehen kann",
      hintFr: "Quand on ne voit pas loin à cause de la brume",
    },
    {
      english: "heiß",
      french: "Chaud",
      hintEn: "Hohe Temperatur, du schwitzt",
      hintFr: "Température élevée, tu transpires",
    },
    {
      english: "kalt",
      french: "Froid",
      hintEn: "Niedrige Temperatur, du zitterst",
      hintFr: "Température basse, tu frissonnes",
    },
    {
      english: "der Donner",
      french: "Tonnerre",
      hintEn: "Ein lauter Knall während eines Gewitters",
      hintFr: "Un grand bruit pendant un orage",
    },
    {
      english: "der Blitz",
      french: "Éclair",
      hintEn: "Ein Lichtblitz am Himmel während eines Gewitters",
      hintFr: "Un flash de lumière dans le ciel pendant un orage",
    },
    {
      english: "der Regenbogen",
      french: "Arc-en-ciel",
      hintEn: "Bunter Bogen am Himmel nach dem Regen",
      hintFr: "Arc coloré dans le ciel après la pluie",
    },
    {
      english: "der Frost",
      french: "Gel",
      hintEn: "Eiskristalle auf dem Boden am Morgen",
      hintFr: "Cristaux de glace au sol le matin",
    },
  ],
  "La musique": [
    {
      english: "die Gitarre",
      french: "Guitare",
      hintEn: "Ein Saiteninstrument, das man zupft",
      hintFr: "Un instrument à cordes que l'on gratte",
    },
    {
      english: "das Klavier",
      french: "Piano",
      hintEn: "Ein großes Instrument mit schwarzen und weißen Tasten",
      hintFr: "Un grand instrument avec des touches noires et blanches",
    },
    {
      english: "das Schlagzeug",
      french: "Batterie",
      hintEn: "Man schlägt sie mit Stöcken, um Rhythmus zu machen",
      hintFr: "On les frappe avec des baguettes pour faire du rythme",
    },
    {
      english: "die Geige",
      french: "Violon",
      hintEn: "Ein Saiteninstrument, das mit einem Bogen gespielt wird",
      hintFr: "Un instrument à cordes joué avec un archet",
    },
    {
      english: "die Flöte",
      french: "Flûte",
      hintEn: "Ein Blasinstrument, in das man seitlich bläst",
      hintFr: "Un instrument à vent dans lequel on souffle de côté",
    },
    {
      english: "die Trompete",
      french: "Trompette",
      hintEn: "Ein Blechblasinstrument mit drei Ventilen",
      hintFr: "Un instrument en cuivre avec trois boutons",
    },
    {
      english: "der Sänger",
      french: "Chanteur",
      hintEn: "Eine Person, die singt",
      hintFr: "Une personne qui chante",
    },
    {
      english: "das Lied",
      french: "Chanson",
      hintEn: "Ein Musikstück mit Text",
      hintFr: "Un morceau de musique avec des paroles",
    },
    {
      english: "das Konzert",
      french: "Concert",
      hintEn: "Eine Live-Musikaufführung",
      hintFr: "Un spectacle de musique en direct",
    },
    {
      english: "die Melodie",
      french: "Mélodie",
      hintEn: "Eine Folge von Musiknoten",
      hintFr: "Une suite de notes musicales",
    },
    {
      english: "der Rhythmus",
      french: "Rythme",
      hintEn: "Das Taktmuster der Musik",
      hintFr: "Le motif de battement de la musique",
    },
    {
      english: "das Mikrofon",
      french: "Microphone",
      hintEn: "Ein Gerät, um deine Stimme lauter zu machen",
      hintFr: "Un appareil pour rendre ta voix plus forte",
    },
  ],
  "Les insectes": [
    {
      english: "der Schmetterling",
      french: "Papillon",
      hintEn: "Ein buntes Insekt mit großen Flügeln",
      hintFr: "Un insecte coloré avec de grandes ailes",
    },
    {
      english: "die Biene",
      french: "Abeille",
      hintEn: "Sie macht Honig und kann stechen",
      hintFr: "Elle fait du miel et peut piquer",
    },
    {
      english: "die Ameise",
      french: "Fourmi",
      hintEn: "Ein winziges Insekt, das in Kolonien lebt",
      hintFr: "Un minuscule insecte qui vit en colonies",
    },
    {
      english: "die Spinne",
      french: "Araignée",
      hintEn: "Sie hat acht Beine und baut Netze",
      hintFr: "Elle a huit pattes et fait des toiles",
    },
    {
      english: "die Fliege",
      french: "Mouche",
      hintEn: "Ein summendes Insekt, das sich auf Essen setzt",
      hintFr: "Un insecte bourdonnant qui se pose sur la nourriture",
    },
    {
      english: "die Mücke",
      french: "Moustique",
      hintEn: "Sie sticht dich und es juckt",
      hintFr: "Il te pique et te fait gratter",
    },
    {
      english: "der Marienkäfer",
      french: "Coccinelle",
      hintEn: "Ein kleines rotes Insekt mit schwarzen Punkten",
      hintFr: "Un petit insecte rouge avec des points noirs",
    },
    {
      english: "die Libelle",
      french: "Libellule",
      hintEn: "Ein langes Insekt mit durchsichtigen Flügeln in der Nähe von Wasser",
      hintFr: "Un long insecte aux ailes transparentes près de l'eau",
    },
    {
      english: "der Käfer",
      french: "Scarabée",
      hintEn: "Ein Insekt mit einem harten Panzer",
      hintFr: "Un insecte avec une carapace dure",
    },
    {
      english: "die Raupe",
      french: "Chenille",
      hintEn: "Eine Larve, die zum Schmetterling wird",
      hintFr: "Une larve qui devient un papillon",
    },
    {
      english: "die Heuschrecke",
      french: "Sauterelle",
      hintEn: "Ein grünes Insekt, das weit springt",
      hintFr: "Un insecte vert qui saute loin",
    },
    {
      english: "die Schnecke",
      french: "Escargot",
      hintEn: "Ein langsames Tier mit einem Haus auf dem Rücken",
      hintFr: "Une créature lente avec une coquille sur le dos",
    },
  ],
  "Les boissons": [
    {
      english: "der Kaffee",
      french: "Café",
      hintEn: "Ein heißes braunes Getränk, das dich wach macht",
      hintFr: "Une boisson chaude marron qui te réveille",
    },
    {
      english: "der Tee",
      french: "Thé",
      hintEn: "Ein heißes Getränk aus Blättern",
      hintFr: "Une boisson chaude faite avec des feuilles",
    },
    {
      english: "der Saft",
      french: "Jus",
      hintEn: "Ein Getränk aus gepressten Früchten",
      hintFr: "Une boisson faite de fruits pressés",
    },
    {
      english: "die Limonade",
      french: "Limonade",
      hintEn: "Ein süßes Getränk aus Zitronen",
      hintFr: "Une boisson sucrée faite de citrons",
    },
    {
      english: "die heiße Schokolade",
      french: "Chocolat chaud",
      hintEn: "Ein warmes süßes Getränk aus Kakao",
      hintFr: "Une boisson chaude sucrée faite de cacao",
    },
    {
      english: "der Smoothie",
      french: "Smoothie",
      hintEn: "Ein dickes Getränk aus gemischten Früchten",
      hintFr: "Une boisson épaisse de fruits mixés",
    },
    {
      english: "der Milchshake",
      french: "Milkshake",
      hintEn: "Ein kaltes Getränk aus Milch und Eis",
      hintFr: "Une boisson froide de lait et glace",
    },
    {
      english: "das Sprudelwasser",
      french: "Eau gazeuse",
      hintEn: "Wasser mit Bläschen",
      hintFr: "De l'eau avec des bulles",
    },
    {
      english: "die Brause",
      french: "Soda",
      hintEn: "Ein süßes sprudelndes Getränk",
      hintFr: "Une boisson sucrée gazeuse",
    },
    {
      english: "der Sirup",
      french: "Sirop",
      hintEn: "Eine süße dicke Flüssigkeit, die man mit Wasser mischt",
      hintFr: "Un liquide sucré et épais qu'on mélange avec de l'eau",
    },
    {
      english: "der Strohhalm",
      french: "Paille",
      hintEn: "Ein Röhrchen, mit dem du dein Getränk schlürfst",
      hintFr: "Un tube pour siroter ta boisson",
    },
    {
      english: "der Eiswürfel",
      french: "Glaçon",
      hintEn: "Ein kleiner Block aus gefrorenem Wasser",
      hintFr: "Un petit bloc d'eau gelée",
    },
  ],
  "Les desserts": [
    {
      english: "das Eis",
      french: "Glace",
      hintEn: "Eine kalte süße Leckerei, oft in einer Waffel",
      hintFr: "Une gourmandise froide, souvent dans un cornet",
    },
    {
      english: "die Schokolade",
      french: "Chocolat",
      hintEn: "Eine süße braune Leckerei aus Kakao",
      hintFr: "Un aliment sucré marron fait de cacao",
    },
    {
      english: "der Keks",
      french: "Biscuit",
      hintEn: "Ein kleiner flacher süßer Gebäcksnack",
      hintFr: "Un petit gâteau plat et sucré",
    },
    {
      english: "die Torte",
      french: "Tarte",
      hintEn: "Ein gebackenes Gericht mit Teig und Füllung",
      hintFr: "Un plat cuit avec une croûte et une garniture",
    },
    {
      english: "der Donut",
      french: "Beignet",
      hintEn: "Ein runder frittierter Kuchen mit einem Loch",
      hintFr: "Un gâteau frit rond avec un trou",
    },
    {
      english: "das Bonbon",
      french: "Bonbon",
      hintEn: "Eine kleine süße Leckerei",
      hintFr: "Une petite friandise sucrée",
    },
    {
      english: "die Waffel",
      french: "Gaufre",
      hintEn: "Ein knuspriger Kuchen mit Gittermuster",
      hintFr: "Un gâteau croustillant avec un motif en grille",
    },
    {
      english: "der Pfannkuchen",
      french: "Crêpe",
      hintEn: "Ein dünner flacher Kuchen, in der Pfanne gebacken",
      hintFr: "Un gâteau fin et plat cuit à la poêle",
    },
    {
      english: "der Muffin",
      french: "Muffin",
      hintEn: "Ein kleiner runder süßer Kuchen",
      hintFr: "Un petit gâteau rond et sucré",
    },
    {
      english: "das Croissant",
      french: "Croissant",
      hintEn: "Ein blättriges Gebäck in Halbmondform",
      hintFr: "Une viennoiserie feuilletée en forme de lune",
    },
    {
      english: "der Pudding",
      french: "Pudding",
      hintEn: "Ein weiches cremiges Dessert",
      hintFr: "Un dessert mou et crémeux",
    },
    {
      english: "der Brownie",
      french: "Brownie",
      hintEn: "Ein saftiger Schokoladenkuchen im Quadrat",
      hintFr: "Un gâteau carré au chocolat fondant",
    },
  ],
  "Les ustensiles": [
    {
      english: "die Gabel",
      french: "Fourchette",
      hintEn: "Du benutzt sie, um Essen aufzuspießen, sie hat Zinken",
      hintFr: "Tu l'utilises pour piquer la nourriture, avec des dents",
    },
    {
      english: "das Messer",
      french: "Couteau",
      hintEn: "Ein Werkzeug mit einer scharfen Klinge zum Schneiden",
      hintFr: "Un outil avec une lame tranchante pour couper",
    },
    {
      english: "der Löffel",
      french: "Cuillère",
      hintEn: "Du benutzt ihn, um Suppe zu essen",
      hintFr: "Tu l'utilises pour manger de la soupe",
    },
    {
      english: "der Teller",
      french: "Assiette",
      hintEn: "Ein flaches Geschirr, auf das man Essen legt",
      hintFr: "Un plat à surface plane pour poser la nourriture",
    },
    {
      english: "das Glas",
      french: "Verre",
      hintEn: "Ein Behälter zum Trinken",
      hintFr: "Un récipient pour boire",
    },
    {
      english: "die Schüssel",
      french: "Bol",
      hintEn: "Ein rundes tiefes Geschirr für Suppe oder Müsli",
      hintFr: "Un plat rond et profond pour la soupe ou les céréales",
    },
    {
      english: "die Pfanne",
      french: "Poêle",
      hintEn: "Ein flaches Metallgeschirr zum Kochen auf dem Herd",
      hintFr: "Un plat plat en métal pour cuisiner sur le feu",
    },
    {
      english: "der Topf",
      french: "Casserole",
      hintEn: "Ein tiefer Behälter zum Wasserkochen",
      hintFr: "Un récipient profond pour faire bouillir de l'eau",
    },
    {
      english: "der Ofen",
      french: "Four",
      hintEn: "Ein Kasten, der Essen von innen erhitzt",
      hintFr: "Une boîte qui chauffe la nourriture à l'intérieur",
    },
    {
      english: "der Kühlschrank",
      french: "Réfrigérateur",
      hintEn: "Eine kalte Maschine, um Essen frisch zu halten",
      hintFr: "Une machine froide pour garder la nourriture fraîche",
    },
    {
      english: "die Tasse",
      french: "Tasse",
      hintEn: "Ein kleiner Behälter für heiße Getränke",
      hintFr: "Un petit récipient pour les boissons chaudes",
    },
    {
      english: "die Serviette",
      french: "Serviette",
      hintEn: "Ein Stück Stoff oder Papier, um sich den Mund abzuwischen",
      hintFr: "Un morceau de tissu ou papier pour s'essuyer la bouche",
    },
  ],
  "Les meubles": [
    {
      english: "das Sofa",
      french: "Canapé",
      hintEn: "Ein langer bequemer Sitz für mehrere Personen",
      hintFr: "Un long siège confortable pour plusieurs personnes",
    },
    {
      english: "der Kleiderschrank",
      french: "Armoire",
      hintEn: "Ein hoher Schrank für Kleidung",
      hintFr: "Un grand meuble pour les vêtements",
    },
    {
      english: "das Regal",
      french: "Étagère",
      hintEn: "Ein flaches Brett, um Dinge darauf zu stellen",
      hintFr: "Une planche pour poser des choses",
    },
    {
      english: "die Lampe",
      french: "Lampe",
      hintEn: "Ein Gegenstand, der Licht gibt",
      hintFr: "Un objet qui donne de la lumière",
    },
    {
      english: "der Spiegel",
      french: "Miroir",
      hintEn: "Du siehst dein Spiegelbild darin",
      hintFr: "Tu vois ton reflet dedans",
    },
    {
      english: "der Teppich",
      french: "Tapis",
      hintEn: "Ein weicher Belag auf dem Boden",
      hintFr: "Un revêtement doux sur le sol",
    },
    {
      english: "der Vorhang",
      french: "Rideau",
      hintEn: "Stoff, der vor einem Fenster hängt",
      hintFr: "Du tissu suspendu devant une fenêtre",
    },
    {
      english: "die Schublade",
      french: "Tiroir",
      hintEn: "Eine Box, die du aus einem Schreibtisch oder Tisch ziehst",
      hintFr: "Une boîte que tu tires d'un bureau ou d'une table",
    },
    {
      english: "der Sessel",
      french: "Fauteuil",
      hintEn: "Ein bequemer Stuhl mit Armlehnen",
      hintFr: "Une chaise confortable avec des accoudoirs",
    },
    {
      english: "die Uhr",
      french: "Horloge",
      hintEn: "Ein Gegenstand, der die Zeit an einer Wand anzeigt",
      hintFr: "Un objet qui montre l'heure sur un mur",
    },
    {
      english: "das Kissen",
      french: "Coussin",
      hintEn: "Ein weiches Polster, das du auf ein Sofa legst",
      hintFr: "Un coussin doux que tu poses sur un canapé",
    },
    {
      english: "die Vase",
      french: "Vase",
      hintEn: "Ein Behälter für Blumen",
      hintFr: "Un récipient pour les fleurs",
    },
  ],
  "L'espace": [
    {
      english: "der Planet",
      french: "Planète",
      hintEn: "Ein großes Objekt, das um einen Stern kreist",
      hintFr: "Un gros objet en orbite autour d'une étoile",
    },
    {
      english: "die Rakete",
      french: "Fusée",
      hintEn: "Ein Fahrzeug, das ins All fliegt",
      hintFr: "Un véhicule qui va dans l'espace",
    },
    {
      english: "der Astronaut",
      french: "Astronaute",
      hintEn: "Eine Person, die ins All reist",
      hintFr: "Une personne qui voyage dans l'espace",
    },
    {
      english: "der Satellit",
      french: "Satellite",
      hintEn: "Ein Objekt, das um einen Planeten kreist",
      hintFr: "Un objet en orbite autour d'une planète",
    },
    {
      english: "die Galaxie",
      french: "Galaxie",
      hintEn: "Eine riesige Gruppe von Sternen im Weltraum",
      hintFr: "Un immense groupe d'étoiles dans l'espace",
    },
    {
      english: "der Komet",
      french: "Comète",
      hintEn: "Ein Ball aus Eis und Staub mit einem leuchtenden Schweif",
      hintFr: "Une boule de glace et poussière avec une queue brillante",
    },
    {
      english: "das Teleskop",
      french: "Télescope",
      hintEn: "Ein Werkzeug, um weit entfernte Objekte am Himmel zu sehen",
      hintFr: "Un outil pour voir des objets lointains dans le ciel",
    },
    {
      english: "die Schwerkraft",
      french: "Gravité",
      hintEn: "Die Kraft, die Dinge nach unten zieht",
      hintFr: "La force qui attire les choses vers le bas",
    },
    {
      english: "das Raumschiff",
      french: "Vaisseau spatial",
      hintEn: "Ein Fahrzeug für Reisen durch den Weltraum",
      hintFr: "Un véhicule pour voyager dans l'espace",
    },
    {
      english: "das Universum",
      french: "Univers",
      hintEn: "Alles, was im Weltraum existiert",
      hintFr: "Tout ce qui existe dans l'espace",
    },
    {
      english: "die Umlaufbahn",
      french: "Orbite",
      hintEn: "Der Weg eines Planeten um einen Stern",
      hintFr: "Le chemin d'une planète autour d'une étoile",
    },
    {
      english: "der Außerirdische",
      french: "Extraterrestre",
      hintEn: "Ein Wesen von einem anderen Planeten",
      hintFr: "Un être venu d'une autre planète",
    },
  ],
  "Les animaux marins": [
    {
      english: "der Wal",
      french: "Baleine",
      hintEn: "Das größte Tier im Ozean",
      hintFr: "Le plus grand animal de l'océan",
    },
    {
      english: "der Delfin",
      french: "Dauphin",
      hintEn: "Ein intelligentes Meerestier, das springt",
      hintFr: "Un animal marin intelligent qui saute",
    },
    {
      english: "der Hai",
      french: "Requin",
      hintEn: "Ein großer Fisch mit scharfen Zähnen",
      hintFr: "Un gros poisson avec des dents pointues",
    },
    {
      english: "der Oktopus",
      french: "Pieuvre",
      hintEn: "Ein Meerestier mit acht Armen",
      hintFr: "Une créature marine avec huit bras",
    },
    {
      english: "die Qualle",
      french: "Méduse",
      hintEn: "Ein durchsichtiges Meerestier, das sticht",
      hintFr: "Une créature marine transparente qui pique",
    },
    {
      english: "die Krabbe",
      french: "Crabe",
      hintEn: "Ein Meerestier mit Scheren, das seitwärts geht",
      hintFr: "Une créature marine avec des pinces qui marche de côté",
    },
    {
      english: "die Schildkröte",
      french: "Tortue",
      hintEn: "Ein langsames Tier mit einem Panzer",
      hintFr: "Un animal lent avec une carapace",
    },
    {
      english: "das Seepferdchen",
      french: "Hippocampe",
      hintEn: "Ein kleiner Fisch in der Form eines Pferdes",
      hintFr: "Un petit poisson en forme de cheval",
    },
    {
      english: "der Seestern",
      french: "Étoile de mer",
      hintEn: "Ein sternförmiges Meerestier",
      hintFr: "Une créature marine en forme d'étoile",
    },
    {
      english: "der Hummer",
      french: "Homard",
      hintEn: "Ein großes Meerestier mit großen Scheren",
      hintFr: "Une grande créature marine avec de grosses pinces",
    },
    {
      english: "die Robbe",
      french: "Phoque",
      hintEn: "Ein Meeressäugetier mit Flossen",
      hintFr: "Un mammifère marin avec des nageoires",
    },
    {
      english: "die Koralle",
      french: "Corail",
      hintEn: "Bunte Strukturen auf dem Meeresboden",
      hintFr: "Des structures colorées au fond de l'océan",
    },
  ],
  "Les oiseaux": [
    {
      english: "der Adler",
      french: "Aigle",
      hintEn: "Ein großer Raubvogel mit scharfem Blick",
      hintFr: "Un grand oiseau de proie à la vue perçante",
    },
    {
      english: "der Papagei",
      french: "Perroquet",
      hintEn: "Ein bunter Vogel, der sprechen kann",
      hintFr: "Un oiseau coloré qui peut parler",
    },
    {
      english: "die Eule",
      french: "Hibou",
      hintEn: "Ein Vogel, der nachts jagt",
      hintFr: "Un oiseau qui chasse la nuit",
    },
    {
      english: "der Schwan",
      french: "Cygne",
      hintEn: "Ein großer weißer Vogel mit langem Hals",
      hintFr: "Un grand oiseau blanc avec un long cou",
    },
    {
      english: "der Pinguin",
      french: "Pingouin",
      hintEn: "Ein schwarz-weißer Vogel, der nicht fliegen kann",
      hintFr: "Un oiseau noir et blanc qui ne peut pas voler",
    },
    {
      english: "der Pfau",
      french: "Paon",
      hintEn: "Ein Vogel mit wunderschönen bunten Schwanzfedern",
      hintFr: "Un oiseau avec de belles plumes colorées",
    },
    {
      english: "der Spatz",
      french: "Moineau",
      hintEn: "Ein kleiner häufiger brauner Vogel",
      hintFr: "Un petit oiseau brun commun",
    },
    {
      english: "die Krähe",
      french: "Corbeau",
      hintEn: "Ein großer schwarzer Vogel, der sehr klug ist",
      hintFr: "Un grand oiseau noir très intelligent",
    },
    {
      english: "der Flamingo",
      french: "Flamant rose",
      hintEn: "Ein großer rosa Vogel mit langen Beinen",
      hintFr: "Un grand oiseau rose avec de longues pattes",
    },
    {
      english: "die Taube",
      french: "Pigeon",
      hintEn: "Ein grauer Vogel, der in Städten verbreitet ist",
      hintFr: "Un oiseau gris commun dans les villes",
    },
    {
      english: "der Storch",
      french: "Cigogne",
      hintEn: "Ein großer weißer Vogel mit einem langen Schnabel",
      hintFr: "Un grand oiseau blanc avec un long bec",
    },
    {
      english: "das Rotkehlchen",
      french: "Rouge-gorge",
      hintEn: "Ein kleiner Vogel mit roter Brust",
      hintFr: "Un petit oiseau avec la poitrine rouge",
    },
  ],
  "La plage": [
    {
      english: "der Sand",
      french: "Sable",
      hintEn: "Winzige Körner, die den Strand bedecken",
      hintFr: "De petits grains qui couvrent la plage",
    },
    {
      english: "die Welle",
      french: "Vague",
      hintEn: "Bewegtes Wasser, das am Ufer bricht",
      hintFr: "De l'eau qui bouge et s'écrase sur le rivage",
    },
    {
      english: "die Sonnencreme",
      french: "Crème solaire",
      hintEn: "Eine Creme, um die Haut vor der Sonne zu schützen",
      hintFr: "Une crème pour protéger la peau du soleil",
    },
    {
      english: "der Sonnenschirm",
      french: "Parasol",
      hintEn: "Gibt Schatten vor der Sonne am Strand",
      hintFr: "Donne de l'ombre sur la plage",
    },
    {
      english: "der Badeanzug",
      french: "Maillot de bain",
      hintEn: "Kleidung zum Schwimmen",
      hintFr: "Vêtement pour nager",
    },
    {
      english: "das Handtuch",
      french: "Serviette",
      hintEn: "Ein Tuch zum Abtrocknen",
      hintFr: "Un tissu pour se sécher",
    },
    {
      english: "die Muschel",
      french: "Coquillage",
      hintEn: "Eine harte Hülle von einem Meerestier",
      hintFr: "Une couverture dure d'une créature marine",
    },
    {
      english: "das Surfbrett",
      french: "Planche de surf",
      hintEn: "Ein Brett, um auf Wellen zu reiten",
      hintFr: "Une planche pour glisser sur les vagues",
    },
    {
      english: "die Sandburg",
      french: "Château de sable",
      hintEn: "Eine Burg aus nassem Sand",
      hintFr: "Un château fait de sable mouillé",
    },
    {
      english: "die Möwe",
      french: "Mouette",
      hintEn: "Ein weißer Vogel am Strand",
      hintFr: "Un oiseau blanc à la plage",
    },
    {
      english: "der Sonnenuntergang",
      french: "Coucher de soleil",
      hintEn: "Wenn die Sonne am Abend untergeht",
      hintFr: "Quand le soleil descend le soir",
    },
    {
      english: "der Rettungsschwimmer",
      french: "Maître-nageur",
      hintEn: "Eine Person, die über die Schwimmer wacht",
      hintFr: "Une personne qui surveille les nageurs",
    },
  ],
  "Les jouets": [
    {
      english: "die Puppe",
      french: "Poupée",
      hintEn: "Ein Spielzeug, das wie eine kleine Person aussieht",
      hintFr: "Un jouet qui ressemble à une petite personne",
    },
    {
      english: "das Puzzle",
      french: "Puzzle",
      hintEn: "Teile, die du zusammensetzt, um ein Bild zu machen",
      hintFr: "Des pièces à assembler pour faire une image",
    },
    {
      english: "der Ball",
      french: "Ballon",
      hintEn: "Ein runder Gegenstand, den du wirfst oder trittst",
      hintFr: "Un objet rond que tu lances ou que tu frappes",
    },
    {
      english: "der Teddybär",
      french: "Nounours",
      hintEn: "Ein weiches Kuscheltier in Bärenform",
      hintFr: "Un ours en peluche tout doux",
    },
    {
      english: "der Drachen",
      french: "Cerf-volant",
      hintEn: "Ein Spielzeug, das an einem Faden im Wind fliegt",
      hintFr: "Un jouet qui vole dans le vent au bout d'un fil",
    },
    {
      english: "der Roboter",
      french: "Robot",
      hintEn: "Ein mechanisches Spielzeug, das sich bewegt",
      hintFr: "Un jouet mécanique qui bouge",
    },
    {
      english: "die Bausteine",
      french: "Cubes",
      hintEn: "Du stapelst sie, um Dinge zu bauen",
      hintFr: "Tu les empiles pour construire des choses",
    },
    {
      english: "das Brettspiel",
      french: "Jeu de société",
      hintEn: "Ein Spiel, das auf einem Brett mit Figuren gespielt wird",
      hintFr: "Un jeu avec un plateau et des pions",
    },
    {
      english: "die Murmel",
      french: "Bille",
      hintEn: "Eine kleine Kugel aus Glas",
      hintFr: "Une petite boule en verre",
    },
    {
      english: "der Luftballon",
      french: "Ballon de baudruche",
      hintEn: "Ein Gummibeutel, den du mit Luft aufbläst",
      hintFr: "Un sac en caoutchouc que tu gonfles",
    },
    {
      english: "die Rutsche",
      french: "Toboggan",
      hintEn: "Du rutschst darauf auf dem Spielplatz hinunter",
      hintFr: "Tu descends dessus au parc",
    },
    {
      english: "die Schaukel",
      french: "Balançoire",
      hintEn: "Ein Sitz, der an Ketten hängt und hin und her schwingt",
      hintFr: "Un siège suspendu à des chaînes qui va et vient",
    },
  ],
  "Le restaurant": [
    {
      english: "die Speisekarte",
      french: "Menu",
      hintEn: "Eine Liste der Gerichte, die du bestellen kannst",
      hintFr: "Une liste de plats que tu peux commander",
    },
    {
      english: "die Rechnung",
      french: "Addition",
      hintEn: "Das Papier, das zeigt, was du bezahlen musst",
      hintFr: "Le papier qui montre ce que tu dois payer",
    },
    {
      english: "das Trinkgeld",
      french: "Pourboire",
      hintEn: "Zusätzliches Geld, das du dem Kellner gibst",
      hintFr: "De l'argent en plus que tu donnes au serveur",
    },
    {
      english: "die Reservierung",
      french: "Réservation",
      hintEn: "Einen Tisch im Voraus buchen",
      hintFr: "Réserver une table à l'avance",
    },
    {
      english: "die Vorspeise",
      french: "Entrée",
      hintEn: "Ein kleines Gericht vor dem Hauptgang",
      hintFr: "Un petit plat avant le plat principal",
    },
    {
      english: "das Hauptgericht",
      french: "Plat principal",
      hintEn: "Das größte Gericht einer Mahlzeit",
      hintFr: "Le plus grand plat d'un repas",
    },
    {
      english: "der Chefkoch",
      french: "Chef cuisinier",
      hintEn: "Die Person, die in der Küche kocht",
      hintFr: "La personne qui cuisine en cuisine",
    },
    {
      english: "die Bestellung",
      french: "Commande",
      hintEn: "Was du im Restaurant bestellst",
      hintFr: "Ce que tu demandes au restaurant",
    },
    {
      english: "das Rezept",
      french: "Recette",
      hintEn: "Anweisungen, um ein Gericht zu kochen",
      hintFr: "Les instructions pour préparer un plat",
    },
    {
      english: "das Gericht",
      french: "Plat",
      hintEn: "Eine bestimmte Art von servierten Speisen",
      hintFr: "Un type de nourriture servi",
    },
    {
      english: "die Tischdecke",
      french: "Nappe",
      hintEn: "Ein Tuch, das den Tisch bedeckt",
      hintFr: "Un tissu qui couvre la table",
    },
    {
      english: "die Kerze",
      french: "Bougie",
      hintEn: "Ein Wachsstab mit einer Flamme",
      hintFr: "Un bâton de cire avec une flamme",
    },
  ],
  "Le camping": [
    {
      english: "das Zelt",
      french: "Tente",
      hintEn: "Ein tragbarer Unterschlupf aus Stoff",
      hintFr: "Un abri portable en tissu",
    },
    {
      english: "der Schlafsack",
      french: "Sac de couchage",
      hintEn: "Ein warmer Sack zum Schlafen",
      hintFr: "Un sac chaud pour dormir",
    },
    {
      english: "das Lagerfeuer",
      french: "Feu de camp",
      hintEn: "Ein Feuer draußen zum Aufwärmen",
      hintFr: "Un feu fait dehors pour se réchauffer",
    },
    {
      english: "die Taschenlampe",
      french: "Lampe torche",
      hintEn: "Ein kleines tragbares Licht",
      hintFr: "Une petite lumière portable",
    },
    {
      english: "der Kompass",
      french: "Boussole",
      hintEn: "Ein Werkzeug, das den Norden anzeigt",
      hintFr: "Un outil qui montre le nord",
    },
    {
      english: "die Landkarte",
      french: "Carte",
      hintEn: "Eine Zeichnung eines Gebiets",
      hintFr: "Un dessin d'une zone",
    },
    {
      english: "der Rucksack",
      french: "Sac à dos",
      hintEn: "Eine Tasche, die du auf dem Rücken trägst",
      hintFr: "Un sac que tu portes sur le dos",
    },
    {
      english: "das Wandern",
      french: "Randonnée",
      hintEn: "Lange in der Natur spazieren gehen",
      hintFr: "Marcher longtemps dans la nature",
    },
    {
      english: "der Wanderweg",
      french: "Sentier",
      hintEn: "Ein Pfad durch den Wald",
      hintFr: "Un chemin à travers la forêt",
    },
    {
      english: "die Hütte",
      french: "Cabane",
      hintEn: "Ein kleines Holzhaus im Wald",
      hintFr: "Une petite maison en bois dans les bois",
    },
    {
      english: "das Fernglas",
      french: "Jumelles",
      hintEn: "Ein Werkzeug, um Dinge in der Ferne zu sehen",
      hintFr: "Un outil pour voir les choses au loin",
    },
    {
      english: "das Brennholz",
      french: "Bois de chauffage",
      hintEn: "Holz, das man benutzt, um ein Feuer zu machen",
      hintFr: "Du bois utilisé pour faire un feu",
    },
  ],
  "Les voyages": [
    {
      english: "der Koffer",
      french: "Valise",
      hintEn: "Eine große Tasche zum Reisen",
      hintFr: "Un grand sac pour voyager",
    },
    {
      english: "das Hotel",
      french: "Hôtel",
      hintEn: "Ein Ort zum Schlafen, wenn man reist",
      hintFr: "Un endroit pour dormir quand on voyage",
    },
    {
      english: "der Tourist",
      french: "Touriste",
      hintEn: "Eine Person, die einen Ort besucht",
      hintFr: "Une personne qui visite un endroit",
    },
    {
      english: "die Kamera",
      french: "Appareil photo",
      hintEn: "Ein Gerät, um Fotos zu machen",
      hintFr: "Un appareil pour prendre des photos",
    },
    {
      english: "das Souvenir",
      french: "Souvenir",
      hintEn: "Ein Gegenstand zur Erinnerung an eine Reise",
      hintFr: "Un objet pour se rappeler d'un voyage",
    },
    {
      english: "der Reisepass",
      french: "Passeport",
      hintEn: "Ein offizielles Dokument zum Reisen ins Ausland",
      hintFr: "Un document officiel pour voyager à l'étranger",
    },
    {
      english: "die Postkarte",
      french: "Carte postale",
      hintEn: "Eine Karte mit einem Bild, die du aus dem Urlaub schickst",
      hintFr: "Une carte avec une image que tu envoies en vacances",
    },
    {
      english: "das Gepäck",
      french: "Bagages",
      hintEn: "Alle Taschen, die du auf eine Reise mitnimmst",
      hintFr: "Tous les sacs que tu prends en voyage",
    },
    {
      english: "das Reiseziel",
      french: "Destination",
      hintEn: "Der Ort, an den du reist",
      hintFr: "L'endroit où tu vas",
    },
    {
      english: "der Urlaub",
      french: "Vacances",
      hintEn: "Freie Zeit ohne Schule oder Arbeit",
      hintFr: "Du temps libre sans école ni travail",
    },
    {
      english: "der Reiseführer",
      french: "Guide",
      hintEn: "Eine Person, die dir alles zeigt",
      hintFr: "Une personne qui te fait visiter",
    },
    {
      english: "das Abenteuer",
      french: "Aventure",
      hintEn: "Ein aufregendes und ungewöhnliches Erlebnis",
      hintFr: "Une expérience excitante et inhabituelle",
    },
  ],
  "La fête": [
    {
      english: "der Geburtstag",
      french: "Anniversaire",
      hintEn: "Der Tag, an dem du geboren wurdest, jedes Jahr gefeiert",
      hintFr: "Le jour de ta naissance, fêté chaque année",
    },
    {
      english: "das Geschenk",
      french: "Cadeau",
      hintEn: "Etwas, das du jemandem gibst",
      hintFr: "Quelque chose que tu donnes à quelqu'un",
    },
    {
      english: "die Einladung",
      french: "Invitation",
      hintEn: "Eine Karte, die jemanden bittet zu kommen",
      hintFr: "Une carte qui demande à quelqu'un de venir",
    },
    {
      english: "der Gast",
      french: "Invité",
      hintEn: "Eine Person, die zu deiner Feier kommt",
      hintFr: "Une personne qui vient à ta fête",
    },
    {
      english: "der Tanz",
      french: "Danse",
      hintEn: "Sich zur Musik auf einer Feier bewegen",
      hintFr: "Bouger sur la musique à une fête",
    },
    {
      english: "das Feuerwerk",
      french: "Feux d'artifice",
      hintEn: "Bunte Explosionen am Himmel",
      hintFr: "Des explosions colorées dans le ciel",
    },
    {
      english: "das Kostüm",
      french: "Déguisement",
      hintEn: "Besondere Kleidung, um wie jemand anderes auszusehen",
      hintFr: "Des vêtements spéciaux pour ressembler à quelqu'un d'autre",
    },
    {
      english: "das Konfetti",
      french: "Confettis",
      hintEn: "Kleine bunte Papierstücke, die in die Luft geworfen werden",
      hintFr: "Petits morceaux de papier coloré lancés en l'air",
    },
    {
      english: "die Überraschung",
      french: "Surprise",
      hintEn: "Etwas Unerwartetes und Schönes",
      hintFr: "Quelque chose d'inattendu et d'agréable",
    },
    {
      english: "die Feier",
      french: "Célébration",
      hintEn: "Ein fröhliches Ereignis mit Menschen zusammen",
      hintFr: "Un événement joyeux avec des gens réunis",
    },
    {
      english: "die Dekoration",
      french: "Décoration",
      hintEn: "Dinge, die du benutzt, um einen Ort hübsch zu machen",
      hintFr: "Des choses pour rendre un endroit joli",
    },
    {
      english: "das Geschenkpapier",
      french: "Papier cadeau",
      hintEn: "Papier zum Einpacken von Geschenken",
      hintFr: "Du papier pour emballer les cadeaux",
    },
  ],
  "L'informatique": [
    {
      english: "der Computer",
      french: "Ordinateur",
      hintEn: "Eine Maschine zum Arbeiten und Surfen",
      hintFr: "Une machine pour travailler et naviguer",
    },
    {
      english: "die Tastatur",
      french: "Clavier",
      hintEn: "Du tippst mit deinen Fingern darauf",
      hintFr: "Tu tapes dessus avec tes doigts",
    },
    {
      english: "der Bildschirm",
      french: "Écran",
      hintEn: "Der Teil, den du am Computer anschaust",
      hintFr: "La partie que tu regardes sur un ordinateur",
    },
    {
      english: "das Internet",
      french: "Internet",
      hintEn: "Ein weltweites Netzwerk, das Computer verbindet",
      hintFr: "Un réseau mondial reliant les ordinateurs",
    },
    {
      english: "die Webseite",
      french: "Site web",
      hintEn: "Eine Seite im Internet",
      hintFr: "Une page sur internet",
    },
    {
      english: "das Passwort",
      french: "Mot de passe",
      hintEn: "Ein geheimer Code, um auf dein Konto zuzugreifen",
      hintFr: "Un code secret pour accéder à ton compte",
    },
    {
      english: "die E-Mail",
      french: "E-mail",
      hintEn: "Eine elektronische Nachricht",
      hintFr: "Un message électronique",
    },
    {
      english: "die Datei",
      french: "Fichier",
      hintEn: "Ein Dokument, das auf einem Computer gespeichert ist",
      hintFr: "Un document enregistré sur un ordinateur",
    },
    {
      english: "der Drucker",
      french: "Imprimante",
      hintEn: "Eine Maschine, die Text auf Papier druckt",
      hintFr: "Une machine qui met du texte sur du papier",
    },
    {
      english: "der Download",
      french: "Téléchargement",
      hintEn: "Eine Datei aus dem Internet herunterladen",
      hintFr: "Récupérer un fichier depuis internet",
    },
    {
      english: "die App",
      french: "Application",
      hintEn: "Ein Programm auf deinem Handy oder Computer",
      hintFr: "Un programme sur ton téléphone ou ordinateur",
    },
    {
      english: "der Akku",
      french: "Batterie",
      hintEn: "Das gibt deinem Handy Energie",
      hintFr: "Ce qui donne de l'énergie à ton téléphone",
    },
  ],
  "Les formes": [
    {
      english: "der Kreis",
      french: "Cercle",
      hintEn: "Eine perfekt runde Form",
      hintFr: "Une forme parfaitement ronde",
    },
    {
      english: "das Quadrat",
      french: "Carré",
      hintEn: "Eine Form mit vier gleichen Seiten",
      hintFr: "Une forme avec quatre côtés égaux",
    },
    {
      english: "das Dreieck",
      french: "Triangle",
      hintEn: "Eine Form mit drei Seiten",
      hintFr: "Une forme avec trois côtés",
    },
    {
      english: "das Rechteck",
      french: "Rectangle",
      hintEn: "Eine Form mit vier Seiten, länger als breit",
      hintFr: "Une forme à quatre côtés, plus long que large",
    },
    {
      english: "der Stern",
      french: "Étoile",
      hintEn: "Eine Form mit Spitzen",
      hintFr: "Une forme avec des pointes",
    },
    {
      english: "die Raute",
      french: "Losange",
      hintEn: "Eine Form wie ein gekipptes Quadrat",
      hintFr: "Une forme comme un carré penché",
    },
    {
      english: "das Herz",
      french: "Cœur",
      hintEn: "Eine Form, die die Liebe darstellt",
      hintFr: "Une forme qui représente l'amour",
    },
    {
      english: "das Oval",
      french: "Ovale",
      hintEn: "Eine Form wie ein gestreckter Kreis",
      hintFr: "Une forme comme un cercle étiré",
    },
    {
      english: "der Würfel",
      french: "Cube",
      hintEn: "Eine 3D-Form wie eine Box mit gleichen Seiten",
      hintFr: "Une forme 3D comme une boîte à côtés égaux",
    },
    {
      english: "die Kugel",
      french: "Sphère",
      hintEn: "Eine 3D-Form wie ein Ball",
      hintFr: "Une forme 3D comme une balle",
    },
    {
      english: "die Pyramide",
      french: "Pyramide",
      hintEn: "Eine 3D-Form mit quadratischer Basis und dreieckigen Seiten",
      hintFr: "Une forme 3D avec une base carrée et des côtés triangulaires",
    },
    {
      english: "der Pfeil",
      french: "Flèche",
      hintEn: "Eine Form, die in eine Richtung zeigt",
      hintFr: "Une forme qui pointe dans une direction",
    },
  ],
};
