const themesZh = {
  "La maison": [
    {
      english: "桌子 (zhuōzi)",
      french: "Table",
      hintEn: "吃饭或工作时用的平面家具",
      hintFr: "Surface plate avec des pieds, pour manger ou travailler",
    },
    {
      english: "椅子 (yǐzi)",
      french: "Chaise",
      hintEn: "有靠背的座位，坐一个人",
      hintFr: "Un siège avec un dossier, pour une personne",
    },
    {
      english: "窗户 (chuānghù)",
      french: "Fenêtre",
      hintEn: "墙上有玻璃的开口，可以看外面",
      hintFr: "Une ouverture dans un mur avec du verre, pour voir dehors",
    },
    {
      english: "床 (chuáng)",
      french: "Lit",
      hintEn: "晚上睡觉的地方",
      hintFr: "Là où tu dors la nuit",
    },
    {
      english: "门 (mén)",
      french: "Porte",
      hintEn: "打开它可以进出房间",
      hintFr: "Tu l'ouvres pour entrer ou sortir d'une pièce",
    },
    {
      english: "厨房 (chúfáng)",
      french: "Cuisine",
      hintEn: "做饭的房间",
      hintFr: "La pièce où on prépare les repas",
    },
    {
      english: "浴室 (yùshì)",
      french: "Salle de bain",
      hintEn: "有淋浴或浴缸的房间",
      hintFr: "La pièce avec une douche ou une baignoire",
    },
    {
      english: "花园 (huāyuán)",
      french: "Jardin",
      hintEn: "有花和植物的户外空间",
      hintFr: "Un espace extérieur avec des plantes et des fleurs",
    },
    {
      english: "屋顶 (wūdǐng)",
      french: "Toit",
      hintEn: "房子最上面的部分，挡雨用的",
      hintFr: "La partie en haut de la maison qui protège de la pluie",
    },
    {
      english: "墙 (qiáng)",
      french: "Mur",
      hintEn: "隔开房间的竖直表面",
      hintFr: "Une surface verticale qui sépare les pièces",
    },
    {
      english: "地板 (dìbǎn)",
      french: "Sol",
      hintEn: "房间里你走路的那个面",
      hintFr: "La surface sur laquelle tu marches dans une pièce",
    },
    {
      english: "楼梯 (lóutī)",
      french: "Escalier",
      hintEn: "在楼层之间上下的台阶",
      hintFr: "Des marches pour monter ou descendre entre les étages",
    },
  ],
  "La nourriture": [
    {
      english: "苹果 (píngguǒ)",
      french: "Pomme",
      hintEn: "一种圆形水果，通常是红色或绿色的",
      hintFr: "Un fruit rond, souvent rouge ou vert",
    },
    {
      english: "面包 (miànbāo)",
      french: "Pain",
      hintEn: "用面粉做的，每天都吃",
      hintFr: "Fait avec de la farine, on en mange tous les jours",
    },
    {
      english: "奶酪 (nǎilào)",
      french: "Fromage",
      hintEn: "用牛奶做的，通常是黄色的",
      hintFr: "Fait avec du lait, souvent jaune",
    },
    {
      english: "蛋糕 (dàngāo)",
      french: "Gâteau",
      hintEn: "生日时吃的甜点",
      hintFr: "Un dessert sucré pour les anniversaires",
    },
    {
      english: "牛奶 (niúnǎi)",
      french: "Lait",
      hintEn: "从牛身上来的白色饮料",
      hintFr: "Une boisson blanche qui vient des vaches",
    },
    {
      english: "水 (shuǐ)",
      french: "Eau",
      hintEn: "每天都喝的透明液体",
      hintFr: "Un liquide transparent que tu bois chaque jour",
    },
    {
      english: "鸡肉 (jīròu)",
      french: "Poulet",
      hintEn: "一种鸟的肉，很常见",
      hintFr: "Un oiseau que l'on mange, une viande très courante",
    },
    {
      english: "米饭 (mǐfàn)",
      french: "Riz",
      hintEn: "白色的小颗粒，在亚洲吃很多",
      hintFr: "Petits grains blancs, très mangés en Asie",
    },
    {
      english: "沙拉 (shālā)",
      french: "Salade",
      hintEn: "用生菜和蔬菜做的菜",
      hintFr: "Un plat avec de la laitue et des légumes",
    },
    {
      english: "黄油 (huángyóu)",
      french: "Beurre",
      hintEn: "用奶油做的黄色涂抹物",
      hintFr: "Une pâte jaune faite à partir de crème",
    },
    {
      english: "鸡蛋 (jīdàn)",
      french: "Oeuf",
      hintEn: "从母鸡来的，有壳",
      hintFr: "Il vient de la poule, avec une coquille",
    },
    {
      english: "糖 (táng)",
      french: "Sucre",
      hintEn: "白色的甜粉末，加在茶或咖啡里",
      hintFr: "Une poudre blanche et sucrée pour le thé ou le café",
    },
  ],
  "Les animaux": [
    {
      english: "狗 (gǒu)",
      french: "Chien",
      hintEn: "会汪汪叫、摇尾巴的宠物",
      hintFr: "Un animal qui aboie et remue la queue",
    },
    {
      english: "猫 (māo)",
      french: "Chat",
      hintEn: "会呼噜呼噜叫、抓老鼠的宠物",
      hintFr: "Un animal qui ronronne et attrape les souris",
    },
    {
      english: "鸟 (niǎo)",
      french: "Oiseau",
      hintEn: "有翅膀会飞的动物",
      hintFr: "Un animal avec des ailes qui peut voler",
    },
    {
      english: "鱼 (yú)",
      french: "Poisson",
      hintEn: "生活在水里的动物",
      hintFr: "Un animal qui vit dans l'eau",
    },
    {
      english: "马 (mǎ)",
      french: "Cheval",
      hintEn: "可以骑的大动物",
      hintFr: "Un grand animal que l'on peut monter",
    },
    {
      english: "兔子 (tùzi)",
      french: "Lapin",
      hintEn: "长耳朵会跳的小动物",
      hintFr: "Un petit animal avec de longues oreilles qui saute",
    },
    {
      english: "老鼠 (lǎoshǔ)",
      french: "Souris",
      hintEn: "非常小的动物，喜欢吃奶酪",
      hintFr: "Un très petit animal qui aime le fromage",
    },
    {
      english: "牛 (niú)",
      french: "Vache",
      hintEn: "农场里产奶的大动物",
      hintFr: "Un grand animal de ferme qui donne du lait",
    },
    {
      english: "猪 (zhū)",
      french: "Cochon",
      hintEn: "粉色的农场动物，喜欢泥巴",
      hintFr: "Un animal de ferme rose qui aime la boue",
    },
    {
      english: "羊 (yáng)",
      french: "Mouton",
      hintEn: "农场里有白色羊毛的动物",
      hintFr: "Un animal de ferme avec de la laine blanche",
    },
    {
      english: "鸭子 (yāzi)",
      french: "Canard",
      hintEn: "会游泳、会嘎嘎叫的鸟",
      hintFr: "Un oiseau qui nage et fait 'coin coin'",
    },
    {
      english: "青蛙 (qīngwā)",
      french: "Grenouille",
      hintEn: "水边的绿色小动物，会跳",
      hintFr: "Un petit animal vert qui saute près de l'eau",
    },
  ],
  "La nature": [
    {
      english: "太阳 (tàiyáng)",
      french: "Soleil",
      hintEn: "白天天空中的大黄星",
      hintFr: "La grande étoile jaune dans le ciel pendant la journée",
    },
    {
      english: "月亮 (yuèliàng)",
      french: "Lune",
      hintEn: "晚上在天空中可以看到它",
      hintFr: "On la voit dans le ciel la nuit",
    },
    {
      english: "星星 (xīngxīng)",
      french: "Étoile",
      hintEn: "夜空中的小亮点",
      hintFr: "Un petit point brillant dans le ciel la nuit",
    },
    {
      english: "云 (yún)",
      french: "Nuage",
      hintEn: "天空中白色或灰色的形状",
      hintFr: "Une forme blanche ou grise dans le ciel",
    },
    {
      english: "雨 (yǔ)",
      french: "Pluie",
      hintEn: "从天空落下的水",
      hintFr: "De l'eau qui tombe du ciel",
    },
    {
      english: "树 (shù)",
      french: "Arbre",
      hintEn: "有树干和叶子的高大植物",
      hintFr: "Une grande plante avec un tronc et des feuilles",
    },
    {
      english: "花 (huā)",
      french: "Fleur",
      hintEn: "颜色漂亮、闻起来很香的植物",
      hintFr: "Une plante colorée qui sent bon",
    },
    {
      english: "河 (hé)",
      french: "Rivière",
      hintEn: "流过大地的长长的水流",
      hintFr: "Un long cours d'eau à travers la terre",
    },
    {
      english: "山 (shān)",
      french: "Montagne",
      hintEn: "非常高的地方，山顶有雪",
      hintFr: "Un terrain très élevé, avec de la neige au sommet",
    },
    {
      english: "海 (hǎi)",
      french: "Mer",
      hintEn: "大片的咸水",
      hintFr: "Une grande étendue d'eau salée",
    },
    {
      english: "雪 (xuě)",
      french: "Neige",
      hintEn: "白色的、冷的，冬天会落下来",
      hintFr: "Blanc et froid, ça tombe en hiver",
    },
    {
      english: "风 (fēng)",
      french: "Vent",
      hintEn: "能感觉到但看不到的移动空气",
      hintFr: "De l'air qui bouge, qu'on sent mais qu'on ne voit pas",
    },
  ],
  "L'école": [
    {
      english: "书 (shū)",
      french: "Livre",
      hintEn: "你阅读的东西，有很多页",
      hintFr: "Tu le lis, il a des pages",
    },
    {
      english: "学校 (xuéxiào)",
      french: "École",
      hintEn: "孩子们去学习的地方",
      hintFr: "Un endroit où les enfants vont pour apprendre",
    },
    {
      english: "钢笔 (gāngbǐ)",
      french: "Stylo",
      hintEn: "用墨水写字的工具",
      hintFr: "Tu écris avec, il utilise de l'encre",
    },
    {
      english: "铅笔 (qiānbǐ)",
      french: "Crayon",
      hintEn: "写字的工具，可以擦掉",
      hintFr: "Tu écris avec, tu peux effacer",
    },
    {
      english: "老师 (lǎoshī)",
      french: "Professeur",
      hintEn: "在学校教书的人",
      hintFr: "Une personne qui enseigne à l'école",
    },
    {
      english: "学生 (xuéshēng)",
      french: "Élève",
      hintEn: "在学校学习的人",
      hintFr: "Une personne qui apprend à l'école",
    },
    {
      english: "书桌 (shūzhuō)",
      french: "Bureau",
      hintEn: "工作或学习用的桌子",
      hintFr: "Une table où tu travailles ou étudies",
    },
    {
      english: "作业 (zuòyè)",
      french: "Devoirs",
      hintEn: "在家做的学校功课",
      hintFr: "Du travail scolaire que tu fais à la maison",
    },
    {
      english: "课 (kè)",
      french: "Leçon",
      hintEn: "在课堂上学习的一段时间",
      hintFr: "Un moment d'apprentissage en classe",
    },
    {
      english: "笔记本 (bǐjìběn)",
      french: "Cahier",
      hintEn: "有空白页可以写字的本子",
      hintFr: "Un livre avec des pages vides pour écrire",
    },
    {
      english: "黑板 (hēibǎn)",
      french: "Tableau",
      hintEn: "老师在上面写字的大板",
      hintFr: "Un grand tableau sombre sur lequel le professeur écrit",
    },
    {
      english: "书包 (shūbāo)",
      french: "Sac",
      hintEn: "你把东西装在里面带着",
      hintFr: "Tu transportes tes affaires dedans",
    },
  ],
  "Les vêtements": [
    {
      english: "衬衫 (chènshān)",
      french: "Chemise",
      hintEn: "穿在上半身的衣服，有纽扣",
      hintFr: "Tu le portes sur le haut du corps, avec des boutons",
    },
    {
      english: "裙子 (qúnzi)",
      french: "Robe",
      hintEn: "一件式的衣服，女孩常穿",
      hintFr: "Un vêtement d'une seule pièce, souvent porté par les filles",
    },
    {
      english: "鞋子 (xiézi)",
      french: "Chaussures",
      hintEn: "穿在脚上走路的",
      hintFr: "Tu les portes aux pieds pour marcher",
    },
    {
      english: "帽子 (màozi)",
      french: "Chapeau",
      hintEn: "戴在头上的",
      hintFr: "Tu le portes sur la tête",
    },
    {
      english: "大衣 (dàyī)",
      french: "Manteau",
      hintEn: "冷天穿的温暖衣服",
      hintFr: "Un vêtement chaud pour le froid",
    },
    {
      english: "裤子 (kùzi)",
      french: "Pantalon",
      hintEn: "穿在腿上的衣服，有两个洞",
      hintFr: "Vêtement pour les jambes, avec deux trous",
    },
    {
      english: "袜子 (wàzi)",
      french: "Chaussettes",
      hintEn: "穿在脚上的，在鞋子里面",
      hintFr: "Tu les portes aux pieds, dans les chaussures",
    },
    {
      english: "手套 (shǒutào)",
      french: "Gants",
      hintEn: "冷的时候戴在手上的",
      hintFr: "Tu les portes aux mains quand il fait froid",
    },
    {
      english: "围巾 (wéijīn)",
      french: "Écharpe",
      hintEn: "冬天围在脖子上的",
      hintFr: "Tu l'enroules autour du cou en hiver",
    },
    {
      english: "短裙 (duǎnqún)",
      french: "Jupe",
      hintEn: "从腰部垂下来的衣服",
      hintFr: "Un vêtement qui pend à partir de la taille",
    },
    {
      english: "毛衣 (máoyī)",
      french: "Pull",
      hintEn: "冷天穿的温暖的针织上衣",
      hintFr: "Un haut en maille chaud pour les jours froids",
    },
    {
      english: "夹克 (jiákè)",
      french: "Veste",
      hintEn: "外出时穿的轻便外套",
      hintFr: "Un manteau léger que tu portes dehors",
    },
  ],
  "Le corps humain": [
    {
      english: "头 (tóu)",
      french: "Tête",
      hintEn: "身体最上面的部分",
      hintFr: "La partie en haut de ton corps",
    },
    {
      english: "手 (shǒu)",
      french: "Main",
      hintEn: "你用它来抓东西",
      hintFr: "Tu l'utilises pour attraper des choses",
    },
    {
      english: "手臂 (shǒubì)",
      french: "Bras",
      hintEn: "在肩膀和手之间的部分",
      hintFr: "Entre ton épaule et ta main",
    },
    {
      english: "腿 (tuǐ)",
      french: "Jambe",
      hintEn: "你用它们来走路",
      hintFr: "Tu les utilises pour marcher",
    },
    {
      english: "脚 (jiǎo)",
      french: "Pied",
      hintEn: "在腿的最下面",
      hintFr: "En bas de ta jambe",
    },
    {
      english: "眼睛 (yǎnjīng)",
      french: "Œil",
      hintEn: "你用它来看东西",
      hintFr: "Tu vois avec",
    },
    {
      english: "耳朵 (ěrduǒ)",
      french: "Oreille",
      hintEn: "你用它来听声音",
      hintFr: "Tu entends avec",
    },
    {
      english: "鼻子 (bízi)",
      french: "Nez",
      hintEn: "你用它来闻气味",
      hintFr: "Tu sens les odeurs avec",
    },
    {
      english: "嘴巴 (zuǐba)",
      french: "Bouche",
      hintEn: "你用它来吃东西和说话",
      hintFr: "Tu manges et parles avec",
    },
    {
      english: "头发 (tóufà)",
      french: "Cheveux",
      hintEn: "长在头上的",
      hintFr: "Ça pousse sur ta tête",
    },
    {
      english: "心脏 (xīnzàng)",
      french: "Cœur",
      hintEn: "它在你身体里泵血",
      hintFr: "Il pompe le sang dans ton corps",
    },
    {
      english: "手指 (shǒuzhǐ)",
      french: "Doigt",
      hintEn: "你的手上有十个",
      hintFr: "Tu en as dix sur tes mains",
    },
  ],
  "La famille": [
    {
      english: "妈妈 (māma)",
      french: "Mère",
      hintEn: "生你的那个女人",
      hintFr: "La femme qui t'a mis au monde",
    },
    {
      english: "爸爸 (bàba)",
      french: "Père",
      hintEn: "你的男性家长",
      hintFr: "Ton parent masculin",
    },
    {
      english: "哥哥/弟弟 (gēge/dìdi)",
      french: "Frère",
      hintEn: "和你有相同父母的男孩",
      hintFr: "Un garçon avec les mêmes parents que toi",
    },
    {
      english: "姐姐/妹妹 (jiějie/mèimei)",
      french: "Sœur",
      hintEn: "和你有相同父母的女孩",
      hintFr: "Une fille avec les mêmes parents que toi",
    },
    {
      english: "奶奶/外婆 (nǎinai/wàipó)",
      french: "Grand-mère",
      hintEn: "你父母的妈妈",
      hintFr: "La mère de ton parent",
    },
    {
      english: "爷爷/外公 (yéye/wàigōng)",
      french: "Grand-père",
      hintEn: "你父母的爸爸",
      hintFr: "Le père de ton parent",
    },
    {
      english: "叔叔 (shūshu)",
      french: "Oncle",
      hintEn: "你父母的兄弟",
      hintFr: "Le frère de ton parent",
    },
    {
      english: "阿姨 (āyí)",
      french: "Tante",
      hintEn: "你父母的姐妹",
      hintFr: "La sœur de ton parent",
    },
    {
      english: "表兄弟 (biǎo xiōngdì)",
      french: "Cousin",
      hintEn: "你叔叔或阿姨的孩子",
      hintFr: "L'enfant de ton oncle ou ta tante",
    },
    {
      english: "宝宝 (bǎobao)",
      french: "Bébé",
      hintEn: "非常小的孩子",
      hintFr: "Un très jeune enfant",
    },
    {
      english: "儿子 (érzi)",
      french: "Fils",
      hintEn: "男孩子",
      hintFr: "Un enfant masculin",
    },
    {
      english: "女儿 (nǚ'ér)",
      french: "Fille",
      hintEn: "女孩子",
      hintFr: "Un enfant féminin",
    },
  ],
  "Les couleurs": [
    {
      english: "红色 (hóngsè)",
      french: "Rouge",
      hintEn: "草莓的颜色",
      hintFr: "La couleur des fraises",
    },
    {
      english: "蓝色 (lánsè)",
      french: "Bleu",
      hintEn: "天空的颜色",
      hintFr: "La couleur du ciel",
    },
    {
      english: "绿色 (lǜsè)",
      french: "Vert",
      hintEn: "草的颜色",
      hintFr: "La couleur de l'herbe",
    },
    {
      english: "黄色 (huángsè)",
      french: "Jaune",
      hintEn: "太阳的颜色",
      hintFr: "La couleur du soleil",
    },
    {
      english: "白色 (báisè)",
      french: "Blanc",
      hintEn: "雪的颜色",
      hintFr: "La couleur de la neige",
    },
    {
      english: "黑色 (hēisè)",
      french: "Noir",
      hintEn: "夜晚的颜色",
      hintFr: "La couleur de la nuit",
    },
    {
      english: "橙色 (chéngsè)",
      french: "Orange",
      hintEn: "胡萝卜的颜色",
      hintFr: "La couleur d'une carotte",
    },
    {
      english: "粉色 (fěnsè)",
      french: "Rose",
      hintEn: "浅红色",
      hintFr: "Une teinte claire de rouge",
    },
    {
      english: "紫色 (zǐsè)",
      french: "Violet",
      hintEn: "红色和蓝色的混合",
      hintFr: "Un mélange de rouge et bleu",
    },
    {
      english: "棕色 (zōngsè)",
      french: "Marron",
      hintEn: "巧克力的颜色",
      hintFr: "La couleur du chocolat",
    },
    {
      english: "灰色 (huīsè)",
      french: "Gris",
      hintEn: "黑色和白色的混合",
      hintFr: "Un mélange de noir et blanc",
    },
    {
      english: "金色 (jīnsè)",
      french: "Doré",
      hintEn: "闪亮的黄色",
      hintFr: "Une couleur jaune brillante",
    },
  ],
  "Les fruits": [
    {
      english: "草莓 (cǎoméi)",
      french: "Fraise",
      hintEn: "小小的红色水果，种子在外面",
      hintFr: "Un petit fruit rouge avec des graines dehors",
    },
    {
      english: "香蕉 (xiāngjiāo)",
      french: "Banane",
      hintEn: "长长的黄色水果",
      hintFr: "Un long fruit jaune",
    },
    {
      english: "葡萄 (pútáo)",
      french: "Raisin",
      hintEn: "一串串长的小圆果",
      hintFr: "Petits fruits ronds qui poussent en grappes",
    },
    {
      english: "柠檬 (níngméng)",
      french: "Citron",
      hintEn: "黄色的酸水果",
      hintFr: "Un fruit jaune acide",
    },
    {
      english: "桃子 (táozi)",
      french: "Pêche",
      hintEn: "有绒毛、有核的软水果",
      hintFr: "Un fruit doux et duveteux avec un noyau",
    },
    {
      english: "樱桃 (yīngtáo)",
      french: "Cerise",
      hintEn: "有梗的小红果",
      hintFr: "Un petit fruit rouge avec une tige",
    },
    {
      english: "梨 (lí)",
      french: "Poire",
      hintEn: "像铃铛的形状，绿色或黄色",
      hintFr: "En forme de cloche, vert ou jaune",
    },
    {
      english: "西瓜 (xīguā)",
      french: "Pastèque",
      hintEn: "外面绿色、里面红色的大水果",
      hintFr: "Un gros fruit vert, rouge à l'intérieur",
    },
    {
      english: "菠萝 (bōluó)",
      french: "Ananas",
      hintEn: "有尖叶子的热带水果",
      hintFr: "Un fruit tropical avec des feuilles piquantes",
    },
    {
      english: "覆盆子 (fùpénzi)",
      french: "Framboise",
      hintEn: "小小的、软软的红色浆果",
      hintFr: "Un petit fruit rouge et mou",
    },
    {
      english: "李子 (lǐzi)",
      french: "Prune",
      hintEn: "皮光滑的小紫色水果",
      hintFr: "Un petit fruit violet à peau lisse",
    },
    {
      english: "杏子 (xìngzi)",
      french: "Abricot",
      hintEn: "像小桃子一样的橙色小水果",
      hintFr: "Un petit fruit orange comme une petite pêche",
    },
  ],
  "Les légumes": [
    {
      english: "胡萝卜 (húluóbo)",
      french: "Carotte",
      hintEn: "长长的橙色蔬菜",
      hintFr: "Un long légume orange",
    },
    {
      english: "土豆 (tǔdòu)",
      french: "Pomme de terre",
      hintEn: "可以做薯条",
      hintFr: "On fait des frites avec",
    },
    {
      english: "番茄 (fānqié)",
      french: "Tomate",
      hintEn: "当蔬菜用的红色水果",
      hintFr: "Un fruit rouge utilisé comme légume",
    },
    {
      english: "洋葱 (yángcōng)",
      french: "Oignon",
      hintEn: "切它的时候会让你流泪",
      hintFr: "Il te fait pleurer quand tu le coupes",
    },
    {
      english: "辣椒 (làjiāo)",
      french: "Poivron",
      hintEn: "有红色、绿色或黄色的",
      hintFr: "Peut être rouge, vert ou jaune",
    },
    {
      english: "生菜 (shēngcài)",
      french: "Laitue",
      hintEn: "用来做沙拉的绿叶",
      hintFr: "Des feuilles vertes pour les salades",
    },
    {
      english: "黄瓜 (huángguā)",
      french: "Concombre",
      hintEn: "长长的绿色蔬菜，里面很凉",
      hintFr: "Un long légume vert, frais à l'intérieur",
    },
    {
      english: "蘑菇 (mógū)",
      french: "Champignon",
      hintEn: "长在森林里的，有帽子",
      hintFr: "Il pousse dans la forêt, avec un chapeau",
    },
    {
      english: "玉米 (yùmǐ)",
      french: "Maïs",
      hintEn: "长在棒子上的黄色颗粒",
      hintFr: "Des grains jaunes sur un épi",
    },
    {
      english: "豌豆 (wāndòu)",
      french: "Petit pois",
      hintEn: "豆荚里的小绿色圆蔬菜",
      hintFr: "Petits légumes verts ronds dans une cosse",
    },
    {
      english: "大蒜 (dàsuàn)",
      french: "Ail",
      hintEn: "做饭用的味道很重的球茎",
      hintFr: "Un bulbe à forte odeur pour cuisiner",
    },
    {
      english: "菠菜 (bōcài)",
      french: "Épinard",
      hintEn: "深绿色的叶子，大力水手的食物",
      hintFr: "Des feuilles vert foncé, la nourriture de Popeye",
    },
  ],
  "Les sports": [
    {
      english: "足球 (zúqiú)",
      french: "Football",
      hintEn: "用圆球和球门的团队运动",
      hintFr: "Un sport d'équipe avec un ballon rond et des buts",
    },
    {
      english: "篮球 (lánqiú)",
      french: "Basket",
      hintEn: "把球投进高处的篮筐",
      hintFr: "Tu lances un ballon dans un panier en hauteur",
    },
    {
      english: "网球 (wǎngqiú)",
      french: "Tennis",
      hintEn: "用球拍隔着网打球",
      hintFr: "Tu frappes une balle avec une raquette par-dessus un filet",
    },
    {
      english: "游泳 (yóuyǒng)",
      french: "Natation",
      hintEn: "在水中用身体移动",
      hintFr: "Se déplacer dans l'eau avec son corps",
    },
    {
      english: "跑步 (pǎobù)",
      french: "Course",
      hintEn: "用脚快速移动",
      hintFr: "Se déplacer vite sur ses pieds",
    },
    {
      english: "骑车 (qíchē)",
      french: "Cyclisme",
      hintEn: "骑自行车",
      hintFr: "Faire du vélo",
    },
    {
      english: "滑雪 (huáxuě)",
      french: "Ski",
      hintEn: "从雪山上滑下去",
      hintFr: "Glisser sur des montagnes enneigées",
    },
    {
      english: "跳舞 (tiàowǔ)",
      french: "Danse",
      hintEn: "跟着音乐摆动身体",
      hintFr: "Bouger son corps sur de la musique",
    },
    {
      english: "拳击 (quánjī)",
      french: "Boxe",
      hintEn: "戴着手套的格斗运动",
      hintFr: "Un sport de combat avec des gants",
    },
    {
      english: "体操 (tǐcāo)",
      french: "Gymnastique",
      hintEn: "有翻跟斗和平衡的运动",
      hintFr: "Un sport avec des sauts et de l'équilibre",
    },
    {
      english: "橄榄球 (gǎnlǎnqiú)",
      french: "Rugby",
      hintEn: "用椭圆形球的团队运动",
      hintFr: "Un sport d'équipe avec un ballon ovale",
    },
    {
      english: "排球 (páiqiú)",
      french: "Volley",
      hintEn: "隔着网击球的团队运动",
      hintFr: "Un sport d'équipe où on frappe un ballon par-dessus un filet",
    },
  ],
  "Les métiers": [
    {
      english: "医生 (yīshēng)",
      french: "Médecin",
      hintEn: "给病人看病的人",
      hintFr: "Une personne qui soigne les malades",
    },
    {
      english: "消防员 (xiāofángyuán)",
      french: "Pompier",
      hintEn: "灭火的人",
      hintFr: "Une personne qui éteint les incendies",
    },
    {
      english: "警察 (jǐngchá)",
      french: "Policier",
      hintEn: "维护法律的人",
      hintFr: "Une personne qui fait respecter la loi",
    },
    {
      english: "面包师 (miànbāoshī)",
      french: "Boulanger",
      hintEn: "做面包的人",
      hintFr: "Une personne qui fait du pain",
    },
    {
      english: "农民 (nóngmín)",
      french: "Fermier",
      hintEn: "种粮食的人",
      hintFr: "Une personne qui cultive la nourriture",
    },
    {
      english: "飞行员 (fēixíngyuán)",
      french: "Pilote",
      hintEn: "开飞机的人",
      hintFr: "Une personne qui pilote les avions",
    },
    {
      english: "护士 (hùshi)",
      french: "Infirmier",
      hintEn: "帮助医生的人",
      hintFr: "Une personne qui aide le médecin",
    },
    {
      english: "理发师 (lǐfàshī)",
      french: "Coiffeur",
      hintEn: "剪头发的人",
      hintFr: "Une personne qui coupe les cheveux",
    },
    {
      english: "服务员 (fúwùyuán)",
      french: "Serveur",
      hintEn: "在餐厅端菜的人",
      hintFr: "Une personne qui sert dans un restaurant",
    },
    {
      english: "牙医 (yáyī)",
      french: "Dentiste",
      hintEn: "照顾牙齿的人",
      hintFr: "Une personne qui soigne les dents",
    },
    {
      english: "律师 (lǜshī)",
      french: "Avocat",
      hintEn: "在法庭上为人辩护的人",
      hintFr: "Une personne qui défend les gens au tribunal",
    },
    {
      english: "机械师 (jīxièshī)",
      french: "Mécanicien",
      hintEn: "修车的人",
      hintFr: "Une personne qui répare les voitures",
    },
  ],
  "Les transports": [
    {
      english: "汽车 (qìchē)",
      french: "Voiture",
      hintEn: "有四个轮子的交通工具",
      hintFr: "Un véhicule à quatre roues",
    },
    {
      english: "公共汽车 (gōnggòng qìchē)",
      french: "Bus",
      hintEn: "可以载很多乘客的大车",
      hintFr: "Un grand véhicule pour beaucoup de passagers",
    },
    {
      english: "火车 (huǒchē)",
      french: "Train",
      hintEn: "在铁轨上跑的",
      hintFr: "Il roule sur des rails",
    },
    {
      english: "自行车 (zìxíngchē)",
      french: "Vélo",
      hintEn: "有两个轮子和脚踏板的交通工具",
      hintFr: "Un véhicule à deux roues et des pédales",
    },
    {
      english: "飞机 (fēijī)",
      french: "Avion",
      hintEn: "在天上飞的",
      hintFr: "Il vole dans le ciel",
    },
    {
      english: "船 (chuán)",
      french: "Bateau",
      hintEn: "在水上走的交通工具",
      hintFr: "Un véhicule qui se déplace sur l'eau",
    },
    {
      english: "摩托车 (mótuōchē)",
      french: "Moto",
      hintEn: "有发动机的快速两轮车",
      hintFr: "Un véhicule rapide à deux roues avec un moteur",
    },
    {
      english: "出租车 (chūzūchē)",
      french: "Taxi",
      hintEn: "付钱坐的车",
      hintFr: "Une voiture que tu payes pour te déplacer",
    },
    {
      english: "地铁 (dìtiě)",
      french: "Métro",
      hintEn: "城市里的地下火车",
      hintFr: "Un train souterrain dans les villes",
    },
    {
      english: "直升机 (zhíshēngjī)",
      french: "Hélicoptère",
      hintEn: "顶上有旋转叶片的飞行器",
      hintFr: "Il vole avec des pales qui tournent",
    },
    {
      english: "卡车 (kǎchē)",
      french: "Camion",
      hintEn: "运货的大车",
      hintFr: "Un gros véhicule pour transporter des marchandises",
    },
    {
      english: "滑板车 (huábǎnchē)",
      french: "Trottinette",
      hintEn: "站着踩的小型交通工具",
      hintFr: "Un petit véhicule sur lequel tu te tiens debout",
    },
  ],
  "La ville": [
    {
      english: "街道 (jiēdào)",
      french: "Rue",
      hintEn: "城市里的路",
      hintFr: "Une route dans une ville",
    },
    {
      english: "建筑 (jiànzhù)",
      french: "Bâtiment",
      hintEn: "有墙和屋顶的结构",
      hintFr: "Une structure avec des murs et un toit",
    },
    {
      english: "公园 (gōngyuán)",
      french: "Parc",
      hintEn: "有树和长椅的绿色空间",
      hintFr: "Un espace vert avec des arbres et des bancs",
    },
    {
      english: "医院 (yīyuàn)",
      french: "Hôpital",
      hintEn: "病人接受治疗的地方",
      hintFr: "Un endroit où les malades sont soignés",
    },
    {
      english: "图书馆 (túshūguǎn)",
      french: "Bibliothèque",
      hintEn: "有很多书可以读的地方",
      hintFr: "Un endroit avec beaucoup de livres à lire",
    },
    {
      english: "博物馆 (bówùguǎn)",
      french: "Musée",
      hintEn: "看艺术和历史的地方",
      hintFr: "Un endroit pour voir de l'art et de l'histoire",
    },
    {
      english: "教堂 (jiàotáng)",
      french: "Église",
      hintEn: "有钟楼的宗教建筑",
      hintFr: "Un bâtiment religieux avec un clocher",
    },
    {
      english: "桥 (qiáo)",
      french: "Pont",
      hintEn: "用来过河的建筑",
      hintFr: "Une structure pour traverser une rivière",
    },
    {
      english: "喷泉 (pēnquán)",
      french: "Fontaine",
      hintEn: "广场上水喷上来的东西",
      hintFr: "L'eau jaillit sur une place",
    },
    {
      english: "市场 (shìchǎng)",
      french: "Marché",
      hintEn: "在外面买新鲜食物的地方",
      hintFr: "Un endroit pour acheter de la nourriture fraîche dehors",
    },
    {
      english: "人行道 (rénxíngdào)",
      french: "Trottoir",
      hintEn: "马路旁边走路的路",
      hintFr: "Le chemin pour marcher le long d'une route",
    },
    {
      english: "塔 (tǎ)",
      french: "Tour",
      hintEn: "又高又窄的建筑",
      hintFr: "Un bâtiment haut et étroit",
    },
  ],
  "Les émotions": [
    {
      english: "开心 (kāixīn)",
      french: "Content",
      hintEn: "感到快乐和高兴",
      hintFr: "Ressentir de la joie et du plaisir",
    },
    {
      english: "伤心 (shāngxīn)",
      french: "Triste",
      hintEn: "不开心，想哭",
      hintFr: "Se sentir malheureux, vouloir pleurer",
    },
    {
      english: "生气 (shēngqì)",
      french: "En colère",
      hintEn: "对某事感到愤怒",
      hintFr: "Se sentir furieux à propos de quelque chose",
    },
    {
      english: "害怕 (hàipà)",
      french: "Effrayé",
      hintEn: "对某事感到恐惧",
      hintFr: "Avoir peur de quelque chose",
    },
    {
      english: "惊讶 (jīngyà)",
      french: "Surpris",
      hintEn: "没有想到发生的事",
      hintFr: "Ne pas s'attendre à ce qui s'est passé",
    },
    {
      english: "累 (lèi)",
      french: "Fatigué",
      hintEn: "需要睡觉或休息",
      hintFr: "Avoir besoin de dormir ou se reposer",
    },
    {
      english: "无聊 (wúliáo)",
      french: "Ennuyé",
      hintEn: "没兴趣，没有好玩的事",
      hintFr: "Pas intéressé, rien d'amusant à faire",
    },
    {
      english: "兴奋 (xīngfèn)",
      french: "Excité",
      hintEn: "对即将发生的事非常开心",
      hintFr: "Très content à propos de quelque chose qui arrive",
    },
    {
      english: "骄傲 (jiāo'ào)",
      french: "Fier",
      hintEn: "对自己的成就感到高兴",
      hintFr: "Content de ce que tu as accompli",
    },
    {
      english: "害羞 (hàixiū)",
      french: "Timide",
      hintEn: "在别人面前紧张",
      hintFr: "Nerveux en présence d'autres personnes",
    },
    {
      english: "嫉妒 (jídù)",
      french: "Jaloux",
      hintEn: "想要别人拥有的东西",
      hintFr: "Vouloir ce que quelqu'un d'autre a",
    },
    {
      english: "孤独 (gūdú)",
      french: "Seul",
      hintEn: "因为一个人而感到难过",
      hintFr: "Se sentir triste parce qu'on est seul",
    },
  ],
  "La météo": [
    {
      english: "晴天 (qíngtiān)",
      french: "Ensoleillé",
      hintEn: "太阳照得很亮的时候",
      hintFr: "Quand le soleil brille fort",
    },
    {
      english: "下雨 (xiàyǔ)",
      french: "Pluvieux",
      hintEn: "水从云朵里落下来",
      hintFr: "Quand l'eau tombe des nuages",
    },
    {
      english: "多云 (duōyún)",
      french: "Nuageux",
      hintEn: "天空被云遮住的时候",
      hintFr: "Quand le ciel est couvert de nuages",
    },
    {
      english: "刮风 (guāfēng)",
      french: "Venteux",
      hintEn: "空气流动很大的时候",
      hintFr: "Quand l'air bouge beaucoup",
    },
    {
      english: "暴风雨 (bàofēngyǔ)",
      french: "Orageux",
      hintEn: "有雷声和闪电",
      hintFr: "Avec du tonnerre et des éclairs",
    },
    {
      english: "大雾 (dàwù)",
      french: "Brumeux",
      hintEn: "因为雾看不远的时候",
      hintFr: "Quand on ne voit pas loin à cause de la brume",
    },
    {
      english: "热 (rè)",
      french: "Chaud",
      hintEn: "温度高，会出汗",
      hintFr: "Température élevée, tu transpires",
    },
    {
      english: "冷 (lěng)",
      french: "Froid",
      hintEn: "温度低，会发抖",
      hintFr: "Température basse, tu frissonnes",
    },
    {
      english: "雷 (léi)",
      french: "Tonnerre",
      hintEn: "暴风雨中的轰隆声",
      hintFr: "Un grand bruit pendant un orage",
    },
    {
      english: "闪电 (shǎndiàn)",
      french: "Éclair",
      hintEn: "暴风雨中天空的光",
      hintFr: "Un flash de lumière dans le ciel pendant un orage",
    },
    {
      english: "彩虹 (cǎihóng)",
      french: "Arc-en-ciel",
      hintEn: "雨后天空中彩色的弧",
      hintFr: "Arc coloré dans le ciel après la pluie",
    },
    {
      english: "霜 (shuāng)",
      french: "Gel",
      hintEn: "早晨地上的冰晶",
      hintFr: "Cristaux de glace au sol le matin",
    },
  ],
  "La musique": [
    {
      english: "吉他 (jítā)",
      french: "Guitare",
      hintEn: "用手弹的弦乐器",
      hintFr: "Un instrument à cordes que l'on gratte",
    },
    {
      english: "钢琴 (gāngqín)",
      french: "Piano",
      hintEn: "有黑白键的大乐器",
      hintFr: "Un grand instrument avec des touches noires et blanches",
    },
    {
      english: "鼓 (gǔ)",
      french: "Batterie",
      hintEn: "用鼓棒敲打来打节奏",
      hintFr: "On les frappe avec des baguettes pour faire du rythme",
    },
    {
      english: "小提琴 (xiǎotíqín)",
      french: "Violon",
      hintEn: "用弓拉的弦乐器",
      hintFr: "Un instrument à cordes joué avec un archet",
    },
    {
      english: "长笛 (chángdí)",
      french: "Flûte",
      hintEn: "从侧面吹的管乐器",
      hintFr: "Un instrument à vent dans lequel on souffle de côté",
    },
    {
      english: "小号 (xiǎohào)",
      french: "Trompette",
      hintEn: "有三个按钮的铜管乐器",
      hintFr: "Un instrument en cuivre avec trois boutons",
    },
    {
      english: "歌手 (gēshǒu)",
      french: "Chanteur",
      hintEn: "唱歌的人",
      hintFr: "Une personne qui chante",
    },
    {
      english: "歌曲 (gēqǔ)",
      french: "Chanson",
      hintEn: "有歌词的音乐",
      hintFr: "Un morceau de musique avec des paroles",
    },
    {
      english: "音乐会 (yīnyuèhuì)",
      french: "Concert",
      hintEn: "现场音乐表演",
      hintFr: "Un spectacle de musique en direct",
    },
    {
      english: "旋律 (xuánlǜ)",
      french: "Mélodie",
      hintEn: "一连串的音符",
      hintFr: "Une suite de notes musicales",
    },
    {
      english: "节奏 (jiézòu)",
      french: "Rythme",
      hintEn: "音乐的节拍模式",
      hintFr: "Le motif de battement de la musique",
    },
    {
      english: "麦克风 (màikèfēng)",
      french: "Microphone",
      hintEn: "让声音变大的设备",
      hintFr: "Un appareil pour rendre ta voix plus forte",
    },
  ],
  "Les insectes": [
    {
      english: "蝴蝶 (húdié)",
      french: "Papillon",
      hintEn: "有大翅膀的彩色昆虫",
      hintFr: "Un insecte coloré avec de grandes ailes",
    },
    {
      english: "蜜蜂 (mìfēng)",
      french: "Abeille",
      hintEn: "会酿蜜，也会蜇人",
      hintFr: "Elle fait du miel et peut piquer",
    },
    {
      english: "蚂蚁 (mǎyǐ)",
      french: "Fourmi",
      hintEn: "群居的小昆虫",
      hintFr: "Un minuscule insecte qui vit en colonies",
    },
    {
      english: "蜘蛛 (zhīzhū)",
      french: "Araignée",
      hintEn: "有八条腿，会织网",
      hintFr: "Elle a huit pattes et fait des toiles",
    },
    {
      english: "苍蝇 (cāngyíng)",
      french: "Mouche",
      hintEn: "嗡嗡叫、停在食物上的昆虫",
      hintFr: "Un insecte bourdonnant qui se pose sur la nourriture",
    },
    {
      english: "蚊子 (wénzi)",
      french: "Moustique",
      hintEn: "它咬你，让你痒",
      hintFr: "Il te pique et te fait gratter",
    },
    {
      english: "瓢虫 (piáochóng)",
      french: "Coccinelle",
      hintEn: "红色有黑点的小昆虫",
      hintFr: "Un petit insecte rouge avec des points noirs",
    },
    {
      english: "蜻蜓 (qīngtíng)",
      french: "Libellule",
      hintEn: "水边有透明翅膀的长昆虫",
      hintFr: "Un long insecte aux ailes transparentes près de l'eau",
    },
    {
      english: "甲虫 (jiǎchóng)",
      french: "Scarabée",
      hintEn: "有硬壳的昆虫",
      hintFr: "Un insecte avec une carapace dure",
    },
    {
      english: "毛毛虫 (máomáochóng)",
      french: "Chenille",
      hintEn: "会变成蝴蝶的幼虫",
      hintFr: "Une larve qui devient un papillon",
    },
    {
      english: "蚱蜢 (zhàměng)",
      french: "Sauterelle",
      hintEn: "跳得很远的绿色昆虫",
      hintFr: "Un insecte vert qui saute loin",
    },
    {
      english: "蜗牛 (wōniú)",
      french: "Escargot",
      hintEn: "背上有壳的慢慢的生物",
      hintFr: "Une créature lente avec une coquille sur le dos",
    },
  ],
  "Les boissons": [
    {
      english: "咖啡 (kāfēi)",
      french: "Café",
      hintEn: "让你清醒的热棕色饮料",
      hintFr: "Une boisson chaude marron qui te réveille",
    },
    {
      english: "茶 (chá)",
      french: "Thé",
      hintEn: "用叶子做的热饮",
      hintFr: "Une boisson chaude faite avec des feuilles",
    },
    {
      english: "果汁 (guǒzhī)",
      french: "Jus",
      hintEn: "榨水果做的饮料",
      hintFr: "Une boisson faite de fruits pressés",
    },
    {
      english: "柠檬水 (níngméngshuǐ)",
      french: "Limonade",
      hintEn: "用柠檬做的甜饮料",
      hintFr: "Une boisson sucrée faite de citrons",
    },
    {
      english: "热巧克力 (rè qiǎokèlì)",
      french: "Chocolat chaud",
      hintEn: "用可可做的温暖甜饮",
      hintFr: "Une boisson chaude sucrée faite de cacao",
    },
    {
      english: "冰沙 (bīngshā)",
      french: "Smoothie",
      hintEn: "用水果打成的浓饮料",
      hintFr: "Une boisson épaisse de fruits mixés",
    },
    {
      english: "奶昔 (nǎixī)",
      french: "Milkshake",
      hintEn: "用牛奶和冰淇淋做的冷饮",
      hintFr: "Une boisson froide de lait et glace",
    },
    {
      english: "气泡水 (qìpàoshuǐ)",
      french: "Eau gazeuse",
      hintEn: "有气泡的水",
      hintFr: "De l'eau avec des bulles",
    },
    {
      english: "汽水 (qìshuǐ)",
      french: "Soda",
      hintEn: "甜的碳酸饮料",
      hintFr: "Une boisson sucrée gazeuse",
    },
    {
      english: "糖浆 (tángjiāng)",
      french: "Sirop",
      hintEn: "和水混着喝的甜稠液体",
      hintFr: "Un liquide sucré et épais qu'on mélange avec de l'eau",
    },
    {
      english: "吸管 (xīguǎn)",
      french: "Paille",
      hintEn: "用来吸饮料的管子",
      hintFr: "Un tube pour siroter ta boisson",
    },
    {
      english: "冰块 (bīngkuài)",
      french: "Glaçon",
      hintEn: "一小块冻住的水",
      hintFr: "Un petit bloc d'eau gelée",
    },
  ],
  "Les desserts": [
    {
      english: "冰淇淋 (bīngqílín)",
      french: "Glace",
      hintEn: "冷冷的甜品，常装在蛋卷里",
      hintFr: "Une gourmandise froide, souvent dans un cornet",
    },
    {
      english: "巧克力 (qiǎokèlì)",
      french: "Chocolat",
      hintEn: "用可可做的棕色甜食",
      hintFr: "Un aliment sucré marron fait de cacao",
    },
    {
      english: "饼干 (bǐnggān)",
      french: "Biscuit",
      hintEn: "小小的、扁扁的、甜甜的烘焙食品",
      hintFr: "Un petit gâteau plat et sucré",
    },
    {
      english: "派 (pài)",
      french: "Tarte",
      hintEn: "有外皮和馅的烤食",
      hintFr: "Un plat cuit avec une croûte et une garniture",
    },
    {
      english: "甜甜圈 (tiántiánquān)",
      french: "Beignet",
      hintEn: "圆形油炸糕点，中间有洞",
      hintFr: "Un gâteau frit rond avec un trou",
    },
    {
      english: "糖果 (tángguǒ)",
      french: "Bonbon",
      hintEn: "小小的甜零食",
      hintFr: "Une petite friandise sucrée",
    },
    {
      english: "华夫饼 (huáfūbǐng)",
      french: "Gaufre",
      hintEn: "有格子图案的脆饼",
      hintFr: "Un gâteau croustillant avec un motif en grille",
    },
    {
      english: "煎饼 (jiānbǐng)",
      french: "Crêpe",
      hintEn: "在锅里煎的薄薄的饼",
      hintFr: "Un gâteau fin et plat cuit à la poêle",
    },
    {
      english: "玛芬 (mǎfēn)",
      french: "Muffin",
      hintEn: "圆圆的小甜蛋糕",
      hintFr: "Un petit gâteau rond et sucré",
    },
    {
      english: "可颂 (kěsòng)",
      french: "Croissant",
      hintEn: "月牙形的酥皮糕点",
      hintFr: "Une viennoiserie feuilletée en forme de lune",
    },
    {
      english: "布丁 (bùdīng)",
      french: "Pudding",
      hintEn: "软软的奶油甜点",
      hintFr: "Un dessert mou et crémeux",
    },
    {
      english: "布朗尼 (bùlǎngní)",
      french: "Brownie",
      hintEn: "方形的浓郁巧克力蛋糕",
      hintFr: "Un gâteau carré au chocolat fondant",
    },
  ],
  "Les ustensiles": [
    {
      english: "叉子 (chāzi)",
      french: "Fourchette",
      hintEn: "有尖齿、用来叉食物的",
      hintFr: "Tu l'utilises pour piquer la nourriture, avec des dents",
    },
    {
      english: "刀 (dāo)",
      french: "Couteau",
      hintEn: "有锋利刀刃的切割工具",
      hintFr: "Un outil avec une lame tranchante pour couper",
    },
    {
      english: "勺子 (sháozi)",
      french: "Cuillère",
      hintEn: "用来喝汤的",
      hintFr: "Tu l'utilises pour manger de la soupe",
    },
    {
      english: "盘子 (pánzi)",
      french: "Assiette",
      hintEn: "放食物的平碟子",
      hintFr: "Un plat à surface plane pour poser la nourriture",
    },
    {
      english: "玻璃杯 (bōlibēi)",
      french: "Verre",
      hintEn: "用来喝水的容器",
      hintFr: "Un récipient pour boire",
    },
    {
      english: "碗 (wǎn)",
      french: "Bol",
      hintEn: "喝汤或吃麦片的圆深碗",
      hintFr: "Un plat rond et profond pour la soupe ou les céréales",
    },
    {
      english: "平底锅 (píngdǐguō)",
      french: "Poêle",
      hintEn: "在炉子上烹饪的金属平锅",
      hintFr: "Un plat plat en métal pour cuisiner sur le feu",
    },
    {
      english: "锅 (guō)",
      french: "Casserole",
      hintEn: "烧水用的深容器",
      hintFr: "Un récipient profond pour faire bouillir de l'eau",
    },
    {
      english: "烤箱 (kǎoxiāng)",
      french: "Four",
      hintEn: "在里面加热食物的箱子",
      hintFr: "Une boîte qui chauffe la nourriture à l'intérieur",
    },
    {
      english: "冰箱 (bīngxiāng)",
      french: "Réfrigérateur",
      hintEn: "让食物保持新鲜的冷机器",
      hintFr: "Une machine froide pour garder la nourriture fraîche",
    },
    {
      english: "杯子 (bēizi)",
      french: "Tasse",
      hintEn: "喝热饮的小容器",
      hintFr: "Un petit récipient pour les boissons chaudes",
    },
    {
      english: "餐巾 (cānjīn)",
      french: "Serviette",
      hintEn: "擦嘴的布或纸",
      hintFr: "Un morceau de tissu ou papier pour s'essuyer la bouche",
    },
  ],
  "Les meubles": [
    {
      english: "沙发 (shāfā)",
      french: "Canapé",
      hintEn: "可以坐几个人的长舒适座位",
      hintFr: "Un long siège confortable pour plusieurs personnes",
    },
    {
      english: "衣柜 (yīguì)",
      french: "Armoire",
      hintEn: "放衣服的高柜子",
      hintFr: "Un grand meuble pour les vêtements",
    },
    {
      english: "架子 (jiàzi)",
      french: "Étagère",
      hintEn: "放东西的平板",
      hintFr: "Une planche pour poser des choses",
    },
    {
      english: "灯 (dēng)",
      french: "Lampe",
      hintEn: "发光的物品",
      hintFr: "Un objet qui donne de la lumière",
    },
    {
      english: "镜子 (jìngzi)",
      french: "Miroir",
      hintEn: "可以看到自己倒影的东西",
      hintFr: "Tu vois ton reflet dedans",
    },
    {
      english: "地毯 (dìtǎn)",
      french: "Tapis",
      hintEn: "地板上柔软的覆盖物",
      hintFr: "Un revêtement doux sur le sol",
    },
    {
      english: "窗帘 (chuānglián)",
      french: "Rideau",
      hintEn: "挂在窗户前面的布",
      hintFr: "Du tissu suspendu devant une fenêtre",
    },
    {
      english: "抽屉 (chōuti)",
      french: "Tiroir",
      hintEn: "从桌子里拉出来的盒子",
      hintFr: "Une boîte que tu tires d'un bureau ou d'une table",
    },
    {
      english: "扶手椅 (fúshǒuyǐ)",
      french: "Fauteuil",
      hintEn: "有扶手的舒适椅子",
      hintFr: "Une chaise confortable avec des accoudoirs",
    },
    {
      english: "时钟 (shízhōng)",
      french: "Horloge",
      hintEn: "挂在墙上显示时间的东西",
      hintFr: "Un objet qui montre l'heure sur un mur",
    },
    {
      english: "靠垫 (kàodiàn)",
      french: "Coussin",
      hintEn: "放在沙发上的软垫",
      hintFr: "Un coussin doux que tu poses sur un canapé",
    },
    {
      english: "花瓶 (huāpíng)",
      french: "Vase",
      hintEn: "插花的容器",
      hintFr: "Un récipient pour les fleurs",
    },
  ],
  "L'espace": [
    {
      english: "行星 (xíngxīng)",
      french: "Planète",
      hintEn: "围绕恒星运转的大物体",
      hintFr: "Un gros objet en orbite autour d'une étoile",
    },
    {
      english: "火箭 (huǒjiàn)",
      french: "Fusée",
      hintEn: "去太空的交通工具",
      hintFr: "Un véhicule qui va dans l'espace",
    },
    {
      english: "宇航员 (yǔhángyuán)",
      french: "Astronaute",
      hintEn: "去太空旅行的人",
      hintFr: "Une personne qui voyage dans l'espace",
    },
    {
      english: "卫星 (wèixīng)",
      french: "Satellite",
      hintEn: "围绕行星运转的物体",
      hintFr: "Un objet en orbite autour d'une planète",
    },
    {
      english: "银河 (yínhé)",
      french: "Galaxie",
      hintEn: "太空中巨大的星群",
      hintFr: "Un immense groupe d'étoiles dans l'espace",
    },
    {
      english: "彗星 (huìxīng)",
      french: "Comète",
      hintEn: "有明亮尾巴的冰和尘埃球",
      hintFr: "Une boule de glace et poussière avec une queue brillante",
    },
    {
      english: "望远镜 (wàngyuǎnjìng)",
      french: "Télescope",
      hintEn: "看天空中远处物体的工具",
      hintFr: "Un outil pour voir des objets lointains dans le ciel",
    },
    {
      english: "引力 (yǐnlì)",
      french: "Gravité",
      hintEn: "把东西往下拉的力",
      hintFr: "La force qui attire les choses vers le bas",
    },
    {
      english: "宇宙飞船 (yǔzhòu fēichuán)",
      french: "Vaisseau spatial",
      hintEn: "在太空中旅行的交通工具",
      hintFr: "Un véhicule pour voyager dans l'espace",
    },
    {
      english: "宇宙 (yǔzhòu)",
      french: "Univers",
      hintEn: "太空中存在的一切",
      hintFr: "Tout ce qui existe dans l'espace",
    },
    {
      english: "轨道 (guǐdào)",
      french: "Orbite",
      hintEn: "行星围绕恒星走的路径",
      hintFr: "Le chemin d'une planète autour d'une étoile",
    },
    {
      english: "外星人 (wàixīngrén)",
      french: "Extraterrestre",
      hintEn: "来自另一个星球的生物",
      hintFr: "Un être venu d'une autre planète",
    },
  ],
  "Les animaux marins": [
    {
      english: "鲸鱼 (jīngyú)",
      french: "Baleine",
      hintEn: "海洋中最大的动物",
      hintFr: "Le plus grand animal de l'océan",
    },
    {
      english: "海豚 (hǎitún)",
      french: "Dauphin",
      hintEn: "聪明的、会跳跃的海洋动物",
      hintFr: "Un animal marin intelligent qui saute",
    },
    {
      english: "鲨鱼 (shāyú)",
      french: "Requin",
      hintEn: "有锋利牙齿的大鱼",
      hintFr: "Un gros poisson avec des dents pointues",
    },
    {
      english: "章鱼 (zhāngyú)",
      french: "Pieuvre",
      hintEn: "有八条手臂的海洋生物",
      hintFr: "Une créature marine avec huit bras",
    },
    {
      english: "水母 (shuǐmǔ)",
      french: "Méduse",
      hintEn: "透明的、会蜇人的海洋生物",
      hintFr: "Une créature marine transparente qui pique",
    },
    {
      english: "螃蟹 (pángxiè)",
      french: "Crabe",
      hintEn: "有钳子、横着走的海洋生物",
      hintFr: "Une créature marine avec des pinces qui marche de côté",
    },
    {
      english: "海龟 (hǎiguī)",
      french: "Tortue",
      hintEn: "有壳的慢动物",
      hintFr: "Un animal lent avec une carapace",
    },
    {
      english: "海马 (hǎimǎ)",
      french: "Hippocampe",
      hintEn: "像马形状的小鱼",
      hintFr: "Un petit poisson en forme de cheval",
    },
    {
      english: "海星 (hǎixīng)",
      french: "Étoile de mer",
      hintEn: "星星形状的海洋生物",
      hintFr: "Une créature marine en forme d'étoile",
    },
    {
      english: "龙虾 (lóngxiā)",
      french: "Homard",
      hintEn: "有大钳子的大型海洋生物",
      hintFr: "Une grande créature marine avec de grosses pinces",
    },
    {
      english: "海豹 (hǎibào)",
      french: "Phoque",
      hintEn: "有鳍的海洋哺乳动物",
      hintFr: "Un mammifère marin avec des nageoires",
    },
    {
      english: "珊瑚 (shānhú)",
      french: "Corail",
      hintEn: "海底的彩色结构",
      hintFr: "Des structures colorées au fond de l'océan",
    },
  ],
  "Les oiseaux": [
    {
      english: "鹰 (yīng)",
      french: "Aigle",
      hintEn: "视力很好的大型猛禽",
      hintFr: "Un grand oiseau de proie à la vue perçante",
    },
    {
      english: "鹦鹉 (yīngwǔ)",
      french: "Perroquet",
      hintEn: "会说话的彩色鸟",
      hintFr: "Un oiseau coloré qui peut parler",
    },
    {
      english: "猫头鹰 (māotóuyīng)",
      french: "Hibou",
      hintEn: "夜晚捕猎的鸟",
      hintFr: "Un oiseau qui chasse la nuit",
    },
    {
      english: "天鹅 (tiān'é)",
      french: "Cygne",
      hintEn: "有长脖子的白色大鸟",
      hintFr: "Un grand oiseau blanc avec un long cou",
    },
    {
      english: "企鹅 (qì'é)",
      french: "Pingouin",
      hintEn: "不会飞的黑白鸟",
      hintFr: "Un oiseau noir et blanc qui ne peut pas voler",
    },
    {
      english: "孔雀 (kǒngquè)",
      french: "Paon",
      hintEn: "有漂亮彩色尾羽的鸟",
      hintFr: "Un oiseau avec de belles plumes colorées",
    },
    {
      english: "麻雀 (máquè)",
      french: "Moineau",
      hintEn: "常见的棕色小鸟",
      hintFr: "Un petit oiseau brun commun",
    },
    {
      english: "乌鸦 (wūyā)",
      french: "Corbeau",
      hintEn: "非常聪明的黑色大鸟",
      hintFr: "Un grand oiseau noir très intelligent",
    },
    {
      english: "火烈鸟 (huǒlièniǎo)",
      french: "Flamant rose",
      hintEn: "有长腿的粉色大鸟",
      hintFr: "Un grand oiseau rose avec de longues pattes",
    },
    {
      english: "鸽子 (gēzi)",
      french: "Pigeon",
      hintEn: "城市里常见的灰色鸟",
      hintFr: "Un oiseau gris commun dans les villes",
    },
    {
      english: "鹳 (guàn)",
      french: "Cigogne",
      hintEn: "有长嘴的白色大鸟",
      hintFr: "Un grand oiseau blanc avec un long bec",
    },
    {
      english: "知更鸟 (zhīgēngniǎo)",
      french: "Rouge-gorge",
      hintEn: "胸口红色的小鸟",
      hintFr: "Un petit oiseau avec la poitrine rouge",
    },
  ],
  "La plage": [
    {
      english: "沙子 (shāzi)",
      french: "Sable",
      hintEn: "覆盖海滩的小颗粒",
      hintFr: "De petits grains qui couvrent la plage",
    },
    {
      english: "海浪 (hǎilàng)",
      french: "Vague",
      hintEn: "拍打到岸边的水",
      hintFr: "De l'eau qui bouge et s'écrase sur le rivage",
    },
    {
      english: "防晒霜 (fángshàishuāng)",
      french: "Crème solaire",
      hintEn: "保护皮肤不被晒伤的乳液",
      hintFr: "Une crème pour protéger la peau du soleil",
    },
    {
      english: "遮阳伞 (zhēyángsǎn)",
      french: "Parasol",
      hintEn: "在沙滩上遮阳的",
      hintFr: "Donne de l'ombre sur la plage",
    },
    {
      english: "泳衣 (yǒngyī)",
      french: "Maillot de bain",
      hintEn: "游泳穿的衣服",
      hintFr: "Vêtement pour nager",
    },
    {
      english: "毛巾 (máojīn)",
      french: "Serviette",
      hintEn: "擦干身体的布",
      hintFr: "Un tissu pour se sécher",
    },
    {
      english: "贝壳 (bèiké)",
      french: "Coquillage",
      hintEn: "海洋生物的硬壳",
      hintFr: "Une couverture dure d'une créature marine",
    },
    {
      english: "冲浪板 (chōnglàngbǎn)",
      french: "Planche de surf",
      hintEn: "在浪上滑行的板",
      hintFr: "Une planche pour glisser sur les vagues",
    },
    {
      english: "沙堡 (shābǎo)",
      french: "Château de sable",
      hintEn: "用湿沙做的城堡",
      hintFr: "Un château fait de sable mouillé",
    },
    {
      english: "海鸥 (hǎi'ōu)",
      french: "Mouette",
      hintEn: "海滩上的白色鸟",
      hintFr: "Un oiseau blanc à la plage",
    },
    {
      english: "日落 (rìluò)",
      french: "Coucher de soleil",
      hintEn: "傍晚太阳下山的时候",
      hintFr: "Quand le soleil descend le soir",
    },
    {
      english: "救生员 (jiùshēngyuán)",
      french: "Maître-nageur",
      hintEn: "看管游泳者的人",
      hintFr: "Une personne qui surveille les nageurs",
    },
  ],
  "Les jouets": [
    {
      english: "娃娃 (wáwa)",
      french: "Poupée",
      hintEn: "看起来像小人的玩具",
      hintFr: "Un jouet qui ressemble à une petite personne",
    },
    {
      english: "拼图 (pīntú)",
      french: "Puzzle",
      hintEn: "把碎片拼在一起组成图片",
      hintFr: "Des pièces à assembler pour faire une image",
    },
    {
      english: "球 (qiú)",
      french: "Ballon",
      hintEn: "你扔或踢的圆形东西",
      hintFr: "Un objet rond que tu lances ou que tu frappes",
    },
    {
      english: "泰迪熊 (tàidíxióng)",
      french: "Nounours",
      hintEn: "柔软的毛绒玩具熊",
      hintFr: "Un ours en peluche tout doux",
    },
    {
      english: "风筝 (fēngzhēng)",
      french: "Cerf-volant",
      hintEn: "用绳子拉着在风中飞的玩具",
      hintFr: "Un jouet qui vole dans le vent au bout d'un fil",
    },
    {
      english: "机器人 (jīqìrén)",
      french: "Robot",
      hintEn: "会动的机械玩具",
      hintFr: "Un jouet mécanique qui bouge",
    },
    {
      english: "积木 (jīmù)",
      french: "Cubes",
      hintEn: "你堆起来搭东西的",
      hintFr: "Tu les empiles pour construire des choses",
    },
    {
      english: "桌游 (zhuōyóu)",
      french: "Jeu de société",
      hintEn: "在棋盘上用棋子玩的游戏",
      hintFr: "Un jeu avec un plateau et des pions",
    },
    {
      english: "弹珠 (tánzhū)",
      french: "Bille",
      hintEn: "小小的玻璃球",
      hintFr: "Une petite boule en verre",
    },
    {
      english: "气球 (qìqiú)",
      french: "Ballon de baudruche",
      hintEn: "你吹气的橡皮袋",
      hintFr: "Un sac en caoutchouc que tu gonfles",
    },
    {
      english: "滑梯 (huátī)",
      french: "Toboggan",
      hintEn: "在游乐场上滑下去的",
      hintFr: "Tu descends dessus au parc",
    },
    {
      english: "秋千 (qiūqiān)",
      french: "Balançoire",
      hintEn: "用链子挂着的座位，前后摆动",
      hintFr: "Un siège suspendu à des chaînes qui va et vient",
    },
  ],
  "Le restaurant": [
    {
      english: "菜单 (càidān)",
      french: "Menu",
      hintEn: "你可以点的菜的清单",
      hintFr: "Une liste de plats que tu peux commander",
    },
    {
      english: "账单 (zhàngdān)",
      french: "Addition",
      hintEn: "写着你要付多少钱的纸",
      hintFr: "Le papier qui montre ce que tu dois payer",
    },
    {
      english: "小费 (xiǎofèi)",
      french: "Pourboire",
      hintEn: "给服务员的额外的钱",
      hintFr: "De l'argent en plus que tu donnes au serveur",
    },
    {
      english: "预订 (yùdìng)",
      french: "Réservation",
      hintEn: "提前订好桌子",
      hintFr: "Réserver une table à l'avance",
    },
    {
      english: "前菜 (qiáncài)",
      french: "Entrée",
      hintEn: "主菜前的小菜",
      hintFr: "Un petit plat avant le plat principal",
    },
    {
      english: "主菜 (zhǔcài)",
      french: "Plat principal",
      hintEn: "一顿饭中最大的菜",
      hintFr: "Le plus grand plat d'un repas",
    },
    {
      english: "厨师 (chúshī)",
      french: "Chef cuisinier",
      hintEn: "在厨房做饭的人",
      hintFr: "La personne qui cuisine en cuisine",
    },
    {
      english: "点菜 (diǎncài)",
      french: "Commande",
      hintEn: "你在餐厅要的东西",
      hintFr: "Ce que tu demandes au restaurant",
    },
    {
      english: "食谱 (shípǔ)",
      french: "Recette",
      hintEn: "做菜的说明",
      hintFr: "Les instructions pour préparer un plat",
    },
    {
      english: "菜 (cài)",
      french: "Plat",
      hintEn: "端上来的一种食物",
      hintFr: "Un type de nourriture servi",
    },
    {
      english: "桌布 (zhuōbù)",
      french: "Nappe",
      hintEn: "盖在桌子上的布",
      hintFr: "Un tissu qui couvre la table",
    },
    {
      english: "蜡烛 (làzhú)",
      french: "Bougie",
      hintEn: "有火焰的蜡棒",
      hintFr: "Un bâton de cire avec une flamme",
    },
  ],
  "Le camping": [
    {
      english: "帐篷 (zhàngpéng)",
      french: "Tente",
      hintEn: "用布做的可以搬动的遮蔽处",
      hintFr: "Un abri portable en tissu",
    },
    {
      english: "睡袋 (shuìdài)",
      french: "Sac de couchage",
      hintEn: "睡觉用的暖和袋子",
      hintFr: "Un sac chaud pour dormir",
    },
    {
      english: "篝火 (gōuhuǒ)",
      french: "Feu de camp",
      hintEn: "在外面生的火，用来取暖",
      hintFr: "Un feu fait dehors pour se réchauffer",
    },
    {
      english: "手电筒 (shǒudiàntǒng)",
      french: "Lampe torche",
      hintEn: "可以带着走的小灯",
      hintFr: "Une petite lumière portable",
    },
    {
      english: "指南针 (zhǐnánzhēn)",
      french: "Boussole",
      hintEn: "指示北方的工具",
      hintFr: "Un outil qui montre le nord",
    },
    {
      english: "地图 (dìtú)",
      french: "Carte",
      hintEn: "一个地区的图画",
      hintFr: "Un dessin d'une zone",
    },
    {
      english: "背包 (bēibāo)",
      french: "Sac à dos",
      hintEn: "背在背上的包",
      hintFr: "Un sac que tu portes sur le dos",
    },
    {
      english: "徒步 (túbù)",
      french: "Randonnée",
      hintEn: "在大自然中走很长时间",
      hintFr: "Marcher longtemps dans la nature",
    },
    {
      english: "小径 (xiǎojìng)",
      french: "Sentier",
      hintEn: "穿过森林的小路",
      hintFr: "Un chemin à travers la forêt",
    },
    {
      english: "小木屋 (xiǎo mùwū)",
      french: "Cabane",
      hintEn: "树林中的小木房子",
      hintFr: "Une petite maison en bois dans les bois",
    },
    {
      english: "望远镜 (wàngyuǎnjìng)",
      french: "Jumelles",
      hintEn: "看远处东西的工具",
      hintFr: "Un outil pour voir les choses au loin",
    },
    {
      english: "柴火 (cháihuǒ)",
      french: "Bois de chauffage",
      hintEn: "用来生火的木头",
      hintFr: "Du bois utilisé pour faire un feu",
    },
  ],
  "Les voyages": [
    {
      english: "行李箱 (xínglixiāng)",
      french: "Valise",
      hintEn: "旅行用的大包",
      hintFr: "Un grand sac pour voyager",
    },
    {
      english: "酒店 (jiǔdiàn)",
      french: "Hôtel",
      hintEn: "旅行时睡觉的地方",
      hintFr: "Un endroit pour dormir quand on voyage",
    },
    {
      english: "游客 (yóukè)",
      french: "Touriste",
      hintEn: "参观某个地方的人",
      hintFr: "Une personne qui visite un endroit",
    },
    {
      english: "相机 (xiàngjī)",
      french: "Appareil photo",
      hintEn: "拍照的设备",
      hintFr: "Un appareil pour prendre des photos",
    },
    {
      english: "纪念品 (jìniànpǐn)",
      french: "Souvenir",
      hintEn: "用来记住一次旅行的东西",
      hintFr: "Un objet pour se rappeler d'un voyage",
    },
    {
      english: "护照 (hùzhào)",
      french: "Passeport",
      hintEn: "出国旅行的官方文件",
      hintFr: "Un document officiel pour voyager à l'étranger",
    },
    {
      english: "明信片 (míngxìnpiàn)",
      french: "Carte postale",
      hintEn: "度假时寄出的有图片的卡片",
      hintFr: "Une carte avec une image que tu envoies en vacances",
    },
    {
      english: "行李 (xíngli)",
      french: "Bagages",
      hintEn: "旅行时带的所有包",
      hintFr: "Tous les sacs que tu prends en voyage",
    },
    {
      english: "目的地 (mùdìdì)",
      french: "Destination",
      hintEn: "你要去的地方",
      hintFr: "L'endroit où tu vas",
    },
    {
      english: "假期 (jiàqī)",
      french: "Vacances",
      hintEn: "不上学不工作的休息时间",
      hintFr: "Du temps libre sans école ni travail",
    },
    {
      english: "导游 (dǎoyóu)",
      french: "Guide",
      hintEn: "带你参观的人",
      hintFr: "Une personne qui te fait visiter",
    },
    {
      english: "冒险 (màoxiǎn)",
      french: "Aventure",
      hintEn: "令人兴奋的不寻常的经历",
      hintFr: "Une expérience excitante et inhabituelle",
    },
  ],
  "La fête": [
    {
      english: "生日 (shēngrì)",
      french: "Anniversaire",
      hintEn: "你出生的那天，每年庆祝",
      hintFr: "Le jour de ta naissance, fêté chaque année",
    },
    {
      english: "礼物 (lǐwù)",
      french: "Cadeau",
      hintEn: "你送给别人的东西",
      hintFr: "Quelque chose que tu donnes à quelqu'un",
    },
    {
      english: "邀请 (yāoqǐng)",
      french: "Invitation",
      hintEn: "请别人来的卡片",
      hintFr: "Une carte qui demande à quelqu'un de venir",
    },
    {
      english: "客人 (kèrén)",
      french: "Invité",
      hintEn: "来参加你的聚会的人",
      hintFr: "Une personne qui vient à ta fête",
    },
    {
      english: "跳舞 (tiàowǔ)",
      french: "Danse",
      hintEn: "在聚会上跟着音乐摆动",
      hintFr: "Bouger sur la musique à une fête",
    },
    {
      english: "烟花 (yānhuā)",
      french: "Feux d'artifice",
      hintEn: "天空中的彩色爆炸",
      hintFr: "Des explosions colorées dans le ciel",
    },
    {
      english: "化装 (huàzhuāng)",
      french: "Déguisement",
      hintEn: "特别的衣服，让自己看起来像别人",
      hintFr: "Des vêtements spéciaux pour ressembler à quelqu'un d'autre",
    },
    {
      english: "五彩纸屑 (wǔcǎi zhǐxiè)",
      french: "Confettis",
      hintEn: "往空中撒的彩色小纸片",
      hintFr: "Petits morceaux de papier coloré lancés en l'air",
    },
    {
      english: "惊喜 (jīngxǐ)",
      french: "Surprise",
      hintEn: "意想不到的美好事物",
      hintFr: "Quelque chose d'inattendu et d'agréable",
    },
    {
      english: "庆祝 (qìngzhù)",
      french: "Célébration",
      hintEn: "大家聚在一起的快乐活动",
      hintFr: "Un événement joyeux avec des gens réunis",
    },
    {
      english: "装饰 (zhuāngshì)",
      french: "Décoration",
      hintEn: "让地方变漂亮的东西",
      hintFr: "Des choses pour rendre un endroit joli",
    },
    {
      english: "包装纸 (bāozhuāngzhǐ)",
      french: "Papier cadeau",
      hintEn: "用来包礼物的纸",
      hintFr: "Du papier pour emballer les cadeaux",
    },
  ],
  "L'informatique": [
    {
      english: "电脑 (diànnǎo)",
      french: "Ordinateur",
      hintEn: "工作和上网用的机器",
      hintFr: "Une machine pour travailler et naviguer",
    },
    {
      english: "键盘 (jiànpán)",
      french: "Clavier",
      hintEn: "用手指在上面打字的",
      hintFr: "Tu tapes dessus avec tes doigts",
    },
    {
      english: "屏幕 (píngmù)",
      french: "Écran",
      hintEn: "电脑上你看的那个部分",
      hintFr: "La partie que tu regardes sur un ordinateur",
    },
    {
      english: "互联网 (hùliánwǎng)",
      french: "Internet",
      hintEn: "连接电脑的全球网络",
      hintFr: "Un réseau mondial reliant les ordinateurs",
    },
    {
      english: "网站 (wǎngzhàn)",
      french: "Site web",
      hintEn: "互联网上的页面",
      hintFr: "Une page sur internet",
    },
    {
      english: "密码 (mìmǎ)",
      french: "Mot de passe",
      hintEn: "登录账号的秘密代码",
      hintFr: "Un code secret pour accéder à ton compte",
    },
    {
      english: "电子邮件 (diànzǐ yóujiàn)",
      french: "E-mail",
      hintEn: "电子信息",
      hintFr: "Un message électronique",
    },
    {
      english: "文件 (wénjiàn)",
      french: "Fichier",
      hintEn: "保存在电脑上的文档",
      hintFr: "Un document enregistré sur un ordinateur",
    },
    {
      english: "打印机 (dǎyìnjī)",
      french: "Imprimante",
      hintEn: "把文字印到纸上的机器",
      hintFr: "Une machine qui met du texte sur du papier",
    },
    {
      english: "下载 (xiàzài)",
      french: "Téléchargement",
      hintEn: "从网上获取文件",
      hintFr: "Récupérer un fichier depuis internet",
    },
    {
      english: "应用 (yìngyòng)",
      french: "Application",
      hintEn: "手机或电脑上的程序",
      hintFr: "Un programme sur ton téléphone ou ordinateur",
    },
    {
      english: "电池 (diànchí)",
      french: "Batterie",
      hintEn: "给手机提供电力的东西",
      hintFr: "Ce qui donne de l'énergie à ton téléphone",
    },
  ],
  "Les formes": [
    {
      english: "圆形 (yuánxíng)",
      french: "Cercle",
      hintEn: "完全圆的形状",
      hintFr: "Une forme parfaitement ronde",
    },
    {
      english: "正方形 (zhèngfāngxíng)",
      french: "Carré",
      hintEn: "四条边一样长的形状",
      hintFr: "Une forme avec quatre côtés égaux",
    },
    {
      english: "三角形 (sānjiǎoxíng)",
      french: "Triangle",
      hintEn: "有三条边的形状",
      hintFr: "Une forme avec trois côtés",
    },
    {
      english: "长方形 (chángfāngxíng)",
      french: "Rectangle",
      hintEn: "四条边、比宽长的形状",
      hintFr: "Une forme à quatre côtés, plus long que large",
    },
    {
      english: "星形 (xīngxíng)",
      french: "Étoile",
      hintEn: "有尖角的形状",
      hintFr: "Une forme avec des pointes",
    },
    {
      english: "菱形 (língxíng)",
      french: "Losange",
      hintEn: "像倾斜的正方形",
      hintFr: "Une forme comme un carré penché",
    },
    {
      english: "心形 (xīnxíng)",
      french: "Cœur",
      hintEn: "代表爱的形状",
      hintFr: "Une forme qui représente l'amour",
    },
    {
      english: "椭圆形 (tuǒyuánxíng)",
      french: "Ovale",
      hintEn: "像拉长的圆形",
      hintFr: "Une forme comme un cercle étiré",
    },
    {
      english: "立方体 (lìfāngtǐ)",
      french: "Cube",
      hintEn: "像盒子一样的三维形状，各边相等",
      hintFr: "Une forme 3D comme une boîte à côtés égaux",
    },
    {
      english: "球体 (qiútǐ)",
      french: "Sphère",
      hintEn: "像球一样的三维形状",
      hintFr: "Une forme 3D comme une balle",
    },
    {
      english: "金字塔 (jīnzìtǎ)",
      french: "Pyramide",
      hintEn: "底部是方形、侧面是三角形的三维形状",
      hintFr: "Une forme 3D avec une base carrée et des côtés triangulaires",
    },
    {
      english: "箭头 (jiàntóu)",
      french: "Flèche",
      hintEn: "指向一个方向的形状",
      hintFr: "Une forme qui pointe dans une direction",
    },
  ],
};
