const themesEs = {
  "La maison": [
    {
      english: "Mesa",
      french: "Table",
      hintEn: "Un mueble con patas para comer o trabajar",
      hintFr: "Surface plate avec des pieds, pour manger ou travailler",
    },
    {
      english: "Silla",
      french: "Chaise",
      hintEn: "Un asiento con respaldo, para una persona",
      hintFr: "Un siège avec un dossier, pour une personne",
    },
    {
      english: "Ventana",
      french: "Fenêtre",
      hintEn: "Una abertura en la pared con vidrio, para ver afuera",
      hintFr: "Une ouverture dans un mur avec du verre, pour voir dehors",
    },
    {
      english: "Cama",
      french: "Lit",
      hintEn: "Donde duermes por la noche",
      hintFr: "Là où tu dors la nuit",
    },
    {
      english: "Puerta",
      french: "Porte",
      hintEn: "La abres para entrar o salir de una habitación",
      hintFr: "Tu l'ouvres pour entrer ou sortir d'une pièce",
    },
    {
      english: "Cocina",
      french: "Cuisine",
      hintEn: "La habitación donde se prepara la comida",
      hintFr: "La pièce où on prépare les repas",
    },
    {
      english: "Cuarto de baño",
      french: "Salle de bain",
      hintEn: "La habitación con una ducha o una bañera",
      hintFr: "La pièce avec une douche ou une baignoire",
    },
    {
      english: "Jardín",
      french: "Jardin",
      hintEn: "Un espacio exterior con plantas y flores",
      hintFr: "Un espace extérieur avec des plantes et des fleurs",
    },
    {
      english: "Tejado",
      french: "Toit",
      hintEn: "La parte de arriba de la casa que protege de la lluvia",
      hintFr: "La partie en haut de la maison qui protège de la pluie",
    },
    {
      english: "Pared",
      french: "Mur",
      hintEn: "Una superficie vertical que separa las habitaciones",
      hintFr: "Une surface verticale qui sépare les pièces",
    },
    {
      english: "Suelo",
      french: "Sol",
      hintEn: "La superficie sobre la que caminas dentro de la casa",
      hintFr: "La surface sur laquelle tu marches dans la maison",
    },
    {
      english: "Escalera",
      french: "Escalier",
      hintEn: "Peldaños para subir o bajar entre los pisos",
      hintFr: "Des marches pour monter ou descendre entre les étages",
    },
  ],
  "La nourriture": [
    {
      english: "Manzana",
      french: "Pomme",
      hintEn: "Una fruta redonda, roja o verde",
      hintFr: "Un fruit rond, rouge ou vert",
    },
    {
      english: "Pan",
      french: "Pain",
      hintEn: "Un alimento hecho con harina que se hornea",
      hintFr: "Un aliment fait avec de la farine qu'on cuit au four",
    },
    {
      english: "Queso",
      french: "Fromage",
      hintEn: "Un alimento hecho con leche, a veces con agujeros",
      hintFr: "Un aliment fait avec du lait, parfois avec des trous",
    },
    {
      english: "Pastel",
      french: "Gâteau",
      hintEn: "Un postre dulce que se come en los cumpleaños",
      hintFr: "Un dessert sucré qu'on mange aux anniversaires",
    },
    {
      english: "Leche",
      french: "Lait",
      hintEn: "Una bebida blanca que viene de la vaca",
      hintFr: "Une boisson blanche qui vient de la vache",
    },
    {
      english: "Agua",
      french: "Eau",
      hintEn: "Un líquido transparente que bebemos todos los días",
      hintFr: "Un liquide transparent qu'on boit tous les jours",
    },
    {
      english: "Pollo",
      french: "Poulet",
      hintEn: "Una carne blanca que viene de un ave de corral",
      hintFr: "Une viande blanche qui vient d'un oiseau de basse-cour",
    },
    {
      english: "Arroz",
      french: "Riz",
      hintEn: "Pequeños granos blancos que se cocinan en agua",
      hintFr: "Des petits grains blancs qu'on cuit dans l'eau",
    },
    {
      english: "Ensalada",
      french: "Salade",
      hintEn: "Un plato frío con lechuga y verduras",
      hintFr: "Un plat froid avec de la laitue et des légumes",
    },
    {
      english: "Mantequilla",
      french: "Beurre",
      hintEn: "Un producto amarillo hecho con leche, para untar en el pan",
      hintFr: "Un produit jaune fait avec du lait, à tartiner sur le pain",
    },
    {
      english: "Huevo",
      french: "Oeuf",
      hintEn: "Viene de la gallina, tiene cáscara y yema",
      hintFr: "Vient de la poule, a une coquille et un jaune",
    },
    {
      english: "Azúcar",
      french: "Sucre",
      hintEn: "Un polvo blanco dulce que se añade a los postres",
      hintFr: "Une poudre blanche sucrée qu'on ajoute aux desserts",
    },
  ],
  "Les animaux": [
    {
      english: "Perro",
      french: "Chien",
      hintEn: "El mejor amigo del hombre, ladra",
      hintFr: "Le meilleur ami de l'homme, il aboie",
    },
    {
      english: "Gato",
      french: "Chat",
      hintEn: "Un animal pequeño que ronronea y caza ratones",
      hintFr: "Un petit animal qui ronronne et chasse les souris",
    },
    {
      english: "Pájaro",
      french: "Oiseau",
      hintEn: "Un animal con alas y plumas que vuela",
      hintFr: "Un animal avec des ailes et des plumes qui vole",
    },
    {
      english: "Pez",
      french: "Poisson",
      hintEn: "Un animal que vive en el agua y tiene aletas",
      hintFr: "Un animal qui vit dans l'eau et a des nageoires",
    },
    {
      english: "Caballo",
      french: "Cheval",
      hintEn: "Un animal grande que se puede montar",
      hintFr: "Un grand animal qu'on peut monter",
    },
    {
      english: "Conejo",
      french: "Lapin",
      hintEn: "Un animal pequeño con orejas largas que salta",
      hintFr: "Un petit animal avec de longues oreilles qui saute",
    },
    {
      english: "Ratón",
      french: "Souris",
      hintEn: "Un roedor muy pequeño y gris",
      hintFr: "Un tout petit rongeur gris",
    },
    {
      english: "Vaca",
      french: "Vache",
      hintEn: "Un animal de granja que da leche",
      hintFr: "Un animal de ferme qui donne du lait",
    },
    {
      english: "Cerdo",
      french: "Cochon",
      hintEn: "Un animal rosa de granja que gruñe",
      hintFr: "Un animal rose de la ferme qui grogne",
    },
    {
      english: "Oveja",
      french: "Mouton",
      hintEn: "Un animal de granja cubierto de lana",
      hintFr: "Un animal de ferme couvert de laine",
    },
    {
      english: "Serpiente",
      french: "Serpent",
      hintEn: "Un reptil largo y sin patas que se arrastra",
      hintFr: "Un reptile long et sans pattes qui rampe",
    },
    {
      english: "Tortuga",
      french: "Tortue",
      hintEn: "Un animal lento con un caparazón duro",
      hintFr: "Un animal lent avec une carapace dure",
    },
  ],
  "La nature": [
    {
      english: "Árbol",
      french: "Arbre",
      hintEn: "Una planta grande con tronco, ramas y hojas",
      hintFr: "Une grande plante avec un tronc, des branches et des feuilles",
    },
    {
      english: "Flor",
      french: "Fleur",
      hintEn: "Una planta bonita y colorida que huele bien",
      hintFr: "Une jolie plante colorée qui sent bon",
    },
    {
      english: "Río",
      french: "Rivière",
      hintEn: "Una corriente de agua que fluye por la tierra",
      hintFr: "Un cours d'eau qui coule à travers la terre",
    },
    {
      english: "Montaña",
      french: "Montagne",
      hintEn: "Una gran elevación de tierra muy alta",
      hintFr: "Une très grande élévation de terrain",
    },
    {
      english: "Bosque",
      french: "Forêt",
      hintEn: "Un lugar con muchos árboles juntos",
      hintFr: "Un endroit avec beaucoup d'arbres ensemble",
    },
    {
      english: "Lago",
      french: "Lac",
      hintEn: "Una gran extensión de agua rodeada de tierra",
      hintFr: "Une grande étendue d'eau entourée de terre",
    },
    {
      english: "Sol",
      french: "Soleil",
      hintEn: "La estrella que nos da luz y calor durante el día",
      hintFr: "L'étoile qui nous donne lumière et chaleur pendant la journée",
    },
    {
      english: "Luna",
      french: "Lune",
      hintEn: "Brilla en el cielo por la noche",
      hintFr: "Elle brille dans le ciel la nuit",
    },
    {
      english: "Estrella",
      french: "Étoile",
      hintEn: "Un punto brillante en el cielo nocturno",
      hintFr: "Un point brillant dans le ciel la nuit",
    },
    {
      english: "Nube",
      french: "Nuage",
      hintEn: "Una masa blanca o gris que flota en el cielo",
      hintFr: "Une masse blanche ou grise qui flotte dans le ciel",
    },
    {
      english: "Lluvia",
      french: "Pluie",
      hintEn: "Gotas de agua que caen del cielo",
      hintFr: "Des gouttes d'eau qui tombent du ciel",
    },
    {
      english: "Viento",
      french: "Vent",
      hintEn: "El aire que se mueve y sopla",
      hintFr: "L'air qui bouge et qui souffle",
    },
  ],
  "L'école": [
    {
      english: "Libro",
      french: "Livre",
      hintEn: "Un objeto con páginas que lees para aprender",
      hintFr: "Un objet avec des pages que tu lis pour apprendre",
    },
    {
      english: "Cuaderno",
      french: "Cahier",
      hintEn: "Un conjunto de hojas donde escribes en clase",
      hintFr: "Un ensemble de feuilles où tu écris en classe",
    },
    {
      english: "Bolígrafo",
      french: "Stylo",
      hintEn: "Un instrumento con tinta para escribir",
      hintFr: "Un instrument avec de l'encre pour écrire",
    },
    {
      english: "Lápiz",
      french: "Crayon",
      hintEn: "Un instrumento de madera con mina para escribir o dibujar",
      hintFr: "Un instrument en bois avec une mine pour écrire ou dessiner",
    },
    {
      english: "Pizarra",
      french: "Tableau",
      hintEn: "Una superficie grande donde el profesor escribe",
      hintFr: "Une grande surface où le professeur écrit",
    },
    {
      english: "Profesor",
      french: "Professeur",
      hintEn: "La persona que enseña en la escuela",
      hintFr: "La personne qui enseigne à l'école",
    },
    {
      english: "Alumno",
      french: "Élève",
      hintEn: "Una persona joven que va a la escuela para aprender",
      hintFr: "Une jeune personne qui va à l'école pour apprendre",
    },
    {
      english: "Clase",
      french: "Classe",
      hintEn: "La sala donde los alumnos estudian",
      hintFr: "La salle où les élèves étudient",
    },
    {
      english: "Mochila",
      french: "Cartable",
      hintEn: "Un bolso que llevas a la espalda con tus libros",
      hintFr: "Un sac que tu portes sur le dos avec tes livres",
    },
    {
      english: "Regla",
      french: "Règle",
      hintEn: "Un instrumento recto para medir o trazar líneas",
      hintFr: "Un instrument droit pour mesurer ou tracer des lignes",
    },
    {
      english: "Goma",
      french: "Gomme",
      hintEn: "Se usa para borrar lo que está escrito con lápiz",
      hintFr: "On l'utilise pour effacer ce qui est écrit au crayon",
    },
    {
      english: "Tijeras",
      french: "Ciseaux",
      hintEn: "Un instrumento con dos hojas para cortar papel",
      hintFr: "Un instrument avec deux lames pour couper le papier",
    },
  ],
  "Les vêtements": [
    {
      english: "Camisa",
      french: "Chemise",
      hintEn: "Una prenda con botones y cuello para la parte de arriba",
      hintFr: "Un vêtement avec des boutons et un col pour le haut du corps",
    },
    {
      english: "Pantalón",
      french: "Pantalon",
      hintEn: "Una prenda larga que cubre las dos piernas",
      hintFr: "Un vêtement long qui couvre les deux jambes",
    },
    {
      english: "Vestido",
      french: "Robe",
      hintEn: "Una prenda de una pieza que llevan a menudo las chicas",
      hintFr: "Un vêtement d'une seule pièce souvent porté par les filles",
    },
    {
      english: "Falda",
      french: "Jupe",
      hintEn: "Una prenda que cubre desde la cintura sin cubrir las piernas por separado",
      hintFr: "Un vêtement qui couvre à partir de la taille sans séparer les jambes",
    },
    {
      english: "Zapatos",
      french: "Chaussures",
      hintEn: "Lo que te pones en los pies para caminar fuera",
      hintFr: "Ce que tu mets aux pieds pour marcher dehors",
    },
    {
      english: "Sombrero",
      french: "Chapeau",
      hintEn: "Un accesorio que se pone en la cabeza",
      hintFr: "Un accessoire qu'on met sur la tête",
    },
    {
      english: "Abrigo",
      french: "Manteau",
      hintEn: "Una prenda larga y gruesa para el invierno",
      hintFr: "Un vêtement long et épais pour l'hiver",
    },
    {
      english: "Bufanda",
      french: "Écharpe",
      hintEn: "Una tira de tela que se lleva alrededor del cuello cuando hace frío",
      hintFr: "Une bande de tissu qu'on porte autour du cou quand il fait froid",
    },
    {
      english: "Calcetines",
      french: "Chaussettes",
      hintEn: "Se ponen en los pies, dentro de los zapatos",
      hintFr: "On les met aux pieds, à l'intérieur des chaussures",
    },
    {
      english: "Guantes",
      french: "Gants",
      hintEn: "Cubren las manos cuando hace frío",
      hintFr: "Ils couvrent les mains quand il fait froid",
    },
    {
      english: "Cinturón",
      french: "Ceinture",
      hintEn: "Una tira que se lleva alrededor de la cintura para sujetar el pantalón",
      hintFr: "Une bande qu'on porte autour de la taille pour tenir le pantalon",
    },
    {
      english: "Jersey",
      french: "Pull",
      hintEn: "Una prenda de punto que abriga en invierno",
      hintFr: "Un vêtement en tricot qui tient chaud en hiver",
    },
  ],
  "Le corps humain": [
    {
      english: "Cabeza",
      french: "Tête",
      hintEn: "La parte de arriba del cuerpo donde está el cerebro",
      hintFr: "La partie en haut du corps où se trouve le cerveau",
    },
    {
      english: "Mano",
      french: "Main",
      hintEn: "La parte del cuerpo al final del brazo, con cinco dedos",
      hintFr: "La partie du corps au bout du bras, avec cinq doigts",
    },
    {
      english: "Pie",
      french: "Pied",
      hintEn: "La parte del cuerpo al final de la pierna, para caminar",
      hintFr: "La partie du corps au bout de la jambe, pour marcher",
    },
    {
      english: "Ojo",
      french: "Oeil",
      hintEn: "El órgano del cuerpo que sirve para ver",
      hintFr: "L'organe du corps qui sert à voir",
    },
    {
      english: "Oreja",
      french: "Oreille",
      hintEn: "La parte del cuerpo que sirve para oír",
      hintFr: "La partie du corps qui sert à entendre",
    },
    {
      english: "Boca",
      french: "Bouche",
      hintEn: "La parte de la cara que sirve para hablar y comer",
      hintFr: "La partie du visage qui sert à parler et manger",
    },
    {
      english: "Nariz",
      french: "Nez",
      hintEn: "La parte de la cara que sirve para oler y respirar",
      hintFr: "La partie du visage qui sert à sentir et respirer",
    },
    {
      english: "Brazo",
      french: "Bras",
      hintEn: "La parte del cuerpo entre el hombro y la mano",
      hintFr: "La partie du corps entre l'épaule et la main",
    },
    {
      english: "Pierna",
      french: "Jambe",
      hintEn: "La parte del cuerpo que va de la cadera al pie",
      hintFr: "La partie du corps qui va de la hanche au pied",
    },
    {
      english: "Dedo",
      french: "Doigt",
      hintEn: "Tienes diez en las manos",
      hintFr: "Tu en as dix aux mains",
    },
    {
      english: "Rodilla",
      french: "Genou",
      hintEn: "La articulación en el medio de la pierna",
      hintFr: "L'articulation au milieu de la jambe",
    },
    {
      english: "Hombro",
      french: "Épaule",
      hintEn: "La parte del cuerpo entre el cuello y el brazo",
      hintFr: "La partie du corps entre le cou et le bras",
    },
  ],
  "La famille": [
    {
      english: "Madre",
      french: "Mère",
      hintEn: "La mujer que te dio la vida, tu mamá",
      hintFr: "La femme qui t'a donné la vie, ta maman",
    },
    {
      english: "Padre",
      french: "Père",
      hintEn: "El hombre que te dio la vida, tu papá",
      hintFr: "L'homme qui t'a donné la vie, ton papa",
    },
    {
      english: "Hermano",
      french: "Frère",
      hintEn: "Un chico que tiene los mismos padres que tú",
      hintFr: "Un garçon qui a les mêmes parents que toi",
    },
    {
      english: "Hermana",
      french: "Soeur",
      hintEn: "Una chica que tiene los mismos padres que tú",
      hintFr: "Une fille qui a les mêmes parents que toi",
    },
    {
      english: "Abuela",
      french: "Grand-mère",
      hintEn: "La madre de tu padre o de tu madre",
      hintFr: "La mère de ton père ou de ta mère",
    },
    {
      english: "Abuelo",
      french: "Grand-père",
      hintEn: "El padre de tu padre o de tu madre",
      hintFr: "Le père de ton père ou de ta mère",
    },
    {
      english: "Tío",
      french: "Oncle",
      hintEn: "El hermano de tu padre o de tu madre",
      hintFr: "Le frère de ton père ou de ta mère",
    },
    {
      english: "Tía",
      french: "Tante",
      hintEn: "La hermana de tu padre o de tu madre",
      hintFr: "La sœur de ton père ou de ta mère",
    },
    {
      english: "Primo",
      french: "Cousin",
      hintEn: "El hijo de tu tío o de tu tía (chico)",
      hintFr: "Le fils de ton oncle ou de ta tante (garçon)",
    },
    {
      english: "Prima",
      french: "Cousine",
      hintEn: "La hija de tu tío o de tu tía (chica)",
      hintFr: "La fille de ton oncle ou de ta tante (fille)",
    },
    {
      english: "Hijo",
      french: "Fils",
      hintEn: "Un niño en relación con sus padres (chico)",
      hintFr: "Un enfant par rapport à ses parents (garçon)",
    },
    {
      english: "Hija",
      french: "Fille",
      hintEn: "Una niña en relación con sus padres (chica)",
      hintFr: "Une enfant par rapport à ses parents (fille)",
    },
  ],
  "Les couleurs": [
    {
      english: "Rojo",
      french: "Rouge",
      hintEn: "El color de los tomates y las fresas",
      hintFr: "La couleur des tomates et des fraises",
    },
    {
      english: "Azul",
      french: "Bleu",
      hintEn: "El color del cielo y del mar",
      hintFr: "La couleur du ciel et de la mer",
    },
    {
      english: "Verde",
      french: "Vert",
      hintEn: "El color de la hierba y las hojas",
      hintFr: "La couleur de l'herbe et des feuilles",
    },
    {
      english: "Amarillo",
      french: "Jaune",
      hintEn: "El color del sol y de los plátanos",
      hintFr: "La couleur du soleil et des bananes",
    },
    {
      english: "Negro",
      french: "Noir",
      hintEn: "El color de la noche, la ausencia de luz",
      hintFr: "La couleur de la nuit, l'absence de lumière",
    },
    {
      english: "Blanco",
      french: "Blanc",
      hintEn: "El color de la nieve y de las nubes",
      hintFr: "La couleur de la neige et des nuages",
    },
    {
      english: "Naranja",
      french: "Orange",
      hintEn: "El color de la fruta que lleva el mismo nombre",
      hintFr: "La couleur du fruit qui porte le même nom",
    },
    {
      english: "Rosa",
      french: "Rose",
      hintEn: "Un color suave, mezcla de rojo y blanco",
      hintFr: "Une couleur douce, mélange de rouge et blanc",
    },
    {
      english: "Violeta",
      french: "Violet",
      hintEn: "Un color mezcla de rojo y azul",
      hintFr: "Une couleur mélange de rouge et bleu",
    },
    {
      english: "Marrón",
      french: "Marron",
      hintEn: "El color del chocolate y de la madera",
      hintFr: "La couleur du chocolat et du bois",
    },
    {
      english: "Gris",
      french: "Gris",
      hintEn: "Un color entre blanco y negro",
      hintFr: "Une couleur entre le blanc et le noir",
    },
    {
      english: "Dorado",
      french: "Doré",
      hintEn: "El color del oro, brillante y cálido",
      hintFr: "La couleur de l'or, brillante et chaude",
    },
  ],
  "Les fruits": [
    {
      english: "Fresa",
      french: "Fraise",
      hintEn: "Una fruta pequeña, roja y dulce con puntitos",
      hintFr: "Un petit fruit rouge et sucré avec des petits points",
    },
    {
      english: "Plátano",
      french: "Banane",
      hintEn: "Una fruta larga y amarilla que se pela",
      hintFr: "Un fruit long et jaune qu'on épluche",
    },
    {
      english: "Naranja",
      french: "Orange",
      hintEn: "Una fruta redonda de color naranja con mucho jugo",
      hintFr: "Un fruit rond de couleur orange avec beaucoup de jus",
    },
    {
      english: "Uva",
      french: "Raisin",
      hintEn: "Pequeñas frutas que crecen en racimos",
      hintFr: "De petits fruits qui poussent en grappes",
    },
    {
      english: "Cereza",
      french: "Cerise",
      hintEn: "Una fruta pequeña y roja con un hueso dentro",
      hintFr: "Un petit fruit rouge avec un noyau à l'intérieur",
    },
    {
      english: "Melocotón",
      french: "Pêche",
      hintEn: "Una fruta redonda con piel aterciopelada y un hueso",
      hintFr: "Un fruit rond avec une peau veloutée et un noyau",
    },
    {
      english: "Pera",
      french: "Poire",
      hintEn: "Una fruta con forma de campana, verde o amarilla",
      hintFr: "Un fruit en forme de cloche, vert ou jaune",
    },
    {
      english: "Piña",
      french: "Ananas",
      hintEn: "Una fruta tropical grande con corona de hojas",
      hintFr: "Un gros fruit tropical avec une couronne de feuilles",
    },
    {
      english: "Limón",
      french: "Citron",
      hintEn: "Una fruta amarilla y ácida",
      hintFr: "Un fruit jaune et acide",
    },
    {
      english: "Sandía",
      french: "Pastèque",
      hintEn: "Una fruta muy grande, verde por fuera y roja por dentro",
      hintFr: "Un très gros fruit, vert dehors et rouge dedans",
    },
    {
      english: "Mango",
      french: "Mangue",
      hintEn: "Una fruta tropical dulce de color naranja",
      hintFr: "Un fruit tropical sucré de couleur orange",
    },
    {
      english: "Kiwi",
      french: "Kiwi",
      hintEn: "Una fruta pequeña marrón por fuera y verde por dentro",
      hintFr: "Un petit fruit marron dehors et vert dedans",
    },
  ],
  "Les légumes": [
    {
      english: "Zanahoria",
      french: "Carotte",
      hintEn: "Una verdura larga y naranja que crece bajo tierra",
      hintFr: "Un légume long et orange qui pousse sous terre",
    },
    {
      english: "Tomate",
      french: "Tomate",
      hintEn: "Un fruto rojo y redondo que se usa en ensaladas",
      hintFr: "Un fruit rouge et rond qu'on met dans les salades",
    },
    {
      english: "Patata",
      french: "Pomme de terre",
      hintEn: "Un tubérculo que se puede freír, asar o hervir",
      hintFr: "Un tubercule qu'on peut frire, rôtir ou faire bouillir",
    },
    {
      english: "Cebolla",
      french: "Oignon",
      hintEn: "Una verdura redonda que te hace llorar al cortarla",
      hintFr: "Un légume rond qui te fait pleurer quand tu le coupes",
    },
    {
      english: "Calabacín",
      french: "Courgette",
      hintEn: "Una verdura larga y verde, parecida a un pepino",
      hintFr: "Un légume long et vert, qui ressemble à un concombre",
    },
    {
      english: "Pimiento",
      french: "Poivron",
      hintEn: "Una verdura que puede ser roja, verde o amarilla",
      hintFr: "Un légume qui peut être rouge, vert ou jaune",
    },
    {
      english: "Judía",
      french: "Haricot",
      hintEn: "Una verdura alargada y verde que crece en vaina",
      hintFr: "Un légume allongé et vert qui pousse dans une cosse",
    },
    {
      english: "Brócoli",
      french: "Brocoli",
      hintEn: "Una verdura verde que parece un arbolito",
      hintFr: "Un légume vert qui ressemble à un petit arbre",
    },
    {
      english: "Espinaca",
      french: "Épinard",
      hintEn: "Una verdura de hojas verdes, la favorita de Popeye",
      hintFr: "Un légume à feuilles vertes, le préféré de Popeye",
    },
    {
      english: "Col",
      french: "Chou",
      hintEn: "Una verdura grande y redonda con muchas hojas",
      hintFr: "Un gros légume rond avec beaucoup de feuilles",
    },
    {
      english: "Pepino",
      french: "Concombre",
      hintEn: "Una verdura larga, verde y fresca para las ensaladas",
      hintFr: "Un légume long, vert et frais pour les salades",
    },
    {
      english: "Maíz",
      french: "Maïs",
      hintEn: "Una planta con granos amarillos en una mazorca",
      hintFr: "Une plante avec des grains jaunes sur un épi",
    },
  ],
  "Les sports": [
    {
      english: "Fútbol",
      french: "Football",
      hintEn: "Un deporte con un balón redondo y porterías",
      hintFr: "Un sport avec un ballon rond et des buts",
    },
    {
      english: "Tenis",
      french: "Tennis",
      hintEn: "Un deporte con raqueta y pelota en una pista con red",
      hintFr: "Un sport avec une raquette et une balle sur un terrain avec un filet",
    },
    {
      english: "Natación",
      french: "Natation",
      hintEn: "Un deporte que se practica en el agua, en una piscina",
      hintFr: "Un sport qui se pratique dans l'eau, dans une piscine",
    },
    {
      english: "Baloncesto",
      french: "Basket",
      hintEn: "Un deporte donde se lanza un balón a una canasta alta",
      hintFr: "Un sport où on lance un ballon dans un panier en hauteur",
    },
    {
      english: "Ciclismo",
      french: "Vélo",
      hintEn: "Un deporte que se practica sobre dos ruedas pedaleando",
      hintFr: "Un sport qui se pratique sur deux roues en pédalant",
    },
    {
      english: "Carrera",
      french: "Course",
      hintEn: "Un deporte donde corres lo más rápido posible",
      hintFr: "Un sport où tu cours le plus vite possible",
    },
    {
      english: "Gimnasia",
      french: "Gymnastique",
      hintEn: "Un deporte con acrobacias, saltos y equilibrio",
      hintFr: "Un sport avec des acrobaties, des sauts et de l'équilibre",
    },
    {
      english: "Esquí",
      french: "Ski",
      hintEn: "Un deporte de invierno que se practica deslizándose sobre la nieve",
      hintFr: "Un sport d'hiver qui se pratique en glissant sur la neige",
    },
    {
      english: "Baile",
      french: "Danse",
      hintEn: "Un arte donde mueves el cuerpo al ritmo de la música",
      hintFr: "Un art où tu bouges ton corps au rythme de la musique",
    },
    {
      english: "Judo",
      french: "Judo",
      hintEn: "Un arte marcial japonés donde se hacen llaves y proyecciones",
      hintFr: "Un art martial japonais avec des prises et des projections",
    },
    {
      english: "Esgrima",
      french: "Escrime",
      hintEn: "Un deporte de combate con una espada larga y fina",
      hintFr: "Un sport de combat avec une épée longue et fine",
    },
    {
      english: "Vela",
      french: "Voile",
      hintEn: "Un deporte náutico donde navegas con el viento",
      hintFr: "Un sport nautique où tu navigues avec le vent",
    },
  ],
  "Les métiers": [
    {
      english: "Médico",
      french: "Médecin",
      hintEn: "Una persona que cura a los enfermos",
      hintFr: "Une personne qui soigne les malades",
    },
    {
      english: "Panadero",
      french: "Boulanger",
      hintEn: "Una persona que hace pan y bollería",
      hintFr: "Une personne qui fait du pain et des viennoiseries",
    },
    {
      english: "Bombero",
      french: "Pompier",
      hintEn: "Una persona que apaga los incendios y hace rescates",
      hintFr: "Une personne qui éteint les incendies et fait des sauvetages",
    },
    {
      english: "Policía",
      french: "Policier",
      hintEn: "Una persona que mantiene el orden y la seguridad",
      hintFr: "Une personne qui maintient l'ordre et la sécurité",
    },
    {
      english: "Profesor",
      french: "Professeur",
      hintEn: "Una persona que enseña en la escuela o la universidad",
      hintFr: "Une personne qui enseigne à l'école ou à l'université",
    },
    {
      english: "Enfermero",
      french: "Infirmier",
      hintEn: "Una persona que cuida a los pacientes en el hospital",
      hintFr: "Une personne qui s'occupe des patients à l'hôpital",
    },
    {
      english: "Cocinero",
      french: "Cuisinier",
      hintEn: "Una persona que prepara platos y comidas",
      hintFr: "Une personne qui prépare des plats et des repas",
    },
    {
      english: "Piloto",
      french: "Pilote",
      hintEn: "Una persona que conduce aviones",
      hintFr: "Une personne qui conduit des avions",
    },
    {
      english: "Agricultor",
      french: "Agriculteur",
      hintEn: "Una persona que cultiva la tierra y cría animales",
      hintFr: "Une personne qui cultive la terre et élève des animaux",
    },
    {
      english: "Dentista",
      french: "Dentiste",
      hintEn: "Una persona que cuida tus dientes",
      hintFr: "Une personne qui soigne tes dents",
    },
    {
      english: "Peluquero",
      french: "Coiffeur",
      hintEn: "Una persona que corta y peina el pelo",
      hintFr: "Une personne qui coupe et coiffe les cheveux",
    },
    {
      english: "Cartero",
      french: "Facteur",
      hintEn: "Una persona que reparte las cartas y los paquetes",
      hintFr: "Une personne qui distribue le courrier et les colis",
    },
  ],
  "Les transports": [
    {
      english: "Coche",
      french: "Voiture",
      hintEn: "Un vehículo con cuatro ruedas y un motor",
      hintFr: "Un véhicule avec quatre roues et un moteur",
    },
    {
      english: "Autobús",
      french: "Bus",
      hintEn: "Un vehículo grande que transporta muchas personas en la ciudad",
      hintFr: "Un grand véhicule qui transporte beaucoup de personnes en ville",
    },
    {
      english: "Tren",
      french: "Train",
      hintEn: "Un vehículo largo que circula por las vías",
      hintFr: "Un long véhicule qui roule sur des rails",
    },
    {
      english: "Avión",
      french: "Avion",
      hintEn: "Un vehículo con alas que vuela por el cielo",
      hintFr: "Un véhicule avec des ailes qui vole dans le ciel",
    },
    {
      english: "Bicicleta",
      french: "Vélo",
      hintEn: "Un vehículo con dos ruedas que se mueve pedaleando",
      hintFr: "Un véhicule à deux roues qu'on fait avancer en pédalant",
    },
    {
      english: "Barco",
      french: "Bateau",
      hintEn: "Un vehículo que navega por el agua",
      hintFr: "Un véhicule qui navigue sur l'eau",
    },
    {
      english: "Metro",
      french: "Métro",
      hintEn: "Un tren que circula bajo tierra en la ciudad",
      hintFr: "Un train qui circule sous terre en ville",
    },
    {
      english: "Moto",
      french: "Moto",
      hintEn: "Un vehículo con dos ruedas y un motor potente",
      hintFr: "Un véhicule à deux roues avec un moteur puissant",
    },
    {
      english: "Helicóptero",
      french: "Hélicoptère",
      hintEn: "Un aparato volador con una gran hélice encima",
      hintFr: "Un appareil volant avec une grande hélice au-dessus",
    },
    {
      english: "Tranvía",
      french: "Tramway",
      hintEn: "Un vehículo sobre raíles que circula por la ciudad",
      hintFr: "Un véhicule sur rails qui circule en ville",
    },
    {
      english: "Camión",
      french: "Camion",
      hintEn: "Un vehículo grande para transportar mercancías",
      hintFr: "Un grand véhicule pour transporter des marchandises",
    },
    {
      english: "Taxi",
      french: "Taxi",
      hintEn: "Un coche con conductor que te lleva a donde quieras, pagando",
      hintFr: "Une voiture avec chauffeur qui t'emmène où tu veux, en payant",
    },
  ],
  "La ville": [
    {
      english: "Calle",
      french: "Rue",
      hintEn: "Un camino en la ciudad donde pasan los coches y la gente",
      hintFr: "Un chemin en ville où passent les voitures et les gens",
    },
    {
      english: "Tienda",
      french: "Magasin",
      hintEn: "Un lugar donde compras cosas",
      hintFr: "Un endroit où tu achètes des choses",
    },
    {
      english: "Hospital",
      french: "Hôpital",
      hintEn: "Un edificio grande donde curan a los enfermos",
      hintFr: "Un grand bâtiment où on soigne les malades",
    },
    {
      english: "Parque",
      french: "Parc",
      hintEn: "Un espacio verde en la ciudad con árboles y juegos",
      hintFr: "Un espace vert en ville avec des arbres et des jeux",
    },
    {
      english: "Iglesia",
      french: "Église",
      hintEn: "Un edificio religioso con una torre y campanas",
      hintFr: "Un bâtiment religieux avec une tour et des cloches",
    },
    {
      english: "Biblioteca",
      french: "Bibliothèque",
      hintEn: "Un lugar con muchos libros que puedes leer o llevar prestados",
      hintFr: "Un endroit avec beaucoup de livres que tu peux lire ou emprunter",
    },
    {
      english: "Museo",
      french: "Musée",
      hintEn: "Un lugar donde se muestran obras de arte o cosas antiguas",
      hintFr: "Un endroit où on montre des œuvres d'art ou des objets anciens",
    },
    {
      english: "Farmacia",
      french: "Pharmacie",
      hintEn: "Una tienda donde compras medicamentos",
      hintFr: "Un magasin où tu achètes des médicaments",
    },
    {
      english: "Panadería",
      french: "Boulangerie",
      hintEn: "Una tienda donde se vende pan y bollería",
      hintFr: "Un magasin où on vend du pain et des viennoiseries",
    },
    {
      english: "Estación",
      french: "Gare",
      hintEn: "El lugar donde coges el tren",
      hintFr: "L'endroit où tu prends le train",
    },
    {
      english: "Puente",
      french: "Pont",
      hintEn: "Una construcción que permite cruzar un río o una carretera",
      hintFr: "Une construction qui permet de traverser une rivière ou une route",
    },
    {
      english: "Plaza",
      french: "Place",
      hintEn: "Un espacio abierto en la ciudad donde la gente se encuentra",
      hintFr: "Un espace ouvert en ville où les gens se retrouvent",
    },
  ],
  "Les émotions": [
    {
      english: "Contento",
      french: "Content",
      hintEn: "Cuando te sientes bien y sonríes",
      hintFr: "Quand tu te sens bien et que tu souris",
    },
    {
      english: "Triste",
      french: "Triste",
      hintEn: "Cuando no te sientes bien y quieres llorar",
      hintFr: "Quand tu ne te sens pas bien et que tu veux pleurer",
    },
    {
      english: "Enfadado",
      french: "En colère",
      hintEn: "Cuando algo te molesta mucho y quieres gritar",
      hintFr: "Quand quelque chose te dérange beaucoup et que tu veux crier",
    },
    {
      english: "Sorprendido",
      french: "Surpris",
      hintEn: "Cuando algo inesperado pasa y abres mucho los ojos",
      hintFr: "Quand quelque chose d'inattendu arrive et que tu ouvres grand les yeux",
    },
    {
      english: "Cansado",
      french: "Fatigué",
      hintEn: "Cuando tu cuerpo necesita descansar o dormir",
      hintFr: "Quand ton corps a besoin de se reposer ou dormir",
    },
    {
      english: "Asustado",
      french: "Effrayé",
      hintEn: "Cuando tienes miedo de algo",
      hintFr: "Quand tu as peur de quelque chose",
    },
    {
      english: "Orgulloso",
      french: "Fier",
      hintEn: "Cuando estás contento de ti mismo por algo que has logrado",
      hintFr: "Quand tu es content de toi pour quelque chose que tu as réussi",
    },
    {
      english: "Celoso",
      french: "Jaloux",
      hintEn: "Cuando quieres lo que otra persona tiene",
      hintFr: "Quand tu veux ce qu'une autre personne a",
    },
    {
      english: "Tímido",
      french: "Timide",
      hintEn: "Cuando te cuesta hablar con personas que no conoces",
      hintFr: "Quand tu as du mal à parler aux gens que tu ne connais pas",
    },
    {
      english: "Aburrido",
      french: "Ennuyé",
      hintEn: "Cuando no tienes nada interesante que hacer",
      hintFr: "Quand tu n'as rien d'intéressant à faire",
    },
    {
      english: "Enamorado",
      french: "Amoureux",
      hintEn: "Cuando sientes amor por alguien",
      hintFr: "Quand tu ressens de l'amour pour quelqu'un",
    },
    {
      english: "Nervioso",
      french: "Nerveux",
      hintEn: "Cuando te sientes inquieto antes de algo importante",
      hintFr: "Quand tu te sens agité avant quelque chose d'important",
    },
  ],
  "La météo": [
    {
      english: "Sol",
      french: "Soleil",
      hintEn: "La estrella que brilla durante el día y da calor",
      hintFr: "L'étoile qui brille le jour et donne de la chaleur",
    },
    {
      english: "Lluvia",
      french: "Pluie",
      hintEn: "Gotas de agua que caen de las nubes",
      hintFr: "Des gouttes d'eau qui tombent des nuages",
    },
    {
      english: "Nieve",
      french: "Neige",
      hintEn: "Copos blancos y fríos que caen del cielo en invierno",
      hintFr: "Des flocons blancs et froids qui tombent du ciel en hiver",
    },
    {
      english: "Viento",
      french: "Vent",
      hintEn: "El aire que se mueve con fuerza",
      hintFr: "L'air qui se déplace avec force",
    },
    {
      english: "Tormenta",
      french: "Orage",
      hintEn: "Mal tiempo con truenos, relámpagos y lluvia fuerte",
      hintFr: "Mauvais temps avec du tonnerre, des éclairs et de la forte pluie",
    },
    {
      english: "Nube",
      french: "Nuage",
      hintEn: "Una masa blanca o gris que flota en el cielo",
      hintFr: "Une masse blanche ou grise qui flotte dans le ciel",
    },
    {
      english: "Niebla",
      french: "Brouillard",
      hintEn: "Una nube baja que impide ver bien",
      hintFr: "Un nuage bas qui empêche de bien voir",
    },
    {
      english: "Arcoíris",
      french: "Arc-en-ciel",
      hintEn: "Un arco de colores que aparece en el cielo después de la lluvia",
      hintFr: "Un arc de couleurs qui apparaît dans le ciel après la pluie",
    },
    {
      english: "Granizo",
      french: "Grêle",
      hintEn: "Bolitas de hielo que caen del cielo durante una tormenta",
      hintFr: "Des petites boules de glace qui tombent du ciel pendant un orage",
    },
    {
      english: "Tempestad",
      french: "Tempête",
      hintEn: "Un viento muy fuerte y violento con lluvia",
      hintFr: "Un vent très fort et violent avec de la pluie",
    },
    {
      english: "Relámpago",
      french: "Éclair",
      hintEn: "Una luz brillante en el cielo durante una tormenta",
      hintFr: "Une lumière brillante dans le ciel pendant un orage",
    },
    {
      english: "Helada",
      french: "Gel",
      hintEn: "Cuando hace tanto frío que el agua se congela",
      hintFr: "Quand il fait tellement froid que l'eau gèle",
    },
  ],
  "La musique": [
    {
      english: "Guitarra",
      french: "Guitare",
      hintEn: "Un instrumento con cuerdas que se toca con los dedos",
      hintFr: "Un instrument à cordes qu'on joue avec les doigts",
    },
    {
      english: "Piano",
      french: "Piano",
      hintEn: "Un instrumento grande con teclas blancas y negras",
      hintFr: "Un grand instrument avec des touches blanches et noires",
    },
    {
      english: "Violín",
      french: "Violon",
      hintEn: "Un instrumento de cuerdas que se toca con un arco",
      hintFr: "Un instrument à cordes qu'on joue avec un archet",
    },
    {
      english: "Batería",
      french: "Batterie",
      hintEn: "Un conjunto de tambores y platillos que se golpean con baquetas",
      hintFr: "Un ensemble de tambours et cymbales qu'on frappe avec des baguettes",
    },
    {
      english: "Flauta",
      french: "Flûte",
      hintEn: "Un instrumento largo de viento en el que soplas",
      hintFr: "Un instrument long à vent dans lequel tu souffles",
    },
    {
      english: "Trompeta",
      french: "Trompette",
      hintEn: "Un instrumento de viento de metal con un sonido potente",
      hintFr: "Un instrument à vent en métal avec un son puissant",
    },
    {
      english: "Canción",
      french: "Chanson",
      hintEn: "Una pieza musical con letra que se canta",
      hintFr: "Un morceau de musique avec des paroles qu'on chante",
    },
    {
      english: "Melodía",
      french: "Mélodie",
      hintEn: "Una serie de notas musicales agradables al oído",
      hintFr: "Une suite de notes musicales agréables à l'oreille",
    },
    {
      english: "Ritmo",
      french: "Rythme",
      hintEn: "La cadencia regular de la música que marca el tiempo",
      hintFr: "La cadence régulière de la musique qui marque le temps",
    },
    {
      english: "Concierto",
      french: "Concert",
      hintEn: "Un espectáculo donde los músicos tocan en directo",
      hintFr: "Un spectacle où les musiciens jouent en direct",
    },
    {
      english: "Cantante",
      french: "Chanteur",
      hintEn: "Una persona que canta canciones",
      hintFr: "Une personne qui chante des chansons",
    },
    {
      english: "Orquesta",
      french: "Orchestre",
      hintEn: "Un grupo grande de músicos que tocan juntos",
      hintFr: "Un grand groupe de musiciens qui jouent ensemble",
    },
  ],
  "Les insectes": [
    {
      english: "Abeja",
      french: "Abeille",
      hintEn: "Un insecto amarillo y negro que hace miel",
      hintFr: "Un insecte jaune et noir qui fait du miel",
    },
    {
      english: "Mariposa",
      french: "Papillon",
      hintEn: "Un insecto con alas grandes y coloridas",
      hintFr: "Un insecte avec de grandes ailes colorées",
    },
    {
      english: "Hormiga",
      french: "Fourmi",
      hintEn: "Un insecto muy pequeño que vive en colonias y trabaja mucho",
      hintFr: "Un tout petit insecte qui vit en colonies et travaille beaucoup",
    },
    {
      english: "Mariquita",
      french: "Coccinelle",
      hintEn: "Un pequeño insecto rojo con puntos negros",
      hintFr: "Un petit insecte rouge avec des points noirs",
    },
    {
      english: "Mosca",
      french: "Mouche",
      hintEn: "Un insecto que vuela y molesta mucho en verano",
      hintFr: "Un insecte qui vole et qui embête beaucoup en été",
    },
    {
      english: "Mosquito",
      french: "Moustique",
      hintEn: "Un insecto que pica y produce picazón",
      hintFr: "Un insecte qui pique et ça démange",
    },
    {
      english: "Araña",
      french: "Araignée",
      hintEn: "Un animal con ocho patas que teje telas",
      hintFr: "Un animal avec huit pattes qui tisse des toiles",
    },
    {
      english: "Saltamontes",
      french: "Sauterelle",
      hintEn: "Un insecto verde que salta muy alto en la hierba",
      hintFr: "Un insecte vert qui saute très haut dans l'herbe",
    },
    {
      english: "Libélula",
      french: "Libellule",
      hintEn: "Un insecto con alas transparentes que vuela cerca del agua",
      hintFr: "Un insecte avec des ailes transparentes qui vole près de l'eau",
    },
    {
      english: "Escarabajo",
      french: "Scarabée",
      hintEn: "Un insecto con un caparazón duro y brillante",
      hintFr: "Un insecte avec une carapace dure et brillante",
    },
    {
      english: "Avispa",
      french: "Guêpe",
      hintEn: "Un insecto amarillo y negro que pica, parecido a la abeja",
      hintFr: "Un insecte jaune et noir qui pique, ressemble à l'abeille",
    },
    {
      english: "Oruga",
      french: "Chenille",
      hintEn: "Una larva que se transforma en mariposa",
      hintFr: "Une larve qui se transforme en papillon",
    },
  ],
  "Les boissons": [
    {
      english: "Agua",
      french: "Eau",
      hintEn: "Un líquido transparente esencial para la vida",
      hintFr: "Un liquide transparent essentiel à la vie",
    },
    {
      english: "Zumo de fruta",
      french: "Jus de fruit",
      hintEn: "Una bebida hecha con el líquido de las frutas",
      hintFr: "Une boisson faite avec le liquide des fruits",
    },
    {
      english: "Leche",
      french: "Lait",
      hintEn: "Una bebida blanca que viene de la vaca",
      hintFr: "Une boisson blanche qui vient de la vache",
    },
    {
      english: "Té",
      french: "Thé",
      hintEn: "Una bebida caliente hecha con hojas secas y agua",
      hintFr: "Une boisson chaude faite avec des feuilles séchées et de l'eau",
    },
    {
      english: "Café",
      french: "Café",
      hintEn: "Una bebida caliente y oscura que los adultos beben por la mañana",
      hintFr: "Une boisson chaude et sombre que les adultes boivent le matin",
    },
    {
      english: "Chocolate caliente",
      french: "Chocolat chaud",
      hintEn: "Una bebida caliente y dulce hecha con cacao y leche",
      hintFr: "Une boisson chaude et sucrée faite avec du cacao et du lait",
    },
    {
      english: "Limonada",
      french: "Limonade",
      hintEn: "Una bebida con gas y sabor a limón",
      hintFr: "Une boisson gazeuse au goût de citron",
    },
    {
      english: "Refresco",
      french: "Soda",
      hintEn: "Una bebida dulce con burbujas",
      hintFr: "Une boisson sucrée avec des bulles",
    },
    {
      english: "Batido",
      french: "Smoothie",
      hintEn: "Una bebida espesa hecha con frutas frescas trituradas",
      hintFr: "Une boisson épaisse faite avec des fruits frais mixés",
    },
    {
      english: "Jarabe",
      french: "Sirop",
      hintEn: "Un líquido dulce y concentrado que se mezcla con agua",
      hintFr: "Un liquide sucré et concentré qu'on mélange avec de l'eau",
    },
    {
      english: "Infusión",
      french: "Tisane",
      hintEn: "Una bebida caliente hecha con hierbas o flores",
      hintFr: "Une boisson chaude faite avec des herbes ou des fleurs",
    },
    {
      english: "Batido de leche",
      french: "Milkshake",
      hintEn: "Una bebida fría y cremosa hecha con leche y helado",
      hintFr: "Une boisson froide et crémeuse faite avec du lait et de la glace",
    },
  ],
  "Les desserts": [
    {
      english: "Pastel",
      french: "Gâteau",
      hintEn: "Un postre dulce que se come en los cumpleaños",
      hintFr: "Un dessert sucré qu'on mange aux anniversaires",
    },
    {
      english: "Tarta",
      french: "Tarte",
      hintEn: "Un postre con masa y relleno de frutas o crema",
      hintFr: "Un dessert avec une pâte et une garniture de fruits ou de crème",
    },
    {
      english: "Helado",
      french: "Glace",
      hintEn: "Un postre frío y cremoso con muchos sabores",
      hintFr: "Un dessert froid et crémeux avec plein de parfums",
    },
    {
      english: "Crepe",
      french: "Crêpe",
      hintEn: "Una tortita fina que se rellena con dulce o salado",
      hintFr: "Une galette fine qu'on garnit avec du sucré ou du salé",
    },
    {
      english: "Mousse de chocolate",
      french: "Mousse au chocolat",
      hintEn: "Un postre suave y aireado hecho con cacao",
      hintFr: "Un dessert léger et aéré fait avec du cacao",
    },
    {
      english: "Macarrón",
      french: "Macaron",
      hintEn: "Un dulce francés redondo y colorido con relleno",
      hintFr: "Un petit gâteau français rond et coloré avec une garniture",
    },
    {
      english: "Relámpago",
      french: "Éclair",
      hintEn: "Un pastel alargado relleno de crema con glaseado encima",
      hintFr: "Un gâteau allongé rempli de crème avec du glaçage dessus",
    },
    {
      english: "Buñuelo",
      french: "Beignet",
      hintEn: "Un dulce frito, redondo, a veces con un agujero",
      hintFr: "Une pâtisserie frite, ronde, parfois avec un trou",
    },
    {
      english: "Flan",
      french: "Flan",
      hintEn: "Un postre cremoso y firme hecho con huevos y leche",
      hintFr: "Un dessert crémeux et ferme fait avec des œufs et du lait",
    },
    {
      english: "Brioche",
      french: "Brioche",
      hintEn: "Un pan dulce y esponjoso hecho con mantequilla y huevos",
      hintFr: "Un pain sucré et moelleux fait avec du beurre et des œufs",
    },
    {
      english: "Compota",
      french: "Compote",
      hintEn: "Frutas cocidas y trituradas, como puré de frutas",
      hintFr: "Des fruits cuits et écrasés, comme une purée de fruits",
    },
    {
      english: "Merengue",
      french: "Meringue",
      hintEn: "Un dulce ligero y crujiente hecho con claras de huevo y azúcar",
      hintFr: "Un gâteau léger et croquant fait avec des blancs d'œufs et du sucre",
    },
  ],
  "Les ustensiles": [
    {
      english: "Tenedor",
      french: "Fourchette",
      hintEn: "Un cubierto con dientes para pinchar la comida",
      hintFr: "Un couvert avec des dents pour piquer la nourriture",
    },
    {
      english: "Cuchillo",
      french: "Couteau",
      hintEn: "Un cubierto con hoja afilada para cortar",
      hintFr: "Un couvert avec une lame tranchante pour couper",
    },
    {
      english: "Cuchara",
      french: "Cuillère",
      hintEn: "Un cubierto con parte cóncava para la sopa",
      hintFr: "Un couvert avec une partie creuse pour la soupe",
    },
    {
      english: "Plato",
      french: "Assiette",
      hintEn: "Un objeto redondo y plano donde se pone la comida",
      hintFr: "Un objet rond et plat où on pose la nourriture",
    },
    {
      english: "Vaso",
      french: "Verre",
      hintEn: "Un recipiente transparente para beber",
      hintFr: "Un récipient transparent pour boire",
    },
    {
      english: "Cacerola",
      french: "Casserole",
      hintEn: "Un recipiente con un mango largo para cocinar en el fuego",
      hintFr: "Un récipient avec une longue poignée pour cuisiner sur le feu",
    },
    {
      english: "Sartén",
      french: "Poêle",
      hintEn: "Un recipiente plano para freír la comida",
      hintFr: "Un récipient plat pour faire frire la nourriture",
    },
    {
      english: "Bol",
      french: "Bol",
      hintEn: "Un recipiente hondo y redondo para cereales o sopa",
      hintFr: "Un récipient creux et rond pour les céréales ou la soupe",
    },
    {
      english: "Taza",
      french: "Tasse",
      hintEn: "Un recipiente pequeño con asa para bebidas calientes",
      hintFr: "Un petit récipient avec une anse pour les boissons chaudes",
    },
    {
      english: "Batidor",
      french: "Fouet",
      hintEn: "Un utensilio de cocina para mezclar y batir",
      hintFr: "Un ustensile de cuisine pour mélanger et fouetter",
    },
    {
      english: "Espátula",
      french: "Spatule",
      hintEn: "Un utensilio plano para dar la vuelta a la comida",
      hintFr: "Un ustensile plat pour retourner la nourriture",
    },
    {
      english: "Cucharón",
      french: "Louche",
      hintEn: "Una cuchara grande para servir la sopa",
      hintFr: "Une grande cuillère pour servir la soupe",
    },
  ],
  "Les meubles": [
    {
      english: "Sofá",
      french: "Canapé",
      hintEn: "Un asiento cómodo y largo donde caben varias personas",
      hintFr: "Un siège confortable et long où plusieurs personnes peuvent s'asseoir",
    },
    {
      english: "Armario",
      french: "Armoire",
      hintEn: "Un mueble grande con puertas para guardar la ropa",
      hintFr: "Un grand meuble avec des portes pour ranger les vêtements",
    },
    {
      english: "Escritorio",
      french: "Bureau",
      hintEn: "Un mueble con superficie plana para trabajar o estudiar",
      hintFr: "Un meuble avec une surface plate pour travailler ou étudier",
    },
    {
      english: "Estantería",
      french: "Étagère",
      hintEn: "Un mueble con estantes para poner libros u objetos",
      hintFr: "Un meuble avec des étagères pour poser des livres ou des objets",
    },
    {
      english: "Cómoda",
      french: "Commode",
      hintEn: "Un mueble con cajones para guardar cosas",
      hintFr: "Un meuble avec des tiroirs pour ranger des choses",
    },
    {
      english: "Mesa baja",
      french: "Table basse",
      hintEn: "Una mesa pequeña y baja que está delante del sofá",
      hintFr: "Une petite table basse qui est devant le canapé",
    },
    {
      english: "Sillón",
      french: "Fauteuil",
      hintEn: "Un asiento cómodo con brazos para una persona",
      hintFr: "Un siège confortable avec des accoudoirs pour une personne",
    },
    {
      english: "Biblioteca",
      french: "Bibliothèque",
      hintEn: "Un mueble grande con muchos estantes para libros",
      hintFr: "Un grand meuble avec beaucoup d'étagères pour les livres",
    },
    {
      english: "Espejo",
      french: "Miroir",
      hintEn: "Un objeto que refleja tu imagen",
      hintFr: "Un objet qui reflète ton image",
    },
    {
      english: "Lámpara",
      french: "Lampe",
      hintEn: "Un objeto que da luz en una habitación",
      hintFr: "Un objet qui donne de la lumière dans une pièce",
    },
    {
      english: "Alfombra",
      french: "Tapis",
      hintEn: "Una pieza de tela gruesa que se pone en el suelo",
      hintFr: "Un morceau de tissu épais qu'on pose sur le sol",
    },
    {
      english: "Cofre",
      french: "Coffre",
      hintEn: "Una caja grande con tapa para guardar cosas",
      hintFr: "Un grand coffre avec un couvercle pour ranger des choses",
    },
  ],
  "L'espace": [
    {
      english: "Planeta",
      french: "Planète",
      hintEn: "Un cuerpo celeste grande que gira alrededor de una estrella",
      hintFr: "Un grand corps céleste qui tourne autour d'une étoile",
    },
    {
      english: "Estrella",
      french: "Étoile",
      hintEn: "Un punto brillante en el cielo nocturno que produce luz",
      hintFr: "Un point brillant dans le ciel la nuit qui produit de la lumière",
    },
    {
      english: "Luna",
      french: "Lune",
      hintEn: "El satélite natural que gira alrededor de la Tierra",
      hintFr: "Le satellite naturel qui tourne autour de la Terre",
    },
    {
      english: "Cohete",
      french: "Fusée",
      hintEn: "Un vehículo espacial que despega con mucho fuego",
      hintFr: "Un véhicule spatial qui décolle avec beaucoup de feu",
    },
    {
      english: "Astronauta",
      french: "Astronaute",
      hintEn: "Una persona que viaja al espacio",
      hintFr: "Une personne qui voyage dans l'espace",
    },
    {
      english: "Galaxia",
      french: "Galaxie",
      hintEn: "Un enorme conjunto de estrellas, planetas y polvo cósmico",
      hintFr: "Un énorme ensemble d'étoiles, de planètes et de poussière cosmique",
    },
    {
      english: "Satélite",
      french: "Satellite",
      hintEn: "Un objeto que gira alrededor de un planeta",
      hintFr: "Un objet qui tourne autour d'une planète",
    },
    {
      english: "Cometa",
      french: "Comète",
      hintEn: "Un cuerpo celeste con una cola brillante",
      hintFr: "Un corps céleste avec une queue brillante",
    },
    {
      english: "Sol",
      french: "Soleil",
      hintEn: "La estrella del centro de nuestro sistema solar",
      hintFr: "L'étoile au centre de notre système solaire",
    },
    {
      english: "Telescopio",
      french: "Télescope",
      hintEn: "Un instrumento para observar las estrellas y los planetas",
      hintFr: "Un instrument pour observer les étoiles et les planètes",
    },
    {
      english: "Asteroide",
      french: "Astéroïde",
      hintEn: "Una roca que flota en el espacio alrededor del sol",
      hintFr: "Un rocher qui flotte dans l'espace autour du soleil",
    },
    {
      english: "Órbita",
      french: "Orbite",
      hintEn: "El camino circular que sigue un planeta o satélite",
      hintFr: "Le chemin circulaire que suit une planète ou un satellite",
    },
  ],
  "Les animaux marins": [
    {
      english: "Delfín",
      french: "Dauphin",
      hintEn: "Un mamífero marino muy inteligente que salta en el agua",
      hintFr: "Un mammifère marin très intelligent qui saute dans l'eau",
    },
    {
      english: "Ballena",
      french: "Baleine",
      hintEn: "El animal más grande del mundo que vive en el mar",
      hintFr: "Le plus grand animal du monde qui vit dans la mer",
    },
    {
      english: "Tiburón",
      french: "Requin",
      hintEn: "Un gran pez depredador con dientes afilados",
      hintFr: "Un grand poisson prédateur avec des dents pointues",
    },
    {
      english: "Pulpo",
      french: "Pieuvre",
      hintEn: "Un animal marino con ocho tentáculos",
      hintFr: "Un animal marin avec huit tentacules",
    },
    {
      english: "Tortuga marina",
      french: "Tortue de mer",
      hintEn: "Un reptil con caparazón que nada en el océano",
      hintFr: "Un reptile avec une carapace qui nage dans l'océan",
    },
    {
      english: "Cangrejo",
      french: "Crabe",
      hintEn: "Un animal con caparazón y pinzas que camina de lado",
      hintFr: "Un animal avec une carapace et des pinces qui marche de côté",
    },
    {
      english: "Caballito de mar",
      french: "Hippocampe",
      hintEn: "Un pez pequeño con forma de caballo",
      hintFr: "Un petit poisson en forme de cheval",
    },
    {
      english: "Medusa",
      french: "Méduse",
      hintEn: "Un animal marino transparente con tentáculos que pican",
      hintFr: "Un animal marin transparent avec des tentacules qui piquent",
    },
    {
      english: "Estrella de mar",
      french: "Étoile de mer",
      hintEn: "Un animal marino con cinco brazos en forma de estrella",
      hintFr: "Un animal marin avec cinq bras en forme d'étoile",
    },
    {
      english: "Foca",
      french: "Phoque",
      hintEn: "Un mamífero marino con pelaje que vive en las costas frías",
      hintFr: "Un mammifère marin avec de la fourrure qui vit sur les côtes froides",
    },
    {
      english: "Langosta",
      french: "Homard",
      hintEn: "Un crustáceo grande con pinzas que vive en el fondo del mar",
      hintFr: "Un grand crustacé avec des pinces qui vit au fond de la mer",
    },
    {
      english: "Concha",
      french: "Coquillage",
      hintEn: "La cubierta dura de un animal marino que se encuentra en la playa",
      hintFr: "L'enveloppe dure d'un animal marin qu'on trouve sur la plage",
    },
  ],
  "Les oiseaux": [
    {
      english: "Águila",
      french: "Aigle",
      hintEn: "Un ave grande y poderosa que caza con sus garras",
      hintFr: "Un grand oiseau puissant qui chasse avec ses serres",
    },
    {
      english: "Loro",
      french: "Perroquet",
      hintEn: "Un ave tropical y colorida que puede repetir palabras",
      hintFr: "Un oiseau tropical et coloré qui peut répéter des mots",
    },
    {
      english: "Búho",
      french: "Chouette",
      hintEn: "Un ave nocturna con grandes ojos que caza de noche",
      hintFr: "Un oiseau nocturne avec de grands yeux qui chasse la nuit",
    },
    {
      english: "Pingüino",
      french: "Pingouin",
      hintEn: "Un ave en blanco y negro que no vuela pero nada muy bien",
      hintFr: "Un oiseau noir et blanc qui ne vole pas mais nage très bien",
    },
    {
      english: "Flamenco",
      french: "Flamant rose",
      hintEn: "Un ave rosa con patas largas que vive cerca del agua",
      hintFr: "Un oiseau rose avec de longues pattes qui vit près de l'eau",
    },
    {
      english: "Gorrión",
      french: "Moineau",
      hintEn: "Un pájaro pequeño y marrón muy común en las ciudades",
      hintFr: "Un petit oiseau brun très commun dans les villes",
    },
    {
      english: "Paloma",
      french: "Pigeon",
      hintEn: "Un ave gris que se ve mucho en las ciudades y las plazas",
      hintFr: "Un oiseau gris qu'on voit beaucoup dans les villes et les places",
    },
    {
      english: "Cisne",
      french: "Cygne",
      hintEn: "Un ave blanca elegante con un cuello largo que vive en los lagos",
      hintFr: "Un oiseau blanc élégant avec un long cou qui vit sur les lacs",
    },
    {
      english: "Cuervo",
      french: "Corbeau",
      hintEn: "Un ave grande y negra con un canto ronco",
      hintFr: "Un grand oiseau noir avec un cri rauque",
    },
    {
      english: "Colibrí",
      french: "Colibri",
      hintEn: "Un pájaro muy pequeño que bate las alas muy rápido",
      hintFr: "Un tout petit oiseau qui bat des ailes très vite",
    },
    {
      english: "Garza",
      french: "Héron",
      hintEn: "Un ave grande con patas largas que pesca en el agua",
      hintFr: "Un grand oiseau avec de longues pattes qui pêche dans l'eau",
    },
    {
      english: "Halcón",
      french: "Faucon",
      hintEn: "Un ave rapaz muy rápida que caza en vuelo",
      hintFr: "Un rapace très rapide qui chasse en vol",
    },
  ],
  "La plage": [
    {
      english: "Arena",
      french: "Sable",
      hintEn: "Los granos finos que cubren la playa",
      hintFr: "Les grains fins qui recouvrent la plage",
    },
    {
      english: "Ola",
      french: "Vague",
      hintEn: "Una masa de agua que sube y baja en el mar",
      hintFr: "Une masse d'eau qui monte et descend dans la mer",
    },
    {
      english: "Sombrilla",
      french: "Parasol",
      hintEn: "Un objeto grande que da sombra en la playa",
      hintFr: "Un grand objet qui donne de l'ombre à la plage",
    },
    {
      english: "Concha",
      french: "Coquillage",
      hintEn: "Un objeto duro y bonito que encuentras en la arena",
      hintFr: "Un objet dur et joli que tu trouves dans le sable",
    },
    {
      english: "Toalla",
      french: "Serviette",
      hintEn: "Un trozo de tela para secarte después de bañarte",
      hintFr: "Un morceau de tissu pour te sécher après le bain",
    },
    {
      english: "Crema solar",
      french: "Crème solaire",
      hintEn: "Un producto que te protege la piel del sol",
      hintFr: "Un produit qui protège ta peau du soleil",
    },
    {
      english: "Castillo de arena",
      french: "Château de sable",
      hintEn: "Una construcción que haces con arena en la playa",
      hintFr: "Une construction que tu fais avec du sable à la plage",
    },
    {
      english: "Traje de baño",
      french: "Maillot de bain",
      hintEn: "La ropa que llevas para meterte en el agua",
      hintFr: "Le vêtement que tu portes pour aller dans l'eau",
    },
    {
      english: "Palmera",
      french: "Palmier",
      hintEn: "Un árbol tropical con un tronco alto y hojas grandes",
      hintFr: "Un arbre tropical avec un tronc haut et de grandes feuilles",
    },
    {
      english: "Flotador",
      french: "Bouée",
      hintEn: "Un objeto inflable que te ayuda a flotar en el agua",
      hintFr: "Un objet gonflable qui t'aide à flotter dans l'eau",
    },
    {
      english: "Chancla",
      french: "Tong",
      hintEn: "Un calzado abierto y ligero para la playa",
      hintFr: "Une chaussure ouverte et légère pour la plage",
    },
    {
      english: "Surf",
      french: "Surf",
      hintEn: "Un deporte donde te deslizas sobre las olas con una tabla",
      hintFr: "Un sport où tu glisses sur les vagues avec une planche",
    },
  ],
  "Les jouets": [
    {
      english: "Muñeca",
      french: "Poupée",
      hintEn: "Un juguete con forma de persona, a menudo de niña",
      hintFr: "Un jouet en forme de personne, souvent de petite fille",
    },
    {
      english: "Pelota",
      french: "Ballon",
      hintEn: "Un objeto redondo con el que juegas a lanzar y atrapar",
      hintFr: "Un objet rond avec lequel tu joues à lancer et attraper",
    },
    {
      english: "Rompecabezas",
      french: "Puzzle",
      hintEn: "Un juego de piezas que encajas para formar una imagen",
      hintFr: "Un jeu de pièces que tu assembles pour former une image",
    },
    {
      english: "Peluche",
      french: "Peluche",
      hintEn: "Un juguete suave en forma de animal",
      hintFr: "Un jouet tout doux en forme d'animal",
    },
    {
      english: "Coche en miniatura",
      french: "Voiture miniature",
      hintEn: "Un pequeño vehículo de juguete para hacer rodar",
      hintFr: "Un petit véhicule jouet qu'on fait rouler",
    },
    {
      english: "Peonza",
      french: "Toupie",
      hintEn: "Un juguete que gira sobre sí mismo",
      hintFr: "Un jouet qui tourne sur lui-même",
    },
    {
      english: "Cometa",
      french: "Cerf-volant",
      hintEn: "Un juguete que vuela en el aire atado a un hilo",
      hintFr: "Un jouet qui vole dans les airs attaché à un fil",
    },
    {
      english: "Canicas",
      french: "Billes",
      hintEn: "Pequeñas bolas de cristal o de colores para jugar",
      hintFr: "De petites boules en verre ou colorées pour jouer",
    },
    {
      english: "Robot",
      french: "Robot",
      hintEn: "Un juguete en forma de máquina que se mueve",
      hintFr: "Un jouet en forme de machine qui bouge",
    },
    {
      english: "Lego",
      french: "Lego",
      hintEn: "Pequeños bloques de plástico que encajas para construir",
      hintFr: "Des petits blocs en plastique qu'on emboîte pour construire",
    },
    {
      english: "Dominó",
      french: "Dominos",
      hintEn: "Fichas rectangulares con puntos para jugar",
      hintFr: "Des pièces rectangulaires avec des points pour jouer",
    },
    {
      english: "Yoyó",
      french: "Yo-yo",
      hintEn: "Un juguete con un disco que sube y baja por un hilo",
      hintFr: "Un jouet avec un disque qui monte et descend le long d'un fil",
    },
  ],
  "Le restaurant": [
    {
      english: "Menú",
      french: "Menu",
      hintEn: "La lista de platos que puedes elegir",
      hintFr: "La liste des plats que tu peux choisir",
    },
    {
      english: "Camarero",
      french: "Serveur",
      hintEn: "La persona que te atiende y trae los platos",
      hintFr: "La personne qui te sert et apporte les plats",
    },
    {
      english: "Cuenta",
      french: "Addition",
      hintEn: "El papel con el precio total que pagas al final",
      hintFr: "Le papier avec le prix total que tu paies à la fin",
    },
    {
      english: "Entrada",
      french: "Entrée",
      hintEn: "El primer plato pequeño antes del plato principal",
      hintFr: "Le premier petit plat avant le plat principal",
    },
    {
      english: "Plato principal",
      french: "Plat principal",
      hintEn: "El plato más grande y más importante de la comida",
      hintFr: "Le plat le plus grand et le plus important du repas",
    },
    {
      english: "Postre",
      french: "Dessert",
      hintEn: "El plato dulce que se come al final de la comida",
      hintFr: "Le plat sucré qu'on mange à la fin du repas",
    },
    {
      english: "Reserva",
      french: "Réservation",
      hintEn: "Cuando llamas antes para guardar una mesa",
      hintFr: "Quand tu appelles avant pour garder une table",
    },
    {
      english: "Propina",
      french: "Pourboire",
      hintEn: "El dinero extra que dejas para el camarero",
      hintFr: "L'argent supplémentaire que tu laisses pour le serveur",
    },
    {
      english: "Carta",
      french: "Carte",
      hintEn: "El documento con todos los platos y bebidas del restaurante",
      hintFr: "Le document avec tous les plats et boissons du restaurant",
    },
    {
      english: "Pedido",
      french: "Commande",
      hintEn: "Lo que eliges y pides al camarero",
      hintFr: "Ce que tu choisis et demandes au serveur",
    },
    {
      english: "Terraza",
      french: "Terrasse",
      hintEn: "La zona exterior del restaurante donde se come al aire libre",
      hintFr: "La zone extérieure du restaurant où on mange en plein air",
    },
    {
      english: "Chef",
      french: "Chef",
      hintEn: "El cocinero principal que dirige la cocina",
      hintFr: "Le cuisinier principal qui dirige la cuisine",
    },
  ],
  "Le camping": [
    {
      english: "Tienda de campaña",
      french: "Tente",
      hintEn: "Un refugio de tela donde duermes al aire libre",
      hintFr: "Un abri en toile où tu dors en plein air",
    },
    {
      english: "Saco de dormir",
      french: "Sac de couchage",
      hintEn: "Una bolsa acolchada para dormir dentro cuando acampas",
      hintFr: "Un sac rembourré pour dormir dedans quand tu campes",
    },
    {
      english: "Fogata",
      french: "Feu de camp",
      hintEn: "Un fuego que haces al aire libre para calentarte",
      hintFr: "Un feu que tu fais en plein air pour te réchauffer",
    },
    {
      english: "Linterna",
      french: "Lampe torche",
      hintEn: "Un objeto portátil que da luz en la oscuridad",
      hintFr: "Un objet portable qui donne de la lumière dans le noir",
    },
    {
      english: "Brújula",
      french: "Boussole",
      hintEn: "Un instrumento que indica el norte para orientarse",
      hintFr: "Un instrument qui indique le nord pour s'orienter",
    },
    {
      english: "Cantimplora",
      french: "Gourde",
      hintEn: "Un recipiente para llevar agua cuando vas de excursión",
      hintFr: "Un récipient pour transporter de l'eau en randonnée",
    },
    {
      english: "Mochila",
      french: "Sac à dos",
      hintEn: "Un bolso grande que llevas a la espalda para excursiones",
      hintFr: "Un grand sac que tu portes sur le dos pour les randonnées",
    },
    {
      english: "Hamaca",
      french: "Hamac",
      hintEn: "Una tela colgada entre dos árboles para descansar",
      hintFr: "Un tissu suspendu entre deux arbres pour se reposer",
    },
    {
      english: "Caña de pescar",
      french: "Canne à pêche",
      hintEn: "Un palo largo con un hilo para atrapar peces",
      hintFr: "Un long bâton avec un fil pour attraper des poissons",
    },
    {
      english: "Prismáticos",
      french: "Jumelles",
      hintEn: "Un instrumento con dos lentes para ver de lejos",
      hintFr: "Un instrument avec deux lentilles pour voir de loin",
    },
    {
      english: "Cerillas",
      french: "Allumettes",
      hintEn: "Pequeños palitos que se frotan para hacer fuego",
      hintFr: "Des petits bâtons qu'on frotte pour faire du feu",
    },
    {
      english: "Navaja",
      french: "Canif",
      hintEn: "Un cuchillo pequeño plegable muy útil en el campo",
      hintFr: "Un petit couteau pliant très utile en pleine nature",
    },
  ],
  "Les voyages": [
    {
      english: "Pasaporte",
      french: "Passeport",
      hintEn: "Un documento oficial necesario para viajar a otro país",
      hintFr: "Un document officiel nécessaire pour voyager dans un autre pays",
    },
    {
      english: "Maleta",
      french: "Valise",
      hintEn: "Un equipaje con ruedas donde metes tu ropa para viajar",
      hintFr: "Un bagage avec des roulettes où tu mets tes vêtements pour voyager",
    },
    {
      english: "Aeropuerto",
      french: "Aéroport",
      hintEn: "El lugar donde despegan y aterrizan los aviones",
      hintFr: "L'endroit où les avions décollent et atterrissent",
    },
    {
      english: "Hotel",
      french: "Hôtel",
      hintEn: "Un edificio donde pagas para dormir cuando viajas",
      hintFr: "Un bâtiment où tu paies pour dormir quand tu voyages",
    },
    {
      english: "Mapa",
      french: "Carte",
      hintEn: "Un dibujo que muestra las calles, los países o las rutas",
      hintFr: "Un dessin qui montre les rues, les pays ou les chemins",
    },
    {
      english: "Billete",
      french: "Billet",
      hintEn: "Un papel que compras para viajar en tren o avión",
      hintFr: "Un papier que tu achètes pour voyager en train ou en avion",
    },
    {
      english: "Aduana",
      french: "Douane",
      hintEn: "El control en la frontera cuando entras en un país",
      hintFr: "Le contrôle à la frontière quand tu entres dans un pays",
    },
    {
      english: "Guía",
      french: "Guide",
      hintEn: "Una persona o un libro que te ayuda a descubrir un lugar",
      hintFr: "Une personne ou un livre qui t'aide à découvrir un lieu",
    },
    {
      english: "Recuerdo",
      french: "Souvenir",
      hintEn: "Un objeto que compras para recordar un viaje",
      hintFr: "Un objet que tu achètes pour te rappeler d'un voyage",
    },
    {
      english: "Destino",
      french: "Destination",
      hintEn: "El lugar adonde quieres ir",
      hintFr: "L'endroit où tu veux aller",
    },
    {
      english: "Itinerario",
      french: "Itinéraire",
      hintEn: "El plan del camino o las etapas de un viaje",
      hintFr: "Le plan du chemin ou les étapes d'un voyage",
    },
    {
      english: "Excursión",
      french: "Excursion",
      hintEn: "Un paseo o visita organizada para descubrir un lugar",
      hintFr: "Une promenade ou visite organisée pour découvrir un lieu",
    },
  ],
  "La fête": [
    {
      english: "Globo",
      french: "Ballon",
      hintEn: "Un objeto inflable y colorido que decora las fiestas",
      hintFr: "Un objet gonflable et coloré qui décore les fêtes",
    },
    {
      english: "Pastel",
      french: "Gâteau",
      hintEn: "Un postre dulce que se come en las fiestas de cumpleaños",
      hintFr: "Un dessert sucré qu'on mange aux fêtes d'anniversaire",
    },
    {
      english: "Regalo",
      french: "Cadeau",
      hintEn: "Un objeto envuelto que das a alguien para hacerle feliz",
      hintFr: "Un objet emballé que tu donnes à quelqu'un pour lui faire plaisir",
    },
    {
      english: "Vela",
      french: "Bougie",
      hintEn: "Un objeto pequeño con llama que se pone en el pastel",
      hintFr: "Un petit objet avec une flamme qu'on met sur le gâteau",
    },
    {
      english: "Guirnalda",
      french: "Guirlande",
      hintEn: "Una decoración larga que se cuelga en las fiestas",
      hintFr: "Une décoration longue qu'on accroche aux fêtes",
    },
    {
      english: "Confeti",
      french: "Confetti",
      hintEn: "Pequeños trozos de papel de colores que se lanzan al aire",
      hintFr: "De petits morceaux de papier colorés qu'on lance en l'air",
    },
    {
      english: "Música",
      french: "Musique",
      hintEn: "Los sonidos y las canciones que escuchas para bailar",
      hintFr: "Les sons et les chansons que tu écoutes pour danser",
    },
    {
      english: "Invitación",
      french: "Invitation",
      hintEn: "Una tarjeta o mensaje para pedir a alguien que venga a la fiesta",
      hintFr: "Une carte ou un message pour demander à quelqu'un de venir à la fête",
    },
    {
      english: "Disfraz",
      french: "Déguisement",
      hintEn: "Una ropa especial para parecer otra persona o un personaje",
      hintFr: "Un vêtement spécial pour ressembler à une autre personne ou un personnage",
    },
    {
      english: "Gorro de fiesta",
      french: "Chapeau de fête",
      hintEn: "Un sombrero puntiagudo y colorido que se lleva en las fiestas",
      hintFr: "Un chapeau pointu et coloré qu'on porte aux fêtes",
    },
    {
      english: "Serpentina",
      french: "Serpentin",
      hintEn: "Una cinta enrollada de papel que se lanza en las fiestas",
      hintFr: "Un ruban enroulé de papier qu'on lance aux fêtes",
    },
    {
      english: "Fuegos artificiales",
      french: "Feu d'artifice",
      hintEn: "Luces de colores que explotan en el cielo por la noche",
      hintFr: "Des lumières de couleurs qui explosent dans le ciel la nuit",
    },
  ],
  "L'informatique": [
    {
      english: "Ordenador",
      french: "Ordinateur",
      hintEn: "Una máquina electrónica para trabajar, jugar y navegar por Internet",
      hintFr: "Une machine électronique pour travailler, jouer et naviguer sur Internet",
    },
    {
      english: "Teclado",
      french: "Clavier",
      hintEn: "La parte del ordenador con letras y números para escribir",
      hintFr: "La partie de l'ordinateur avec des lettres et des chiffres pour écrire",
    },
    {
      english: "Ratón",
      french: "Souris",
      hintEn: "Un objeto pequeño que mueves con la mano para hacer clic",
      hintFr: "Un petit objet que tu bouges avec la main pour cliquer",
    },
    {
      english: "Pantalla",
      french: "Écran",
      hintEn: "La parte del ordenador que muestra imágenes y texto",
      hintFr: "La partie de l'ordinateur qui affiche les images et le texte",
    },
    {
      english: "Internet",
      french: "Internet",
      hintEn: "La red mundial que conecta los ordenadores entre sí",
      hintFr: "Le réseau mondial qui connecte les ordinateurs entre eux",
    },
    {
      english: "Programa",
      french: "Logiciel",
      hintEn: "Un conjunto de instrucciones que le dice al ordenador qué hacer",
      hintFr: "Un ensemble d'instructions qui dit à l'ordinateur quoi faire",
    },
    {
      english: "Archivo",
      french: "Fichier",
      hintEn: "Un documento guardado en el ordenador",
      hintFr: "Un document enregistré dans l'ordinateur",
    },
    {
      english: "Impresora",
      french: "Imprimante",
      hintEn: "Una máquina que imprime documentos en papel",
      hintFr: "Une machine qui imprime des documents sur du papier",
    },
    {
      english: "Contraseña",
      french: "Mot de passe",
      hintEn: "Una palabra secreta para proteger tu cuenta",
      hintFr: "Un mot secret pour protéger ton compte",
    },
    {
      english: "Disco duro",
      french: "Disque dur",
      hintEn: "La parte del ordenador donde se guardan todos los archivos",
      hintFr: "La partie de l'ordinateur où sont stockés tous les fichiers",
    },
    {
      english: "Red",
      french: "Réseau",
      hintEn: "Un sistema que conecta varios ordenadores entre sí",
      hintFr: "Un système qui connecte plusieurs ordinateurs entre eux",
    },
    {
      english: "Aplicación",
      french: "Application",
      hintEn: "Un programa que usas en el teléfono o el ordenador",
      hintFr: "Un programme que tu utilises sur le téléphone ou l'ordinateur",
    },
  ],
  "Les formes": [
    {
      english: "Círculo",
      french: "Cercle",
      hintEn: "Una forma redonda sin esquinas",
      hintFr: "Une forme ronde sans coins",
    },
    {
      english: "Cuadrado",
      french: "Carré",
      hintEn: "Una forma con cuatro lados iguales y cuatro ángulos rectos",
      hintFr: "Une forme avec quatre côtés égaux et quatre angles droits",
    },
    {
      english: "Triángulo",
      french: "Triangle",
      hintEn: "Una forma con tres lados y tres ángulos",
      hintFr: "Une forme avec trois côtés et trois angles",
    },
    {
      english: "Rectángulo",
      french: "Rectangle",
      hintEn: "Una forma con cuatro lados, dos largos y dos cortos",
      hintFr: "Une forme avec quatre côtés, deux longs et deux courts",
    },
    {
      english: "Rombo",
      french: "Losange",
      hintEn: "Una forma con cuatro lados iguales como un diamante inclinado",
      hintFr: "Une forme avec quatre côtés égaux comme un diamant penché",
    },
    {
      english: "Óvalo",
      french: "Ovale",
      hintEn: "Una forma alargada y redondeada como un huevo",
      hintFr: "Une forme allongée et arrondie comme un œuf",
    },
    {
      english: "Estrella",
      french: "Étoile",
      hintEn: "Una forma con puntas que brilla en el cielo nocturno",
      hintFr: "Une forme avec des pointes qui brille dans le ciel la nuit",
    },
    {
      english: "Corazón",
      french: "Cœur",
      hintEn: "Una forma que simboliza el amor",
      hintFr: "Une forme qui symbolise l'amour",
    },
    {
      english: "Cruz",
      french: "Croix",
      hintEn: "Una forma con dos líneas que se cruzan",
      hintFr: "Une forme avec deux lignes qui se croisent",
    },
    {
      english: "Flecha",
      french: "Flèche",
      hintEn: "Una forma que indica una dirección",
      hintFr: "Une forme qui indique une direction",
    },
    {
      english: "Hexágono",
      french: "Hexagone",
      hintEn: "Una forma con seis lados, como las celdas de las abejas",
      hintFr: "Une forme avec six côtés, comme les alvéoles des abeilles",
    },
    {
      english: "Espiral",
      french: "Spirale",
      hintEn: "Una curva que gira alrededor de un punto central",
      hintFr: "Une courbe qui tourne autour d'un point central",
    },
  ],
};
